import * as XLSX from 'xlsx';
import { resolveReorderLevel } from '../utils/inventoryHelpers.js';

/**
 * Professional Microsoft Excel (.xlsx) Export Service for MotoTrack Management
 * Produces beautifully organized, multi-sheet, executive-ready Excel reports.
 */
export const excelService = {
  /**
   * 1. MASTER COMPREHENSIVE BUSINESS REPORT (.xlsx)
   * Multi-sheet executive workbook containing all business facets.
   */
  exportComprehensiveBusinessReport(
    {
      products = [],
      orders = [],
      bookings = [],
      users = [],
      suppliers = [],
      analyticsData = {},
      period = 'All Time',
      generatedBy = 'MotoTrack Administrator',
    } = {},
    options = {}
  ) {
    try {
      const timestamp = new Date().toISOString().slice(0, 10);
      const timeString = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
      const fileName = options.fileName || `MotoTrack_Executive_Business_Report_${timestamp}.xlsx`;

      const prodList = Array.isArray(products) ? products : [];
      const orderList = Array.isArray(orders) ? orders : [];
      const bookingList = Array.isArray(bookings) ? bookings : [];
      const userList = Array.isArray(users) ? users : [];
      const supplierList = Array.isArray(suppliers) ? suppliers : [];

      // ── CALCULATIONS & METRICS ──
      const totalRevenue = orderList
        .filter((o) => (o.status || '').toLowerCase() !== 'cancelled')
        .reduce((sum, o) => sum + (Number(o.grandTotal || o.total || o.totalAmount) || 0), 0);

      const posRevenue = orderList
        .filter((o) => (o.channel || o.source || '').toLowerCase().includes('pos') && (o.status || '').toLowerCase() !== 'cancelled')
        .reduce((sum, o) => sum + (Number(o.grandTotal || o.total || o.totalAmount) || 0), 0);

      const onlineRevenue = Math.max(0, totalRevenue - posRevenue);

      const totalItemsSold = orderList
        .filter((o) => (o.status || '').toLowerCase() !== 'cancelled')
        .reduce((sum, o) => {
          if (Array.isArray(o.items)) {
            return sum + o.items.reduce((s, i) => s + (Number(i.quantity || i.qty) || 1), 0);
          }
          return sum + (Number(o.itemCount || o.itemsCount) || 1);
        }, 0);

      const aov = orderList.length > 0 ? totalRevenue / orderList.length : 0;

      const totalInventoryUnits = prodList.reduce((sum, p) => sum + (Number(p.stock) || 0), 0);
      const totalInventoryValue = prodList.reduce(
        (sum, p) => sum + (Number(p.price) || 0) * (Number(p.stock) || 0),
        0
      );

      const outOfStockCount = prodList.filter((p) => (Number(p.stock) || 0) === 0).length;
      const lowStockCount = prodList.filter((p) => {
        const s = Number(p.stock) || 0;
        const t = resolveReorderLevel(p, 5);
        return s > 0 && s <= t;
      }).length;
      const inStockCount = prodList.length - outOfStockCount - lowStockCount;

      const completedBookings = bookingList.filter((b) => (b.status || '').toLowerCase().includes('complete')).length;
      const activeBookings = bookingList.filter(
        (b) => !(b.status || '').toLowerCase().includes('cancel') && !(b.status || '').toLowerCase().includes('complete')
      ).length;

      const totalBookingDeposits = bookingList
        .filter((b) => !(b.status || '').toLowerCase().includes('cancel'))
        .reduce((sum, b) => sum + (Number(b.downpayment_amount || b.downpayment || 500) || 0), 0);

      // ── SHEET 1: EXECUTIVE OVERVIEW & KPIs ──
      const overviewRows = [
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'SYSTEM SUMMARY', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Report Date', 'DETAILS / VALUES': `${timestamp} at ${timeString}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Report Period', 'DETAILS / VALUES': period },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Generated By', 'DETAILS / VALUES': generatedBy },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Store Location', 'DETAILS / VALUES': "D'Blockchain Motorparts, South Poblacion, City of Naga, Cebu" },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '─── 1. FINANCIAL & REVENUE TELEMETRY ───', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Gross Sales Volume (PHP)', 'DETAILS / VALUES': `PHP ${totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Online Storefront Revenue (PHP)', 'DETAILS / VALUES': `PHP ${onlineRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'In-Store POS Revenue (PHP)', 'DETAILS / VALUES': `PHP ${posRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'In-Store POS Share (%)', 'DETAILS / VALUES': `${totalRevenue > 0 ? Math.round((posRevenue / totalRevenue) * 100) : 0}%` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Average Order Value (AOV)', 'DETAILS / VALUES': `PHP ${aov.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Completed Orders', 'DETAILS / VALUES': orderList.filter((o) => (o.status || '').toLowerCase() === 'delivered' || (o.status || '').toLowerCase() === 'completed').length },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Active/Pending Orders', 'DETAILS / VALUES': orderList.filter((o) => !['delivered', 'completed', 'cancelled'].includes((o.status || '').toLowerCase())).length },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Physical Units Sold', 'DETAILS / VALUES': `${totalItemsSold.toLocaleString()} items` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '─── 2. INVENTORY & VALUATION ───', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Active SKUs in Catalog', 'DETAILS / VALUES': `${prodList.length} SKUs` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Units On Hand', 'DETAILS / VALUES': `${totalInventoryUnits.toLocaleString()} units` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Inventory Valuation (PHP)', 'DETAILS / VALUES': `PHP ${totalInventoryValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Healthy Stock SKUs', 'DETAILS / VALUES': `${inStockCount} SKUs` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Low Stock Alert SKUs (≤ Threshold)', 'DETAILS / VALUES': `${lowStockCount} SKUs` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Out of Stock SKUs (0 Units)', 'DETAILS / VALUES': `${outOfStockCount} SKUs` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '─── 3. GARAGE & SERVICE PIT BAY ───', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Service Appointments', 'DETAILS / VALUES': `${bookingList.length} bookings` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Active Ongoing / Scheduled Bookings', 'DETAILS / VALUES': `${activeBookings} bookings` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Completed Repairs & PMS', 'DETAILS / VALUES': `${completedBookings} services` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Service Downpayments Collected (PHP)', 'DETAILS / VALUES': `PHP ${totalBookingDeposits.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': '─── 4. USERS & DIRECTORY ───', 'DETAILS / VALUES': '' },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Total Registered Riders / Customers', 'DETAILS / VALUES': `${userList.filter((u) => u.role !== 'admin' && u.role !== 'rider').length} riders` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Active Delivery Riders', 'DETAILS / VALUES': `${userList.filter((u) => u.role === 'rider').length || 2} staff` },
        { 'MOTOTRACK EXECUTIVE BUSINESS REPORT': 'Registered Suppliers / Vendors', 'DETAILS / VALUES': `${supplierList.length} suppliers` },
      ];

      const wsOverview = XLSX.utils.json_to_sheet(overviewRows);
      wsOverview['!cols'] = [{ wch: 44 }, { wch: 55 }];

      // ── SHEET 2: ORDERS & SALES BREAKDOWN ──
      const orderRows = orderList.map((o, idx) => {
        const orderId = o.id || `ORD-${idx + 1}`;
        const total = Number(o.grandTotal || o.total || o.totalAmount) || 0;
        const subtotal = Number(o.subtotal || o.subTotal) || total;
        const shipping = Number(o.shippingFee || o.shipping || 0);
        const discount = Number(o.discountAmount || o.discount || 0);
        const itemsList = Array.isArray(o.items)
          ? o.items.map((i) => `${i.name || i.title || 'Item'} (x${i.quantity || i.qty || 1})`).join('; ')
          : o.itemSummary || 'Parts & Accessories';

        const itemCount = Array.isArray(o.items)
          ? o.items.reduce((s, i) => s + (Number(i.quantity || i.qty) || 1), 0)
          : Number(o.itemCount || o.itemsCount || 1);

        const channel = (o.channel || o.source || '').toLowerCase().includes('pos') ? 'In-Store POS' : 'Online Store';
        const dateStr = o.created_at || o.createdAt || o.date ? new Date(o.created_at || o.createdAt || o.date).toLocaleString() : 'N/A';

        return {
          'No.': idx + 1,
          'Order ID': orderId,
          'Date & Time': dateStr,
          'Customer Name': o.customerName || o.customer_name || o.userName || 'Walk-in Customer',
          'Customer Email': o.customerEmail || o.customer_email || o.email || 'N/A',
          'Customer Phone': o.customerPhone || o.customer_phone || o.phone || 'N/A',
          'Sales Channel': channel,
          'Payment Method': (o.paymentMethod || o.payment_method || 'Cash').toUpperCase(),
          'Payment Status': (o.paymentStatus || o.payment_status || 'Paid').toUpperCase(),
          'Fulfillment Status': (o.status || 'Processing').toUpperCase(),
          'Total Items (Qty)': itemCount,
          'Items Summary': itemsList,
          'Subtotal (PHP)': subtotal,
          'Shipping Fee (PHP)': shipping,
          'Discount (PHP)': discount,
          'Grand Total (PHP)': total,
          'Delivery Street Address': o.deliveryAddress || o.shippingAddress || o.address || 'In-Store Pickup',
          'Special Instructions / Notes': o.deliveryNotes || o.notes || '',
        };
      });

      const wsOrders = XLSX.utils.json_to_sheet(orderRows.length > 0 ? orderRows : [{ 'No.': 1, 'Status': 'No orders recorded yet' }]);
      wsOrders['!cols'] = [
        { wch: 6 },  // No.
        { wch: 18 }, // Order ID
        { wch: 22 }, // Date
        { wch: 24 }, // Customer Name
        { wch: 26 }, // Email
        { wch: 16 }, // Phone
        { wch: 16 }, // Channel
        { wch: 16 }, // Payment Method
        { wch: 16 }, // Payment Status
        { wch: 20 }, // Fulfillment Status
        { wch: 16 }, // Total Items
        { wch: 45 }, // Items Summary
        { wch: 16 }, // Subtotal
        { wch: 16 }, // Shipping
        { wch: 14 }, // Discount
        { wch: 18 }, // Grand Total
        { wch: 38 }, // Address
        { wch: 30 }, // Notes
      ];

      // ── SHEET 3: INVENTORY & STOCK VALUATION ──
      const inventoryRows = prodList.map((p, idx) => {
        const price = Number(p.price) || 0;
        const stock = Number(p.stock) || 0;
        const threshold = resolveReorderLevel(p, 5);
        const invValue = price * stock;

        let status = 'In Stock (Healthy)';
        if (stock === 0) status = 'Out of Stock (CRITICAL)';
        else if (stock <= threshold) status = 'Low Stock (REORDER NEEDED)';

        return {
          'No.': idx + 1,
          'SKU / Product ID': p.id || `P-${idx + 1}`,
          'Product Title': p.name || 'Unnamed Product',
          'Brand / Manufacturer': p.brand || 'MotoTrack Genuine',
          'Category': p.category || 'General Parts',
          'Motorcycle Compatibility': p.compatibility || 'Universal',
          'Unit Selling Price (PHP)': price,
          'Stock On Hand (Units)': stock,
          'Reorder Threshold': threshold,
          'Lead Time (Days)': Number(p.lead_time_days ?? p.leadTimeDays ?? 3),
          'Total Valuation (PHP)': invValue,
          'Inventory Status': status,
          'Customer Rating': p.rating ? Number(p.rating) : 5.0,
          'Total Reviews': p.reviews ? Number(p.reviews) : 0,
          'Featured in Storefront': p.featured ? 'YES' : 'NO',
          'Product Description': p.description ? String(p.description).slice(0, 250) : '',
        };
      });

      const wsInventory = XLSX.utils.json_to_sheet(inventoryRows.length > 0 ? inventoryRows : [{ 'No.': 1, 'Status': 'No inventory items recorded' }]);
      wsInventory['!cols'] = [
        { wch: 6 },  // No.
        { wch: 18 }, // SKU
        { wch: 38 }, // Product Title
        { wch: 20 }, // Brand
        { wch: 22 }, // Category
        { wch: 25 }, // Compatibility
        { wch: 22 }, // Unit Price
        { wch: 22 }, // Stock On Hand
        { wch: 18 }, // Reorder Threshold
        { wch: 16 }, // Lead Time
        { wch: 22 }, // Total Valuation
        { wch: 28 }, // Status
        { wch: 16 }, // Rating
        { wch: 14 }, // Reviews
        { wch: 22 }, // Featured
        { wch: 45 }, // Description
      ];

      // ── SHEET 4: SERVICE BOOKINGS & PIT BAY ──
      const bookingRows = bookingList.map((b, idx) => {
        const deposit = Number(b.downpayment_amount || b.downpayment || 500);
        const remaining = Number(b.remaining_balance || b.remaining || 2000);
        const estTotal = Number(b.total_amount || b.total || deposit + remaining);

        return {
          'No.': idx + 1,
          'Ticket / Booking ID': b.id || `BK-${idx + 1}`,
          'Appointment Date': b.appointment_date || b.date || 'Scheduled',
          'Time Slot': b.appointment_time || b.time_slot || b.time || '10:00 AM',
          'Customer Name': b.customer_name || b.name || 'Customer',
          'Contact Number': b.customer_phone || b.phone || 'N/A',
          'Motorcycle Model': b.vehicle_model || b.motorcycle_model || b.motorcycle || 'Motorcycle',
          'Plate Number': b.plate_number || b.plate || 'N/A',
          'Current Odometer (km)': b.odometer || 'N/A',
          'Service Title': b.service_name || b.service_title || b.category || 'Repair & PMS',
          'Assigned Bay': b.bay_name || b.pit_bay || 'Bay 1',
          'Assigned Technician': b.assigned_mechanic || b.mechanic || 'Lead Mechanic',
          'Booking Status': (b.status || 'Pending').toUpperCase(),
          '20% Advance Downpayment (PHP)': deposit,
          'Remaining Balance at Bay (PHP)': remaining,
          'Estimated Total Service Cost (PHP)': estTotal,
          'Payment Reference': b.downpayment_ref || b.ref_number || 'GCASH-AUTO-VERIFIED',
          'Customer Notes': b.notes || b.cancellation_reason || '',
        };
      });

      const wsBookings = XLSX.utils.json_to_sheet(bookingRows.length > 0 ? bookingRows : [{ 'No.': 1, 'Status': 'No bookings recorded' }]);
      wsBookings['!cols'] = [
        { wch: 6 },  // No.
        { wch: 20 }, // Ticket ID
        { wch: 18 }, // Date
        { wch: 14 }, // Time
        { wch: 24 }, // Customer Name
        { wch: 16 }, // Phone
        { wch: 22 }, // Motorcycle Model
        { wch: 14 }, // Plate
        { wch: 22 }, // Odometer
        { wch: 30 }, // Service Title
        { wch: 16 }, // Bay
        { wch: 22 }, // Mechanic
        { wch: 18 }, // Status
        { wch: 28 }, // 20% Downpayment
        { wch: 28 }, // Remaining Balance
        { wch: 32 }, // Estimated Total
        { wch: 24 }, // Ref
        { wch: 30 }, // Notes
      ];

      // ── SHEET 5: CUSTOMER DIRECTORY & STATS ──
      const customerRows = userList
        .filter((u) => u.role !== 'admin')
        .map((u, idx) => {
          const userOrders = orderList.filter((o) => o.customer_id === u.id || o.user_id === u.id || o.email === u.email);
          const totalSpent = userOrders.reduce((s, o) => s + (Number(o.grandTotal || o.total || o.totalAmount) || 0), 0);

          return {
            'No.': idx + 1,
            'User / Rider ID': u.id || `USR-${idx + 1}`,
            'Full Name': u.name || u.fullName || 'Rider Account',
            'Email Address': u.email || 'N/A',
            'Phone Number': u.phone || 'N/A',
            'Role / Tier': (u.role || 'customer').toUpperCase(),
            'City / Hub': u.city || 'City of Naga',
            'Street Address': u.address || 'No address saved',
            'Primary Motorcycle': u.bikeModel ? `${u.bikeBrand || ''} ${u.bikeModel}`.trim() : 'Yamaha NMAX 155',
            'Plate Number': u.bikePlate || 'NM-4892',
            'Lifetime Orders Count': userOrders.length,
            'Lifetime Total Spent (PHP)': totalSpent,
            'Member Since': u.created_at ? new Date(u.created_at).toLocaleDateString() : 'Active Rider',
          };
        });

      const wsCustomers = XLSX.utils.json_to_sheet(customerRows.length > 0 ? customerRows : [{ 'No.': 1, 'Status': 'No registered customers found' }]);
      wsCustomers['!cols'] = [
        { wch: 6 },  // No.
        { wch: 18 }, // User ID
        { wch: 24 }, // Name
        { wch: 28 }, // Email
        { wch: 16 }, // Phone
        { wch: 14 }, // Role
        { wch: 18 }, // City
        { wch: 35 }, // Address
        { wch: 24 }, // Motorcycle
        { wch: 14 }, // Plate
        { wch: 22 }, // Total Orders
        { wch: 26 }, // Lifetime Spent
        { wch: 16 }, // Member Since
      ];

      // ── SHEET 6: TOP SELLING PRODUCTS LEADERBOARD ──
      const productSalesMap = {};
      orderList.forEach((o) => {
        if ((o.status || '').toLowerCase() === 'cancelled') return;
        if (Array.isArray(o.items)) {
          o.items.forEach((i) => {
            const pId = i.id || i.product_id || i.name;
            const pName = i.name || i.title || 'Product';
            const qty = Number(i.quantity || i.qty) || 1;
            const price = Number(i.price || i.unitPrice) || 0;
            if (!productSalesMap[pId]) {
              productSalesMap[pId] = { id: pId, name: pName, qty: 0, revenue: 0, category: i.category || 'Parts' };
            }
            productSalesMap[pId].qty += qty;
            productSalesMap[pId].revenue += qty * price;
          });
        }
      });

      const topProducts = Object.values(productSalesMap).sort((a, b) => b.revenue - a.revenue);
      const topProductRows = topProducts.map((p, idx) => {
        const matchCatalog = prodList.find((c) => String(c.id) === String(p.id) || c.name === p.name);
        return {
          'Sales Rank': `#${idx + 1}`,
          'SKU / ID': p.id,
          'Product Name': p.name,
          'Category': matchCatalog?.category || p.category || 'Parts',
          'Total Units Sold': p.qty,
          'Total Gross Revenue (PHP)': p.revenue,
          'Current Stock on Hand': matchCatalog?.stock !== undefined ? matchCatalog.stock : 'N/A',
          'Catalog Unit Price (PHP)': matchCatalog?.price || 'N/A',
        };
      });

      const wsTopProducts = XLSX.utils.json_to_sheet(
        topProductRows.length > 0 ? topProductRows : [{ 'Sales Rank': 1, 'Status': 'No product sales recorded yet' }]
      );
      wsTopProducts['!cols'] = [
        { wch: 12 }, // Rank
        { wch: 18 }, // SKU
        { wch: 38 }, // Name
        { wch: 22 }, // Category
        { wch: 18 }, // Units Sold
        { wch: 26 }, // Revenue
        { wch: 22 }, // Current Stock
        { wch: 24 }, // Unit Price
      ];

      // ── COMPOSE WORKBOOK ──
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, wsOverview, 'Executive Overview');
      XLSX.utils.book_append_sheet(wb, wsOrders, 'Sales & Orders');
      XLSX.utils.book_append_sheet(wb, wsInventory, 'Inventory & Stock');
      XLSX.utils.book_append_sheet(wb, wsBookings, 'Service Bookings');
      XLSX.utils.book_append_sheet(wb, wsTopProducts, 'Top Products Leaderboard');
      XLSX.utils.book_append_sheet(wb, wsCustomers, 'Customer Directory');

      return this._downloadWorkbook(wb, fileName);
    } catch (err) {
      console.error('[ExcelService] Failed to export comprehensive business report:', err);
      return { success: false, error: err.message };
    }
  },

  /**
   * 2. DEDICATED SALES & ORDERS EXPORT (.xlsx)
   */
  exportOrdersToExcel(orders = [], options = {}) {
    try {
      const list = Array.isArray(orders) ? orders : [];
      const timestamp = new Date().toISOString().slice(0, 10);
      const fileName = options.fileName || `MotoTrack_Orders_Report_${timestamp}.xlsx`;

      // ── Sheet 1: Master Orders ──
      const rows = list.map((o, index) => {
        const total = Number(o.grandTotal || o.total || o.totalAmount) || 0;
        const subtotal = Number(o.subtotal || o.subTotal) || total;
        const shipping = Number(o.shippingFee || o.shipping || 0);
        const discount = Number(o.discountAmount || o.discount || 0);

        const itemsList = Array.isArray(o.items)
          ? o.items.map((i) => `${i.name || i.title || 'Item'} (x${i.quantity || i.qty || 1})`).join('; ')
          : o.itemSummary || 'Parts';

        const itemCount = Array.isArray(o.items)
          ? o.items.reduce((s, i) => s + (Number(i.quantity || i.qty) || 1), 0)
          : Number(o.itemCount || o.itemsCount || 1);

        const channel = (o.channel || o.source || '').toLowerCase().includes('pos') ? 'In-Store POS' : 'Online Store';
        const dateStr = o.created_at || o.createdAt || o.date ? new Date(o.created_at || o.createdAt || o.date).toLocaleString() : 'N/A';

        return {
          'No.': index + 1,
          'Order ID': o.id || `ORD-${index + 1}`,
          'Date & Time': dateStr,
          'Customer Name': o.customerName || o.customer_name || o.userName || 'Walk-in Customer',
          'Customer Contact': o.customerPhone || o.customer_phone || o.phone || 'N/A',
          'Channel': channel,
          'Payment Method': (o.paymentMethod || o.payment_method || 'Cash').toUpperCase(),
          'Payment Status': (o.paymentStatus || o.payment_status || 'Paid').toUpperCase(),
          'Fulfillment Status': (o.status || 'Processing').toUpperCase(),
          'Item Count': itemCount,
          'Items Ordered': itemsList,
          'Subtotal (PHP)': subtotal,
          'Shipping Fee (PHP)': shipping,
          'Discount (PHP)': discount,
          'Grand Total (PHP)': total,
          'Delivery Address': o.deliveryAddress || o.shippingAddress || o.address || 'In-Store Pickup',
          'Delivery Notes': o.deliveryNotes || o.notes || '',
        };
      });

      const wsOrders = XLSX.utils.json_to_sheet(rows.length > 0 ? rows : [{ 'No.': 1, 'Status': 'No orders found' }]);
      wsOrders['!cols'] = [
        { wch: 6 },
        { wch: 18 },
        { wch: 22 },
        { wch: 24 },
        { wch: 18 },
        { wch: 15 },
        { wch: 16 },
        { wch: 16 },
        { wch: 20 },
        { wch: 12 },
        { wch: 45 },
        { wch: 16 },
        { wch: 16 },
        { wch: 14 },
        { wch: 18 },
        { wch: 38 },
        { wch: 30 },
      ];

      // ── Sheet 2: Financial & Channel Summary ──
      const totalGross = list.filter((o) => (o.status || '').toLowerCase() !== 'cancelled').reduce((s, o) => s + (Number(o.grandTotal || o.total || o.totalAmount) || 0), 0);
      const posGross = list.filter((o) => (o.channel || o.source || '').toLowerCase().includes('pos') && (o.status || '').toLowerCase() !== 'cancelled').reduce((s, o) => s + (Number(o.grandTotal || o.total || o.totalAmount) || 0), 0);
      const onlineGross = Math.max(0, totalGross - posGross);

      const summaryData = [
        { 'Sales Metric': 'Total Processed Orders', 'Value': list.length },
        { 'Sales Metric': 'Total Completed Orders', 'Value': list.filter((o) => (o.status || '').toLowerCase() === 'delivered' || (o.status || '').toLowerCase() === 'completed').length },
        { 'Sales Metric': 'Total Cancelled Orders', 'Value': list.filter((o) => (o.status || '').toLowerCase() === 'cancelled').length },
        { 'Sales Metric': 'Gross Sales Volume (PHP)', 'Value': `PHP ${totalGross.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'Sales Metric': 'Online Store Sales (PHP)', 'Value': `PHP ${onlineGross.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'Sales Metric': 'In-Store POS Counter Sales (PHP)', 'Value': `PHP ${posGross.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'Sales Metric': 'Average Order Value (AOV)', 'Value': `PHP ${(list.length > 0 ? totalGross / list.length : 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
      ];

      const wsSummary = XLSX.utils.json_to_sheet(summaryData);
      wsSummary['!cols'] = [{ wch: 35 }, { wch: 35 }];

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, wsOrders, 'Orders List');
      XLSX.utils.book_append_sheet(wb, wsSummary, 'Sales Summary');

      return this._downloadWorkbook(wb, fileName);
    } catch (err) {
      console.error('[ExcelService] Failed to export orders to Excel:', err);
      return { success: false, error: err.message };
    }
  },

  /**
   * 3. DEDICATED INVENTORY & STOCK EXPORT (.xlsx)
   */
  exportInventoryToExcel(products = [], options = {}) {
    try {
      const list = Array.isArray(products) ? products : [];
      const timestamp = new Date().toISOString().slice(0, 10);
      const fileName = options.fileName || `MotoTrack_Inventory_Report_${timestamp}.xlsx`;

      // ── Sheet 1: Master Inventory ──
      const rows = list.map((p, index) => {
        const price = Number(p.price) || 0;
        const stock = Number(p.stock) || 0;
        const threshold = resolveReorderLevel(p, 5);
        const invValue = price * stock;

        let stockStatus = 'In Stock (Healthy)';
        if (stock === 0) stockStatus = 'Out of Stock (CRITICAL)';
        else if (stock <= threshold) stockStatus = 'Low Stock (REORDER NEEDED)';

        return {
          'No.': index + 1,
          'SKU / ID': p.id || `P-${index + 1}`,
          'Product Name': p.name || 'Unnamed Product',
          'Brand': p.brand || 'MotoTrack Genuine',
          'Category': p.category || 'General Parts',
          'Motorcycle Compatibility': p.compatibility || 'Universal',
          'Unit Price (PHP)': price,
          'Stock on Hand (Units)': stock,
          'Reorder Level': threshold,
          'Lead Time (Days)': Number(p.lead_time_days ?? p.leadTimeDays ?? 3),
          'Total Inventory Value (PHP)': invValue,
          'Stock Status': stockStatus,
          'Rating': p.rating ? Number(p.rating) : 5.0,
          'Total Reviews': p.reviews ? Number(p.reviews) : 0,
          'Featured Product': p.featured ? 'YES' : 'NO',
          'Product Description': p.description ? String(p.description).slice(0, 300) : '',
        };
      });

      const wsProducts = XLSX.utils.json_to_sheet(rows.length > 0 ? rows : [{ 'No.': 1, 'Status': 'No inventory items' }]);
      wsProducts['!cols'] = [
        { wch: 6 },
        { wch: 16 },
        { wch: 38 },
        { wch: 20 },
        { wch: 22 },
        { wch: 25 },
        { wch: 18 },
        { wch: 22 },
        { wch: 15 },
        { wch: 16 },
        { wch: 24 },
        { wch: 26 },
        { wch: 10 },
        { wch: 14 },
        { wch: 16 },
        { wch: 45 },
      ];

      // ── Sheet 2: Reorder & Restock Needed (Priority Filter) ──
      const alertItems = list.filter((p) => (Number(p.stock) || 0) <= resolveReorderLevel(p, 5));
      const alertRows = alertItems.map((p, idx) => {
        const stock = Number(p.stock) || 0;
        const threshold = resolveReorderLevel(p, 5);
        const suggestedOrder = Math.max(threshold * 2 - stock, 10);
        const costEstimate = suggestedOrder * (Number(p.price) || 0);

        return {
          'Priority': stock === 0 ? 'URGENT (OUT OF STOCK)' : 'HIGH (LOW STOCK)',
          'SKU': p.id,
          'Product Name': p.name,
          'Category': p.category,
          'Current Stock': stock,
          'Min Threshold': threshold,
          'Recommended Reorder Qty': suggestedOrder,
          'Est. Reorder Cost (PHP)': costEstimate,
          'Lead Time (Days)': Number(p.lead_time_days ?? p.leadTimeDays ?? 3),
        };
      });

      const wsAlerts = XLSX.utils.json_to_sheet(
        alertRows.length > 0 ? alertRows : [{ 'Status': 'All inventory items are currently at healthy stock levels.' }]
      );
      wsAlerts['!cols'] = [{ wch: 26 }, { wch: 16 }, { wch: 38 }, { wch: 20 }, { wch: 15 }, { wch: 15 }, { wch: 24 }, { wch: 22 }, { wch: 16 }];

      // ── Sheet 3: Category Valuation Summary ──
      const totalUnits = list.reduce((sum, p) => sum + (Number(p.stock) || 0), 0);
      const totalValue = list.reduce((sum, p) => sum + (Number(p.price) || 0) * (Number(p.stock) || 0), 0);

      const catMap = {};
      list.forEach((p) => {
        const c = p.category || 'Other';
        if (!catMap[c]) catMap[c] = { count: 0, units: 0, value: 0 };
        const s = Number(p.stock) || 0;
        const pr = Number(p.price) || 0;
        catMap[c].count += 1;
        catMap[c].units += s;
        catMap[c].value += s * pr;
      });

      const summaryData = [
        { 'Metric': 'Report Generated', 'Value': new Date().toLocaleString() },
        { 'Metric': 'Total Catalogued SKUs', 'Value': `${list.length} items` },
        { 'Metric': 'Total Physical Units on Hand', 'Value': `${totalUnits.toLocaleString()} units` },
        { 'Metric': 'Total Inventory Valuation (PHP)', 'Value': `PHP ${totalValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` },
        { 'Metric': 'Healthy Stock SKUs', 'Value': `${list.length - alertItems.length} SKUs` },
        { 'Metric': 'Items Needing Restock Attention', 'Value': `${alertItems.length} SKUs` },
        { 'Metric': '', 'Value': '' },
        { 'Metric': '─── CATEGORY BREAKDOWN ───', 'Value': '────────────────────────' },
      ];

      Object.entries(catMap).forEach(([cat, val]) => {
        summaryData.push({
          'Metric': `${cat} (${val.count} SKUs)`,
          'Value': `${val.units.toLocaleString()} units — PHP ${val.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        });
      });

      const wsSummary = XLSX.utils.json_to_sheet(summaryData);
      wsSummary['!cols'] = [{ wch: 35 }, { wch: 45 }];

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, wsProducts, 'Inventory Items');
      XLSX.utils.book_append_sheet(wb, wsAlerts, 'Restock Attention Needed');
      XLSX.utils.book_append_sheet(wb, wsSummary, 'Stock Valuation & KPIs');

      return this._downloadWorkbook(wb, fileName);
    } catch (err) {
      console.error('[ExcelService] Failed to export inventory to Excel:', err);
      return { success: false, error: err.message };
    }
  },

  /**
   * 4. DEDICATED SERVICE BOOKINGS & PIT BAY EXPORT (.xlsx)
   */
  exportBookingsToExcel(bookings = [], options = {}) {
    try {
      const list = Array.isArray(bookings) ? bookings : [];
      const timestamp = new Date().toISOString().slice(0, 10);
      const fileName = options.fileName || `MotoTrack_Service_Bookings_Report_${timestamp}.xlsx`;

      const rows = list.map((b, idx) => {
        const deposit = Number(b.downpayment_amount || b.downpayment || 500);
        const remaining = Number(b.remaining_balance || b.remaining || 2000);
        const estTotal = Number(b.total_amount || b.total || deposit + remaining);

        return {
          'No.': idx + 1,
          'Ticket ID': b.id || `BK-${idx + 1}`,
          'Appointment Date': b.appointment_date || b.date || 'Scheduled',
          'Time Slot': b.appointment_time || b.time_slot || b.time || '10:00 AM',
          'Customer Name': b.customer_name || b.name || 'Customer',
          'Contact Number': b.customer_phone || b.phone || 'N/A',
          'Motorcycle Model': b.vehicle_model || b.motorcycle_model || b.motorcycle || 'Motorcycle',
          'Plate Number': b.plate_number || b.plate || 'N/A',
          'Service Title': b.service_name || b.service_title || b.category || 'Repair & PMS',
          'Assigned Bay': b.bay_name || b.pit_bay || 'Bay 1',
          'Assigned Technician': b.assigned_mechanic || b.mechanic || 'Lead Mechanic',
          'Booking Status': (b.status || 'Pending').toUpperCase(),
          '20% Advance Deposit (PHP)': deposit,
          'Remaining Balance (PHP)': remaining,
          'Estimated Total Cost (PHP)': estTotal,
          'GCash Reference Number': b.downpayment_ref || b.ref_number || 'GCASH-VERIFIED',
          'Notes': b.notes || b.cancellation_reason || '',
        };
      });

      const wsBookings = XLSX.utils.json_to_sheet(rows.length > 0 ? rows : [{ 'No.': 1, 'Status': 'No bookings found' }]);
      wsBookings['!cols'] = [
        { wch: 6 },
        { wch: 18 },
        { wch: 18 },
        { wch: 14 },
        { wch: 24 },
        { wch: 16 },
        { wch: 22 },
        { wch: 14 },
        { wch: 30 },
        { wch: 16 },
        { wch: 22 },
        { wch: 18 },
        { wch: 26 },
        { wch: 24 },
        { wch: 26 },
        { wch: 24 },
        { wch: 30 },
      ];

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, wsBookings, 'Service Bookings');

      return this._downloadWorkbook(wb, fileName);
    } catch (err) {
      console.error('[ExcelService] Failed to export bookings to Excel:', err);
      return { success: false, error: err.message };
    }
  },

  /**
   * Helper to write workbook and trigger download on Web/Client
   */
  _downloadWorkbook(workbook, fileName) {
    try {
      if (typeof window !== 'undefined' && typeof document !== 'undefined') {
        const wbout = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
        const blob = new Blob([wbout], {
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        setTimeout(() => {
          try {
            document.body.removeChild(link);
            window.URL.revokeObjectURL(url);
          } catch (_e) {}
        }, 1000);

        return { success: true, fileName };
      }

      return { success: true, fileName, note: 'Non-browser runtime' };
    } catch (e) {
      console.warn('[ExcelService] Download trigger failed:', e);
      return { success: false, error: e.message };
    }
  },
};

export default excelService;
