import { StyleSheet, Platform } from 'react-native';

export const adminStyles = StyleSheet.create({
  // ─── BASE LAYOUT ───
  container: {
    flex: 1,
    backgroundColor: '#F6F8FC',
  },
  adminLayout: {
    flex: 1,
    flexDirection: 'row',
  },

  // ─── 1. SIDEBAR NAVIGATION (DESKTOP) ───
  sidebar: {
    width: 260,
    backgroundColor: '#FFFFFF',
    borderRightWidth: 1,
    borderRightColor: '#E2E8F0',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 16,
    height: Platform.OS === 'web' ? '100vh' : '100%',
    maxHeight: Platform.OS === 'web' ? '100vh' : '100%',
    position: Platform.OS === 'web' ? 'sticky' : 'relative',
    top: 0,
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 3,
  },
  sidebarNavScroll: {
    flex: 1,
    marginHorizontal: -16,
    paddingHorizontal: 16,
    marginTop: 10,
    marginBottom: 8,
  },

  // ─── ADMIN MOBILE BOTTOM NAVIGATION BAR ───
  bottomNavWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 8,
    paddingBottom: Platform.OS === 'ios' ? 24 : 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 16,
    zIndex: 9999,
  },
  bottomNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 4,
    minWidth: 52,
    position: 'relative',
  },
  bottomNavIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  bottomNavIconWrapActive: {
    backgroundColor: '#F3F7F6',
  },
  bottomNavLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#64748B',
  },
  bottomNavLabelActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  bottomNavBadge: {
    position: 'absolute',
    top: 0,
    right: 6,
    backgroundColor: '#EF4444',
    borderRadius: 8,
    minWidth: 14,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  bottomNavBadgeText: {
    color: '#FFFFFF',
    fontSize: 8.5,
    fontWeight: '900',
  },
  mobileMoreSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
    paddingBottom: Platform.OS === 'ios' ? 36 : 24,
    width: '100%',
    maxHeight: '80%',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 20,
  },
  mobileMoreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  mobileMoreCard: {
    width: '48%',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  mobileMoreCardActive: {
    backgroundColor: '#F3F7F6',
    borderColor: '#0C6258',
  },
  sidebarCompact: {
    width: 68,
    paddingHorizontal: 8,
  },
  sidebarBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  sidebarLogo: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  sidebarLogoAccent: {
    color: '#0C6258',
  },
  adminTagBadge: {
    backgroundColor: '#F3F7F6',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#D1ECE6',
  },
  adminTagBadgeText: {
    color: '#0C6258',
    fontSize: 10.5,
    fontWeight: '800',
  },
  adminProfileBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F8FAFC',
    padding: 10,
    borderRadius: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  adminAvatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0C6258',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  adminAvatarText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: -1,
    right: -1,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  profileNameText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
  },
  profileRoleText: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '500',
  },
  navHeading: {
    fontSize: 11,
    fontWeight: '800',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 10,
    marginBottom: 8,
    paddingHorizontal: 6,
  },
  sidebarNavList: {
    gap: 4,
  },
  sidebarNavItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  sidebarNavItemActive: {
    backgroundColor: '#0C6258',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  sidebarNavLabel: {
    flex: 1,
    fontSize: 13.5,
    fontWeight: '600',
    color: '#475569',
  },
  sidebarNavLabelActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  sidebarCountBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  sidebarCountBadgeActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  sidebarCountText: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '700',
  },
  sidebarCountTextActive: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  sidebarFooter: {
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    gap: 10,
  },
  sidebarStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 4,
  },
  statusDotGreen: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  sidebarStatusText: {
    color: '#64748B',
    fontSize: 11.5,
    fontWeight: '600',
  },
  logoutSidebarBtn: {
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
  },
  logoutSidebarText: {
    color: '#DC2626',
    fontSize: 12.5,
    fontWeight: '700',
  },

  // ─── 2. MAIN CONTENT AREA ───
  mainContentArea: {
    flex: 1,
    backgroundColor: '#F6F8FC',
  },
  topContentBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    flexWrap: 'wrap',
    gap: 12,
  },
  pageBreadcrumbTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  topActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addBtnPrimary: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  addBtnPrimaryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  quickStoreBtn: {
    backgroundColor: '#F3F7F6',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1ECE6',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quickStoreBtnText: {
    color: '#0C6258',
    fontSize: 12.5,
    fontWeight: '700',
  },
  mainScroll: {
    padding: 16,
    paddingBottom: 110,
  },

  // ─── 3. STATS & KPI GRID ───
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    minWidth: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    position: 'relative',
    overflow: 'hidden',
  },
  statCardTealAccent: {
    borderTopWidth: 4,
    borderTopColor: '#0C6258',
  },
  statCardWarningAccent: {
    borderTopWidth: 4,
    borderTopColor: '#F59E0B',
  },
  statCardDangerAccent: {
    borderTopWidth: 4,
    borderTopColor: '#EF4444',
  },
  statCardSuccessAccent: {
    borderTopWidth: 4,
    borderTopColor: '#10B981',
  },
  statIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#F3F7F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  statSub: {
    fontSize: 11.5,
    color: '#64748B',
    fontWeight: '500',
  },

  // ─── 4. CARDS & TABLES ───
  tableCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  tableHeaderCell: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  tableRowHighlight: {
    backgroundColor: '#FFFBEB',
  },
  tableRowDanger: {
    backgroundColor: '#FEF2F2',
  },
  productThumb: {
    width: 44,
    height: 44,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: '#F1F5F9',
  },
  tableTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  tableSub: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  tableInputInline: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: 5,
    paddingHorizontal: 8,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },
  actionIconBtn: {
    padding: 7,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    marginLeft: 6,
  },
  actionIconBtnDanger: {
    backgroundColor: '#FEE2E2',
  },
  actionIconBtnSuccess: {
    backgroundColor: '#D1FAE5',
  },
  actionIconBtnWarning: {
    backgroundColor: '#FEF3C7',
  },
  promoStatusToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
  },
  promoStatusActive: {
    backgroundColor: '#DCFCE7',
    borderColor: '#86EFAC',
  },
  promoStatusInactive: {
    backgroundColor: '#F1F5F9',
    borderColor: '#CBD5E1',
  },
  promoToggleDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  promoToggleDotActive: {
    backgroundColor: '#16A34A',
  },
  promoToggleDotInactive: {
    backgroundColor: '#94A3B8',
  },
  promoStatusText: {
    fontSize: 11.5,
    fontWeight: '800',
  },
  promoStatusTextActive: {
    color: '#166534',
  },
  promoStatusTextInactive: {
    color: '#64748B',
  },

  // ─── 5. TOOLBAR & FILTERS ───
  toolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 12,
  },
  searchInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    height: 44,
    minWidth: 260,
    flex: 1,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    color: '#0F172A',
    fontSize: 13.5,
    fontWeight: '500',
    paddingVertical: 0,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },

  // Filter Pills
  filterPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterPillActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  filterPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  filterPillTextActive: {
    color: '#FFFFFF',
  },

  // ─── 6. INVENTORY MANAGEMENT STYLES ───
  stockStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'center',
  },
  stockInStock: {
    backgroundColor: '#D1FAE5',
  },
  stockInStockText: {
    color: '#065F46',
    fontSize: 11,
    fontWeight: '800',
  },
  stockLow: {
    backgroundColor: '#FEF3C7',
  },
  stockLowText: {
    color: '#92400E',
    fontSize: 11,
    fontWeight: '800',
  },
  stockOut: {
    backgroundColor: '#FEE2E2',
  },
  stockOutText: {
    color: '#991B1B',
    fontSize: 11,
    fontWeight: '800',
  },
  stockAdjustBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  stockMiniBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  stockMiniBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  inventoryAlertBanner: {
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  inventoryAlertText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400E',
    flex: 1,
  },

  // ─── 7. POS (POINT OF SALE) CASHIER TERMINAL ───
  posContainer: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
  },
  posCatalogColumn: {
    flex: 3,
    minWidth: 260,
    width: '100%',
  },
  posRegisterColumn: {
    flex: 2,
    minWidth: 260,
    width: '100%',
  },
  posGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  posProductCard: {
    width: '48%',
    minWidth: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
    position: 'relative',
  },
  posProductCardDisabled: {
    opacity: 0.5,
    backgroundColor: '#F8FAFC',
  },
  posProductImg: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    marginBottom: 8,
  },
  posProductBrand: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  posProductName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 6,
    height: 34,
  },
  posProductPrice: {
    fontSize: 14.5,
    fontWeight: '900',
    color: '#0C6258',
  },
  posAddBtn: {
    backgroundColor: '#F3F7F6',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#D1ECE6',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
  },
  posAddBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0C6258',
  },

  // POS Register Cart
  posRegisterCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  posRegisterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 12,
  },
  posRegisterTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  posCustomerSelector: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 14,
  },
  posCustomerLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  posCustomerPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  posCartItemsList: {
    maxHeight: 240,
    marginBottom: 14,
  },
  posCartItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 8,
  },
  posCartItemName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  posCartItemPrice: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  posQtyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  posQtyBtn: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  posQtyText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    minWidth: 18,
    textAlign: 'center',
  },
  posSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  posSummaryLabel: {
    fontSize: 12.5,
    color: '#64748B',
    fontWeight: '500',
  },
  posSummaryVal: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  posGrandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    marginTop: 6,
    borderTopWidth: 1.5,
    borderTopColor: '#E2E8F0',
  },
  posGrandTotalLabel: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0F172A',
  },
  posGrandTotalVal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0C6258',
  },
  posPayMethodRow: {
    flexDirection: 'row',
    gap: 6,
    marginVertical: 12,
    flexWrap: 'wrap',
  },
  posPayMethodBtn: {
    flex: 1,
    minWidth: 70,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  posPayMethodBtnActive: {
    backgroundColor: '#F3F7F6',
    borderColor: '#0C6258',
    borderWidth: 1.5,
  },
  posPayMethodText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
  },
  posPayMethodTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  posTenderBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
  },
  posQuickCashRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  posQuickCashChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  posQuickCashChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
  },
  posChangeBanner: {
    backgroundColor: '#ECFDF5',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  posChangeBannerText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#065F46',
  },
  posChangeBannerAmount: {
    fontSize: 15,
    fontWeight: '900',
    color: '#047857',
  },
  posCheckoutBtn: {
    backgroundColor: '#0C6258',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  posCheckoutBtnDisabled: {
    backgroundColor: '#94A3B8',
    shadowOpacity: 0,
  },
  posCheckoutBtnText: {
    color: '#FFFFFF',
    fontSize: 14.5,
    fontWeight: '900',
  },

  // ─── 8. ANALYTICS & CHARTS ───
  analyticsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 20,
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  analyticsCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  analyticsCardTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  analyticsCardSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  analyticsPeriodTabs: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#F1F5F9',
    padding: 3,
    borderRadius: 10,
  },
  analyticsPeriodTab: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  analyticsPeriodTabActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  analyticsPeriodTabText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#64748B',
  },
  analyticsPeriodTabTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  chartBarContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 180,
    paddingTop: 20,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    gap: 8,
  },
  chartBarCol: {
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  chartBarPill: {
    width: '100%',
    maxWidth: 36,
    backgroundColor: '#0C6258',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    minHeight: 8,
  },
  chartBarPillAlt: {
    backgroundColor: '#56B9A1',
  },
  chartBarLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    marginTop: 6,
  },
  chartBarVal: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0C6258',
    marginBottom: 4,
  },
  leaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 12,
  },
  leaderboardRank: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F3F7F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  leaderboardRankText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#0C6258',
  },
  progressBarTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F1F5F9',
    overflow: 'hidden',
    marginTop: 6,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0C6258',
    borderRadius: 4,
  },

  // ─── 9. MODALS ───
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    ...(Platform.OS === 'web' ? { backdropFilter: 'blur(4px)' } : {}),
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    width: '100%',
    maxWidth: 640,
    maxHeight: '90%',
    padding: 22,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 17.5,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  modalBody: {
    maxHeight: 500,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 6,
    marginTop: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  formInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13.5,
    color: '#0F172A',
    marginBottom: 4,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },
  imageUploadBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    borderStyle: 'dashed',
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    marginTop: 4,
  },
  imageUploadPreviewWrap: {
    width: '100%',
    height: 140,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
    backgroundColor: '#F1F5F9',
    position: 'relative',
  },
  imageUploadPreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  uploadButtonRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 6,
  },
  uploadActionBtn: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  uploadActionBtnSecondary: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  uploadActionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  presetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
    marginBottom: 10,
  },
  presetThumbBtn: {
    width: 48,
    height: 48,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
  },
  presetThumbBtnActive: {
    borderColor: '#0C6258',
    borderWidth: 2.5,
  },
  presetThumbImg: {
    width: '100%',
    height: '100%',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },

  // ─── 10. DIGITAL RECEIPT MODAL (THERMAL TICKET STYLE) ───
  receiptSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    maxWidth: 420,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 20,
  },
  receiptLogo: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    textAlign: 'center',
  },
  receiptSub: {
    fontSize: 11,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 2,
  },
  receiptDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#CBD5E1',
    borderStyle: 'dashed',
    marginVertical: 14,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  receiptText: {
    fontSize: 12,
    color: '#475569',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  receiptTextBold: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  receiptBarcode: {
    height: 44,
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    marginVertical: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  receiptBarcodeText: {
    fontSize: 12,
    letterSpacing: 4,
    fontWeight: '900',
    color: '#334155',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },

  sqlBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    maxHeight: 180,
  },
  sqlCodeText: {
    color: '#0C6258',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11.5,
    lineHeight: 18,
  },

  // ─── ORDER MANAGEMENT STYLES ───
  paymentDropdownContainer: {
    position: 'relative',
    zIndex: 99999,
    elevation: 99999,
  },
  dropdownDismissBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 99998,
  },
  paymentDropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
    minWidth: 150,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  paymentDropdownTriggerActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  paymentDropdownTriggerText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  paymentDropdownMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 6,
    width: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 6,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 99999,
    zIndex: 99999,
    maxHeight: 260,
  },
  paymentDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  paymentDropdownItemActive: {
    backgroundColor: '#F3F7F6',
  },
  paymentDropdownItemText: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
  },
  paymentDropdownItemTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  orderFilterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  orderFilterTab: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  orderFilterTabActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  orderFilterTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  orderFilterTabTextActive: {
    color: '#FFFFFF',
  },
  codAlertBanner: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  codAlertBannerText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#92400E',
  },
  codAlertBannerSub: {
    fontSize: 11.5,
    color: '#B45309',
    marginTop: 2,
  },
  approveAllCodBtn: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  approveAllCodBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  orderActionBtnGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  btnApproveCod: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnApproveCodText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  btnAdvanceOrder: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnAdvanceOrderText: {
    color: '#1D4ED8',
    fontSize: 11,
    fontWeight: '700',
  },
  btnViewOrder: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnViewOrderText: {
    color: '#334155',
    fontSize: 11,
    fontWeight: '700',
  },
  btnCancelOrder: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnCancelOrderText: {
    color: '#DC2626',
    fontSize: 11,
    fontWeight: '700',
  },
});
