import { StyleSheet, Platform } from 'react-native';

export const getAdminThemeTokens = (isDark = false) => {
  if (isDark) {
    return {
      isDark: true,
      bgMain: '#020617',
      bgCard: 'rgba(15, 23, 42, 0.6)',
      bgSub: 'rgba(30, 41, 59, 0.5)',
      bgSubtle: 'rgba(30, 41, 59, 0.3)',
      border: 'rgba(255, 255, 255, 0.08)',
      borderLight: 'rgba(255, 255, 255, 0.04)',
      borderInput: 'rgba(255, 255, 255, 0.12)',
      textPrimary: '#F8FAFC',
      textSecondary: '#E2E8F0',
      textMuted: '#94A3B8',
      textSubtle: '#64748B',
      sidebarBg: 'rgba(2, 6, 23, 0.65)',
      topBarBg: 'rgba(2, 6, 23, 0.85)',
      inputBg: 'rgba(15, 23, 42, 0.6)',
      modalBg: '#0F172A',
      modalOverlay: 'rgba(0, 0, 0, 0.85)',
      cardShadow: 'rgba(0, 0, 0, 0.5)',
      accent: '#10B981',
      accentBrand: '#10B981',
      accentBg: 'rgba(16, 185, 129, 0.15)',
      accentBorder: 'rgba(16, 185, 129, 0.3)',
      tableHeaderBg: 'rgba(30, 41, 59, 0.6)',
      tableRowBg: 'transparent',
      tableRowBorder: 'rgba(255, 255, 255, 0.06)',
      tableRowHighlight: '#2A2315',
      tableRowDanger: '#2D161A',
      chipBg: '#1E293B',
      chipBorder: '#374151',
      chipText: '#94A3B8',
      badgeNeutralBg: '#1F2937',
      badgeNeutralText: '#CBD5E1',
      statusSuccessBg: 'rgba(16, 185, 129, 0.15)',
      statusSuccessText: '#34D399',
      statusWarningBg: 'rgba(245, 158, 11, 0.15)',
      statusWarningText: '#FBBF24',
      statusDangerBg: 'rgba(239, 68, 68, 0.15)',
      statusDangerText: '#F87171',
      statusInfoBg: 'rgba(59, 130, 246, 0.15)',
      statusInfoText: '#60A5FA',
    };
  }
  return {
    isDark: false,
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    bgSub: '#F1F5F9',
    bgSubtle: '#F8FAFC',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    borderInput: '#CBD5E1',
    textPrimary: '#0F172A',
    textSecondary: '#334155',
    textMuted: '#64748B',
    textSubtle: '#94A3B8',
    sidebarBg: '#FFFFFF',
    topBarBg: '#FFFFFF',
    inputBg: '#FFFFFF',
    modalBg: '#FFFFFF',
    modalOverlay: 'rgba(15, 23, 42, 0.6)',
    cardShadow: '#0F172A',
    accent: '#0C6258',
    accentBrand: '#0C6258',
    accentBg: '#F0FDF4',
    accentBorder: '#BBF7D0',
    tableHeaderBg: '#F8FAFC',
    tableRowBg: '#FFFFFF',
    tableRowBorder: '#F1F5F9',
    tableRowHighlight: '#FFFBEB',
    tableRowDanger: '#FEF2F2',
    chipBg: '#FFFFFF',
    chipBorder: '#E2E8F0',
    chipText: '#475569',
    badgeNeutralBg: '#F1F5F9',
    badgeNeutralText: '#334155',
    statusSuccessBg: '#DCFCE7',
    statusSuccessText: '#15803D',
    statusWarningBg: '#FEF3C7',
    statusWarningText: '#B45309',
    statusDangerBg: '#FEE2E2',
    statusDangerText: '#B91C1C',
    statusInfoBg: '#EFF6FF',
    statusInfoText: '#1D4ED8',
  };
};

export const createAdminStyles = (isDark = false) => {
  const t = getAdminThemeTokens(isDark);
  return StyleSheet.create({
  // ─── BASE LAYOUT ───
  container: {
    flex: 1,
    backgroundColor: t.bgMain,
  },
  adminLayout: {
    flex: 1,
    flexDirection: 'row',
    minHeight: Platform.OS === 'web' ? '100vh' : '100%',
    backgroundColor: t.bgMain,
  },

  // ─── 1. SIDEBAR NAVIGATION (DESKTOP) ───
  sidebar: {
    width: 225,
    flexShrink: 0,
    backgroundColor: t.bgCard,
    borderRightWidth: 1,
    borderRightColor: t.border,
    paddingHorizontal: 12,
    paddingTop: 18,
    paddingBottom: 16,
    height: Platform.OS === 'web' ? '100vh' : '100%',
    maxHeight: Platform.OS === 'web' ? '100vh' : '100%',
    position: Platform.OS === 'web' ? 'sticky' : 'relative',
    top: 0,
    justifyContent: 'space-between',
    shadowColor: t.cardShadow,
    shadowOffset: { width: 1, height: 0 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 3,
    zIndex: 100,
  },
  sidebarNavScroll: {
    flex: 1,
    marginHorizontal: -12,
    paddingHorizontal: 12,
    marginTop: 10,
    marginBottom: 8,
  },

  // ─── ADMIN MOBILE BOTTOM NAVIGATION BAR ───
  bottomNavWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: t.bgCard,
    borderTopWidth: 1,
    borderTopColor: t.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 8,
    paddingBottom: Platform.OS === 'ios' ? 24 : 10,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 16,
    zIndex: 9999,
  },
  bottomNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 4,
    minWidth: 52,
    position: 'relative',
  },
  bottomNavIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  bottomNavIconWrapActive: {
    backgroundColor: t.accentBg,
  },
  bottomNavLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    color: t.textMuted,
  },
  bottomNavLabelActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  bottomNavBadge: {
    position: 'absolute',
    top: 0,
    right: 6,
    backgroundColor: '#EF4444',
    borderRadius: 8,
    minWidth: 14,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  bottomNavBadgeText: {
    color: '#FFFFFF',
    fontSize: 8.5,
    fontWeight: '900',
  },
  mobileMoreSheet: {
    backgroundColor: t.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
    paddingBottom: Platform.OS === 'ios' ? 36 : 24,
    width: '100%',
    maxHeight: '80%',
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 20,
  },
  mobileMoreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  mobileMoreCard: {
    width: '48%',
    backgroundColor: t.bgSub,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: t.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  mobileMoreCardActive: {
    backgroundColor: t.accentBg,
    borderColor: '#0C6258',
  },
  sidebarCompact: {
    width: 68,
    paddingHorizontal: 8,
  },
  sidebarBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  sidebarLogo: {
    fontSize: 20,
    fontWeight: '900',
    color: t.textPrimary,
    letterSpacing: -0.5,
  },
  sidebarLogoAccent: {
    color: '#0C6258',
  },
  adminTagBadge: {
    backgroundColor: t.accentBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: t.accentBorder,
  },
  adminTagBadgeText: {
    color: '#0C6258',
    fontSize: 10.5,
    fontWeight: '800',
  },
  adminProfileBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: t.bgSub,
    padding: 10,
    borderRadius: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: t.border,
  },
  adminAvatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0C6258',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  adminAvatarText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: -1,
    right: -1,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  profileNameText: {
    color: t.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  profileRoleText: {
    color: t.textMuted,
    fontSize: 11,
    fontWeight: '500',
  },
  navHeading: {
    fontSize: 11,
    fontWeight: '800',
    color: t.textSubtle,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 14,
    marginBottom: 6,
    paddingHorizontal: 6,
  },
  sidebarNavList: {
    gap: 4,
  },
  sidebarNavItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: 'transparent',
  },
  sidebarNavItemActive: {
    backgroundColor: '#0C6258',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  sidebarNavLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: t.textSecondary,
  },
  sidebarNavLabelActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  sidebarCountBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  sidebarCountBadgeActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  sidebarCountText: {
    color: t.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  sidebarCountTextActive: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  sidebarFooter: {
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: t.borderLight,
    gap: 10,
  },
  sidebarStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 4,
  },
  statusDotGreen: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  sidebarStatusText: {
    color: t.textMuted,
    fontSize: 11.5,
    fontWeight: '600',
  },
  logoutSidebarBtn: {
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
  },
  logoutSidebarText: {
    color: '#DC2626',
    fontSize: 12.5,
    fontWeight: '700',
  },

  // ─── 2. MAIN CONTENT AREA ───
  mainContentArea: {
    flex: 1,
    backgroundColor: t.bgMain,
  },
  topContentBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: t.border,
    backgroundColor: t.bgCard,
    flexWrap: 'wrap',
    gap: 12,
  },
  pageBreadcrumbTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: t.textPrimary,
    letterSpacing: -0.3,
  },
  topActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addBtnPrimary: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addBtnPrimaryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  quickStoreBtn: {
    backgroundColor: t.accentBg,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.accentBorder,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quickStoreBtnText: {
    color: '#0C6258',
    fontSize: 12.5,
    fontWeight: '700',
  },
  mainScroll: {
    padding: 16,
    paddingBottom: 110,
  },

  // ─── 3. STATS & KPI GRID ───
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    minWidth: 200,
    backgroundColor: t.bgCard,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: t.border,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    position: 'relative',
    overflow: 'hidden',
  },
  statCardTealAccent: {
    borderWidth: 1.5,
    borderColor: '#0D9488',
  },
  statCardWarningAccent: {
    borderWidth: 1.5,
    borderColor: '#F59E0B',
  },
  statCardDangerAccent: {
    borderWidth: 1.5,
    borderColor: '#FB7185',
  },
  statCardSuccessAccent: {
    borderWidth: 1.5,
    borderColor: '#3B82F6', // Blue like the screenshot's 4th card
  },
  statIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: t.accentBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  statLabel: {
    fontSize: 10.5,
    lineHeight: 16,
    fontWeight: '800',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  statValue: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
    color: t.textPrimary,
    letterSpacing: -0.5,
  },
  statSub: {
    fontSize: 11.5,
    lineHeight: 16,
    color: '#9CA3AF',
    fontWeight: '500',
  },

  // ─── 4. CARDS & TABLES ───
  tableScrollContainer: {
    width: '100%',
    ...(Platform.OS === 'web' ? { overflowX: 'auto' } : {}),
  },
  sectionCard: {
    backgroundColor: t.bgCard,
    borderRadius: 16,
    padding: 22,
    borderWidth: 1,
    borderColor: t.border,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 20,
  },
  tableCard: {
    backgroundColor: t.bgCard,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: t.border,
    overflow: 'hidden',
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    width: '100%',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
    backgroundColor: t.bgSub,
    borderBottomWidth: 1,
    borderBottomColor: t.border,
  },
  tableHeaderCell: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    color: t.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: t.borderLight,
    backgroundColor: t.bgCard,
    minHeight: 56,
  },
  tableRowHighlight: {
    backgroundColor: t.tableRowHighlight,
  },
  tableRowDanger: {
    backgroundColor: t.tableRowDanger,
  },
  productThumb: {
    width: 42,
    height: 42,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: '#F1F5F9',
    flexShrink: 0,
  },
  tableTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: t.textPrimary,
  },
  tableSub: {
    fontSize: 11.5,
    lineHeight: 16,
    color: t.textMuted,
    marginTop: 2,
  },
  tableInputInline: {
    backgroundColor: t.bgSub,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: t.borderInput,
    color: t.textPrimary,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: 5,
    paddingHorizontal: 8,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },
  actionIconBtn: {
    padding: 7,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    marginLeft: 6,
  },
  actionIconBtnDanger: {
    backgroundColor: '#FEE2E2',
  },
  actionIconBtnSuccess: {
    backgroundColor: '#D1FAE5',
  },
  actionIconBtnWarning: {
    backgroundColor: '#FEF3C7',
  },
  promoStatusToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
  },
  promoStatusActive: {
    backgroundColor: '#DCFCE7',
    borderColor: '#86EFAC',
  },
  promoStatusInactive: {
    backgroundColor: '#F1F5F9',
    borderColor: t.borderInput,
  },
  promoToggleDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  promoToggleDotActive: {
    backgroundColor: '#16A34A',
  },
  promoToggleDotInactive: {
    backgroundColor: '#94A3B8',
  },
  promoStatusText: {
    fontSize: 11.5,
    fontWeight: '800',
  },
  promoStatusTextActive: {
    color: '#166534',
  },
  promoStatusTextInactive: {
    color: t.textMuted,
  },

  // ─── 5. TOOLBAR & FILTERS ───
  toolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 12,
  },
  searchInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.bgCard,
    borderRadius: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: t.border,
    height: 44,
    minWidth: 260,
    flex: 1,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    color: t.textPrimary,
    fontSize: 13.5,
    fontWeight: '500',
    paddingVertical: 0,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },

  // Filter Pills
  filterPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: t.bgCard,
    borderWidth: 1,
    borderColor: t.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterPillActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  filterPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: t.textMuted,
  },
  filterPillTextActive: {
    color: '#FFFFFF',
  },

  // ─── 6. INVENTORY MANAGEMENT STYLES ───
  stockStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'center',
  },
  stockInStock: {
    backgroundColor: '#D1FAE5',
  },
  stockInStockText: {
    color: '#065F46',
    fontSize: 11,
    fontWeight: '800',
  },
  stockLow: {
    backgroundColor: '#FEF3C7',
  },
  stockLowText: {
    color: '#92400E',
    fontSize: 11,
    fontWeight: '800',
  },
  stockOut: {
    backgroundColor: '#FEE2E2',
  },
  stockOutText: {
    color: '#991B1B',
    fontSize: 11,
    fontWeight: '800',
  },
  stockAdjustBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  stockMiniBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.borderInput,
  },
  stockMiniBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: t.textPrimary,
  },
  inventoryAlertBanner: {
    backgroundColor: t.tableRowHighlight,
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  inventoryAlertText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400E',
    flex: 1,
  },

  // ─── 7. POS (POINT OF SALE) CASHIER TERMINAL ───
  posContainer: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
  },
  posCatalogColumn: {
    flex: 3,
    minWidth: 260,
    width: '100%',
  },
  posRegisterColumn: {
    flex: 2,
    minWidth: 260,
    width: '100%',
  },
  posGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  posProductCard: {
    width: '48%',
    minWidth: 140,
    backgroundColor: t.bgCard,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: t.border,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
    position: 'relative',
  },
  posProductCardDisabled: {
    opacity: 0.5,
    backgroundColor: t.bgSub,
  },
  posProductImg: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    marginBottom: 8,
  },
  posProductBrand: {
    fontSize: 10.5,
    fontWeight: '700',
    color: t.textMuted,
    textTransform: 'uppercase',
  },
  posProductName: {
    fontSize: 13,
    fontWeight: '800',
    color: t.textPrimary,
    marginBottom: 6,
    height: 34,
  },
  posProductPrice: {
    fontSize: 14.5,
    fontWeight: '900',
    color: '#0C6258',
  },
  posAddBtn: {
    backgroundColor: t.accentBg,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: t.accentBorder,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
  },
  posAddBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0C6258',
  },

  // POS Register Cart
  posRegisterCard: {
    backgroundColor: t.bgCard,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: t.border,
    padding: 18,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  posRegisterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: t.borderLight,
    marginBottom: 12,
  },
  posRegisterTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: t.textPrimary,
  },
  posCustomerSelector: {
    backgroundColor: t.bgSub,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: t.border,
    marginBottom: 14,
  },
  posCustomerLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: t.textMuted,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  posCustomerPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  posCartItemsList: {
    maxHeight: 240,
    marginBottom: 14,
  },
  posCartItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: t.borderLight,
    gap: 8,
  },
  posCartItemName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: t.textPrimary,
  },
  posCartItemPrice: {
    fontSize: 12,
    color: t.textMuted,
    marginTop: 2,
  },
  posQtyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  posQtyBtn: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.border,
  },
  posQtyText: {
    fontSize: 13,
    fontWeight: '800',
    color: t.textPrimary,
    minWidth: 18,
    textAlign: 'center',
  },
  posSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  posSummaryLabel: {
    fontSize: 12.5,
    color: t.textMuted,
    fontWeight: '500',
  },
  posSummaryVal: {
    fontSize: 13,
    fontWeight: '700',
    color: t.textPrimary,
  },
  posGrandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    marginTop: 6,
    borderTopWidth: 1.5,
    borderTopColor: t.border,
  },
  posGrandTotalLabel: {
    fontSize: 15,
    fontWeight: '900',
    color: t.textPrimary,
  },
  posGrandTotalVal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0C6258',
  },
  posPayMethodRow: {
    flexDirection: 'row',
    gap: 6,
    marginVertical: 12,
    flexWrap: 'wrap',
  },
  posPayMethodBtn: {
    flex: 1,
    minWidth: 70,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: t.bgSub,
    borderWidth: 1,
    borderColor: t.border,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  posPayMethodBtnActive: {
    backgroundColor: t.accentBg,
    borderColor: '#0C6258',
    borderWidth: 1.5,
  },
  posPayMethodText: {
    fontSize: 11,
    fontWeight: '700',
    color: t.textMuted,
  },
  posPayMethodTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  posTenderBox: {
    backgroundColor: t.bgSub,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: t.border,
    marginBottom: 12,
  },
  posQuickCashRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  posQuickCashChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: t.bgCard,
    borderWidth: 1,
    borderColor: t.borderInput,
  },
  posQuickCashChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: t.textSecondary,
  },
  posChangeBanner: {
    backgroundColor: '#ECFDF5',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  posChangeBannerText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#065F46',
  },
  posChangeBannerAmount: {
    fontSize: 15,
    fontWeight: '900',
    color: '#047857',
  },
  posCheckoutBtn: {
    backgroundColor: '#0C6258',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  posCheckoutBtnDisabled: {
    backgroundColor: '#94A3B8',
    shadowOpacity: 0,
  },
  posCheckoutBtnText: {
    color: '#FFFFFF',
    fontSize: 14.5,
    fontWeight: '900',
  },

  // ─── 8. ANALYTICS & CHARTS ───
  analyticsCard: {
    backgroundColor: t.bgCard,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: t.border,
    padding: 20,
    marginBottom: 20,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  analyticsCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  analyticsCardTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: t.textPrimary,
  },
  analyticsCardSubtitle: {
    fontSize: 12,
    color: t.textMuted,
    marginTop: 2,
  },
  analyticsPeriodTabs: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#F1F5F9',
    padding: 3,
    borderRadius: 10,
  },
  analyticsPeriodTab: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  analyticsPeriodTabActive: {
    backgroundColor: t.bgCard,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  analyticsPeriodTabText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: t.textMuted,
  },
  analyticsPeriodTabTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  chartBarContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 180,
    paddingTop: 20,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: t.border,
    gap: 8,
  },
  chartBarCol: {
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  chartBarPill: {
    width: '100%',
    maxWidth: 36,
    backgroundColor: '#0C6258',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    minHeight: 8,
  },
  chartBarPillAlt: {
    backgroundColor: '#EAB308',
  },
  chartBarLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: t.textMuted,
    marginTop: 6,
  },
  chartBarVal: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0C6258',
    marginBottom: 4,
  },
  leaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: t.borderLight,
    gap: 12,
  },
  leaderboardRank: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: t.accentBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leaderboardRankText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#0C6258',
  },
  progressBarTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F1F5F9',
    overflow: 'hidden',
    marginTop: 6,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0C6258',
    borderRadius: 4,
  },

  // ─── 9. MODALS ───
  modalOverlay: {
    flex: 1,
    backgroundColor: t.modalOverlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    ...(Platform.OS === 'web' ? { backdropFilter: 'blur(4px)' } : {}),
  },
  modalSheet: {
    backgroundColor: t.bgCard,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: t.border,
    width: '100%',
    maxWidth: 640,
    maxHeight: '90%',
    padding: 22,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: t.borderLight,
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 17.5,
    fontWeight: '900',
    color: t.textPrimary,
    letterSpacing: -0.3,
  },
  modalBody: {
    maxHeight: 500,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: t.textSecondary,
    marginBottom: 6,
    marginTop: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  formInput: {
    backgroundColor: t.bgSub,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.borderInput,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13.5,
    color: t.textPrimary,
    marginBottom: 4,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },
  imageUploadBox: {
    backgroundColor: t.bgSub,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    borderStyle: 'dashed',
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    marginTop: 4,
  },
  imageUploadPreviewWrap: {
    width: '100%',
    height: 140,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
    backgroundColor: '#F1F5F9',
    position: 'relative',
  },
  imageUploadPreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  uploadButtonRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 6,
  },
  uploadActionBtn: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  uploadActionBtnSecondary: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: t.borderInput,
  },
  uploadActionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  presetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
    marginBottom: 10,
  },
  presetThumbBtn: {
    width: 48,
    height: 48,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: t.border,
  },
  presetThumbBtnActive: {
    borderColor: '#0C6258',
    borderWidth: 2.5,
  },
  presetThumbImg: {
    width: '100%',
    height: '100%',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: t.borderLight,
  },

  // ─── 10. DIGITAL RECEIPT MODAL (THERMAL TICKET STYLE) ───
  receiptSheet: {
    backgroundColor: t.bgCard,
    borderRadius: 20,
    padding: 24,
    maxWidth: 420,
    width: '100%',
    borderWidth: 1,
    borderColor: t.border,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 20,
  },
  receiptLogo: {
    fontSize: 20,
    fontWeight: '900',
    color: t.textPrimary,
    textAlign: 'center',
  },
  receiptSub: {
    fontSize: 11,
    color: t.textMuted,
    textAlign: 'center',
    marginTop: 2,
  },
  receiptDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#CBD5E1',
    borderStyle: 'dashed',
    marginVertical: 14,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  receiptText: {
    fontSize: 12,
    color: t.textSecondary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  receiptTextBold: {
    fontSize: 12,
    fontWeight: '700',
    color: t.textPrimary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  receiptBarcode: {
    height: 44,
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    marginVertical: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.border,
  },
  receiptBarcodeText: {
    fontSize: 12,
    letterSpacing: 4,
    fontWeight: '900',
    color: t.textSecondary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },

  sqlBox: {
    backgroundColor: t.bgSub,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: t.border,
    maxHeight: 180,
  },
  sqlCodeText: {
    color: '#0C6258',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11.5,
    lineHeight: 18,
  },

  // ─── ORDER MANAGEMENT STYLES ───
  paymentDropdownContainer: {
    position: 'relative',
    zIndex: 99999,
    elevation: 99999,
  },
  dropdownDismissBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 99998,
  },
  paymentDropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: t.bgCard,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
    minWidth: 150,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  paymentDropdownTriggerActive: {
    borderColor: '#0C6258',
    backgroundColor: t.accentBg,
  },
  paymentDropdownTriggerText: {
    fontSize: 13,
    fontWeight: '700',
    color: t.textPrimary,
  },
  paymentDropdownMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 6,
    width: 220,
    backgroundColor: t.bgCard,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: t.border,
    padding: 6,
    shadowColor: t.cardShadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 99999,
    zIndex: 99999,
    maxHeight: 260,
  },
  paymentDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  paymentDropdownItemActive: {
    backgroundColor: t.accentBg,
  },
  paymentDropdownItemText: {
    fontSize: 13,
    color: t.textSecondary,
    fontWeight: '600',
  },
  paymentDropdownItemTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  orderFilterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  orderFilterTab: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: t.bgCard,
    borderWidth: 1,
    borderColor: t.border,
  },
  orderFilterTabActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  orderFilterTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: t.textMuted,
  },
  orderFilterTabTextActive: {
    color: '#FFFFFF',
  },
  codAlertBanner: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  codAlertBannerText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#92400E',
  },
  codAlertBannerSub: {
    fontSize: 11.5,
    color: '#B45309',
    marginTop: 2,
  },
  approveAllCodBtn: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  approveAllCodBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  orderActionBtnGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  btnApproveCod: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  btnApproveCodText: {
    color: '#FFFFFF',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  btnAdvanceOrder: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  btnAdvanceOrderText: {
    color: '#1D4ED8',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  btnViewOrder: {
    backgroundColor: t.bgSub,
    borderWidth: 1,
    borderColor: t.borderInput,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  btnViewOrderText: {
    color: t.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  btnCancelOrder: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  btnCancelOrderText: {
    color: '#DC2626',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },

  // ─── GARAGE SUB-NAVIGATION & BOOKING STYLES ───
  garageSubNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: t.border,
    paddingBottom: 10,
    flexWrap: 'wrap',
  },
  garageSubNavBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: t.bgSub,
    borderWidth: 1,
    borderColor: t.border,
  },
  garageSubNavBtnActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  garageSubNavText: {
    fontSize: 13,
    fontWeight: '700',
    color: t.textSecondary,
  },
  garageSubNavTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  garageBadgeCount: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 18,
    alignItems: 'center',
  },
  garageBadgeCountActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  garageBadgeCountText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: t.textSecondary,
  },
  garageBadgeCountTextActive: {
    color: '#FFFFFF',
  },

  // Booking Status Badges
  bookingStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 9999,
    alignSelf: 'center',
    flexShrink: 0,
  },
  statusConfirmed: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  statusConfirmedText: {
    color: '#1D4ED8',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  statusInProgress: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  statusInProgressText: {
    color: '#B45309',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  statusCompleted: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  statusCompletedText: {
    color: '#059669',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  statusCancelled: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  statusCancelledText: {
    color: '#DC2626',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },

  // Bike & Tech Badges
  bikeInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  bikePlatePill: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: t.borderInput,
  },
  bikePlateText: {
    fontSize: 10,
    fontWeight: '800',
    color: t.textPrimary,
    letterSpacing: 0.5,
  },
  techPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: t.accentBg,
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: t.accentBorder,
  },
  techPillText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#0C6258',
  },

  // ─── MECHANICS & TECHNICIANS ROSTER STYLES ───
  mechanicsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginBottom: 24,
  },
  mechanicCard: {
    backgroundColor: t.bgCard,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: t.border,
    padding: 16,
    flex: 1,
    minWidth: 280,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDark ? 0.25 : 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  mechanicCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  mechanicAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#0C6258',
    backgroundColor: '#E2E8F0',
  },
  mechanicHeaderInfo: {
    flex: 1,
  },
  mechanicName: {
    fontSize: 14.5,
    fontWeight: '800',
    color: t.textPrimary,
    lineHeight: 19,
    marginBottom: 2,
  },
  mechanicShortName: {
    fontSize: 12,
    fontWeight: '600',
    color: t.textSecondary,
  },
  mechanicStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  mechanicStatusAvailable: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  mechanicStatusAvailableText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
  },
  mechanicStatusBusy: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  mechanicStatusBusyText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#B45309',
  },
  mechanicInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  mechanicInfoText: {
    fontSize: 12,
    color: t.textSecondary,
    flex: 1,
  },
  mechanicBayBadge: {
    backgroundColor: isDark ? '#1E293B' : '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: t.borderInput,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
  },
  mechanicBayText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: t.textPrimary,
  },
  mechanicActiveBookingBanner: {
    backgroundColor: isDark ? 'rgba(245, 158, 11, 0.15)' : '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  mechanicActiveBookingText: {
    fontSize: 11.5,
    color: '#92400E',
    fontWeight: '700',
  },
  mechanicCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: t.border,
  },
  avatarPresetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  avatarPresetThumb: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  avatarPresetThumbSelected: {
    borderColor: '#0C6258',
    transform: [{ scale: 1.08 }],
  },
  quickChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  quickChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: isDark ? '#1E293B' : '#F8FAFC',
    borderWidth: 1,
    borderColor: t.borderInput,
  },
  quickChipActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  quickChipText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: t.textSecondary,
  },
  quickChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
});
};

export const adminStyles = createAdminStyles(false);
export const adminDarkStyles = createAdminStyles(true);
export const getAdminStyles = (isDark = false) => (isDark ? adminDarkStyles : adminStyles);
export default adminStyles;
