import { StyleSheet } from 'react-native';

export const customizerStyles = StyleSheet.create({
  // ─── BASE CANVAS & SCROLL CONTAINER ───
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 120, // Generous padding for persistent bottom navigation bar on mobile
  },
  maxContainer: {
    width: '100%',
    maxWidth: 1360,
    alignSelf: 'center',
    paddingHorizontal: 16,
  },

  // ─── 1. MOBILE TOP HEADER (MATCHING APP PALETTE) ───
  headerWrapper: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingVertical: 12,
    zIndex: 100,
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  logoTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  logoAccent: {
    color: '#0C6258',
  },
  aiBadgeHeader: {
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#D1ECE6',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 7,
    marginLeft: 2,
  },
  aiBadgeHeaderText: {
    color: '#0C6258',
    fontSize: 9.5,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  backBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#334155',
  },

  // ─── 2. HERO SHOWCASE SECTION ───
  heroSection: {
    backgroundColor: '#0C6258',
    borderRadius: 20,
    padding: 20,
    marginTop: 14,
    marginBottom: 18,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  heroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  heroPillText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  heroHeading: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 28,
    marginBottom: 6,
    letterSpacing: -0.4,
  },
  heroSub: {
    fontSize: 13,
    color: '#D1ECE6',
    lineHeight: 19,
  },

  // ─── 3. STUDIO LAYOUT (STACKED FOR MOBILE) ───
  studioLayout: {
    flexDirection: 'column',
    gap: 18,
  },
  studioLayoutDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
  },
  canvasColumn: {
    flex: 1.2,
    width: '100%',
  },
  controlsColumn: {
    flex: 1,
    width: '100%',
  },

  // ─── 4. CANVAS CARD & 4K VIEWPORT ───
  canvasCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  canvasImageContainer: {
    width: '100%',
    height: 320,
    backgroundColor: '#0F172A',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  canvasImage: {
    width: '100%',
    height: '100%',
  },
  canvasOverlayHeader: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  bikeTagBadge: {
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bikeTagText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  toggleViewBtn: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    backgroundColor: '#0C6258',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: '#56B9A1',
  },
  toggleViewBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },

  // ─── SCANNING & PROGRESS OVERLAY ───
  scanOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.94)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    zIndex: 20,
  },
  scanSpinnerBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 3,
    borderColor: '#0C6258',
    borderTopColor: '#56B9A1',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  scanTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 6,
    textAlign: 'center',
  },
  scanSub: {
    fontSize: 12.5,
    color: '#74C9B4',
    textAlign: 'center',
    marginBottom: 16,
    fontWeight: '700',
  },
  progressBarBg: {
    width: '85%',
    height: 8,
    backgroundColor: '#1E293B',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0C6258',
    borderRadius: 4,
  },
  progressPercentText: {
    fontSize: 11.5,
    color: '#94A3B8',
    fontWeight: '800',
  },

  // ─── GEMINI DIAGNOSTICS & TELEMETRY ───
  geminiCard: {
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  geminiCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  geminiTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  geminiTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0F172A',
  },
  geminiBadge: {
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#D1ECE6',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  geminiBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0C6258',
  },
  geminiSummary: {
    fontSize: 12,
    color: '#475569',
    lineHeight: 18,
    marginBottom: 8,
  },
  dynoAdviceBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dynoAdviceText: {
    fontSize: 11.5,
    color: '#334155',
    flex: 1,
    lineHeight: 16,
  },

  // ─── LIVE DYNO PERFORMANCE DIAGNOSTICS ───
  diagnosticsCard: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  diagHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  diagTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  diagGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  diagItem: {
    flex: 1,
    minWidth: 130,
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  diagItemLabel: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '700',
    marginBottom: 3,
  },
  diagItemVal: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0C6258',
  },
  diagItemSub: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 2,
  },

  // ─── ACTION BUTTONS (GENERATE / BOOK / CART) ───
  actionButtonsGroup: {
    marginTop: 14,
    gap: 8,
  },
  generateCtaBtn: {
    backgroundColor: '#0C6258',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  generateCtaText: {
    color: '#FFFFFF',
    fontSize: 14.5,
    fontWeight: '900',
  },
  bookServiceBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#0C6258',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  bookServiceBtnText: {
    color: '#0C6258',
    fontSize: 13.5,
    fontWeight: '800',
  },
  addCartBtn: {
    backgroundColor: '#F1F5F9',
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginTop: 6,
  },
  addCartBtnText: {
    color: '#334155',
    fontSize: 12.5,
    fontWeight: '700',
  },

  // ─── 5. WORKBENCH CARDS ───
  workbenchCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionHeading: {
    fontSize: 15.5,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  sectionHeadingSub: {
    fontSize: 11.5,
    color: '#0C6258',
    fontWeight: '700',
  },

  // Base Photo Upload Box
  uploadBox: {
    borderWidth: 2,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    marginBottom: 14,
  },
  uploadBoxActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  uploadIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  uploadTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 3,
    textAlign: 'center',
  },
  uploadSubtitle: {
    fontSize: 11.5,
    color: '#64748B',
    textAlign: 'center',
  },

  // Presets Horizontal Row
  presetBikesScroll: {
    marginBottom: 4,
  },
  presetBikeCard: {
    width: 136,
    marginRight: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  presetBikeCardActive: {
    borderColor: '#0C6258',
    borderWidth: 2,
    backgroundColor: '#F3F7F6',
  },
  presetBikeImg: {
    width: '100%',
    height: 72,
    backgroundColor: '#E2E8F0',
  },
  presetBikeBody: {
    padding: 8,
  },
  presetBikeName: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  presetBikeBrand: {
    fontSize: 10,
    color: '#0C6258',
    fontWeight: '700',
    marginTop: 1,
  },

  // Custom Theme Selector
  themeGrid: {
    gap: 8,
  },
  themeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  themeCardActive: {
    borderColor: '#0C6258',
    borderWidth: 2,
    backgroundColor: '#F3F7F6',
  },
  themeTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
  },
  themeDesc: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
    lineHeight: 15,
  },
  themeBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: '#E2E8F0',
  },
  themeBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F172A',
  },

  // Parts Selector & Search
  partsCategoryScroll: {
    marginBottom: 12,
  },
  partsCategoryChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  partsCategoryChipActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  partsCategoryText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#475569',
  },
  partsCategoryTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  partsSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 10,
    height: 38,
  },
  partsSearchInput: {
    flex: 1,
    color: '#0F172A',
    fontSize: 12,
    marginLeft: 6,
  },
  partsListContainer: {
    gap: 6,
    maxHeight: 280,
  },
  partItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 10,
    marginBottom: 6,
  },
  partItemCardSelected: {
    borderColor: '#0C6258',
    borderWidth: 1.5,
    backgroundColor: '#F3F7F6',
  },
  partThumb: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
  },
  partInfo: {
    flex: 1,
  },
  partName: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  partMeta: {
    fontSize: 10.5,
    color: '#64748B',
    marginTop: 2,
  },
  partPriceRow: {
    alignItems: 'flex-end',
  },
  partPricePhp: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0C6258',
  },
  partPriceUsd: {
    fontSize: 10,
    color: '#94A3B8',
  },
  checkboxCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxCircleSelected: {
    borderColor: '#0C6258',
    backgroundColor: '#0C6258',
  },

  // Selected Parts Tray
  selectedTray: {
    backgroundColor: '#F3F7F6',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#D1ECE6',
    marginTop: 10,
  },
  selectedTrayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  selectedTrayTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#042F2E',
    textTransform: 'uppercase',
  },
  selectedTrayTotal: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0C6258',
  },

  // ─── 6. MODALS ───
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalSheet: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
  },
  modalCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formLabel: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  formInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0F172A',
    marginBottom: 12,
  },
  branchBtn: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 6,
  },
  branchBtnActive: {
    borderColor: '#0C6258',
    borderWidth: 2,
    backgroundColor: '#F3F7F6',
  },
  branchText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  branchSub: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  slotChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginRight: 6,
    marginBottom: 6,
  },
  slotChipActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  slotText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
  },
  slotTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },

  // ─── DUAL-MODE CUSTOMIZATION STYLES ───
  modeSelectorWrapper: {
    marginBottom: 20,
  },
  modeTabsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  modeTab: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  modeTabActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
    shadowColor: '#0C6258',
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  modeTabHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  modeIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeIconWrapActive: {
    backgroundColor: '#0C6258',
  },
  modeTabBadge: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  modeTabBadgeActive: {
    backgroundColor: '#0C6258',
  },
  modeTabBadgeText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#475569',
  },
  modeTabBadgeTextActive: {
    color: '#FFFFFF',
  },
  modeTabTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 3,
  },
  modeTabTitleActive: {
    color: '#0C6258',
  },
  modeTabDesc: {
    fontSize: 11,
    color: '#64748B',
    lineHeight: 15,
  },

  // Inspo Input / Notes
  inspoNotesInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
    fontSize: 12.5,
    color: '#0F172A',
    minHeight: 65,
    textAlignVertical: 'top',
    marginTop: 10,
    marginBottom: 14,
  },

  // Inspo Preview & Results
  inspoPreviewImage: {
    width: '100%',
    height: 230,
    borderRadius: 14,
    backgroundColor: '#0F172A',
  },
  inspoResultCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  inspoStyleBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  inspoStylePill: {
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#56B9A1',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
  },
  inspoStylePillText: {
    color: '#0C6258',
    fontSize: 10.5,
    fontWeight: '800',
  },
  inspoTaglineText: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
    lineHeight: 22,
    marginBottom: 6,
  },
  inspoSummaryText: {
    fontSize: 12.5,
    color: '#475569',
    lineHeight: 18,
    marginBottom: 12,
  },
  inspoModsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 14,
  },
  inspoModChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  inspoModChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
  },

  // Matched Parts Section
  matchedPartsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  matchedPartsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  matchedPartsTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0F172A',
  },
  matchedPartsCountBadge: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  matchedPartsCountText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  matchedPartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 8,
    gap: 10,
  },
  matchedPartItemActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  matchedPartImg: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
  },
  matchedPartName: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  matchedPartBrand: {
    fontSize: 10.5,
    color: '#64748B',
    marginTop: 1,
  },
  matchedPartPrice: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0C6258',
    marginTop: 2,
  },
  customPromptInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 10,
    fontSize: 12,
    color: '#0F172A',
    minHeight: 50,
    textAlignVertical: 'top',
    marginTop: 8,
    marginBottom: 12,
  },

  // ─── REGISTERED MOTORCYCLE SELECTOR STYLES (MOBILE) ───
  bikeSourceTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  bikeSourceTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  bikeSourceTabActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  bikeSourceTabText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
  },
  bikeSourceTabTextActive: {
    color: '#FFFFFF',
  },
  registeredBikesScroll: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  regBikeCard: {
    width: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    padding: 10,
    marginRight: 10,
    position: 'relative',
  },
  regBikeCardActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  regBikeThumb: {
    width: '100%',
    height: 100,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
    marginBottom: 8,
  },
  regBikeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 6,
    marginBottom: 3,
  },
  regBikeTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    flex: 1,
  },
  regBikeNickname: {
    fontSize: 11,
    color: '#64748B',
    marginBottom: 4,
  },
  regBikeMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexWrap: 'wrap',
  },
  regBikePlateBadge: {
    backgroundColor: '#0F172A',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
  },
  regBikePlateText: {
    color: '#F8FAFC',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  regBikeColorBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  regBikeColorText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#475569',
  },
  regBikePrimaryTag: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  regBikePrimaryTagText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#92400E',
  },
  emptyRegBikesBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 12,
  },
  emptyRegBikesText: {
    fontSize: 11.5,
    color: '#64748B',
    textAlign: 'center',
  },
  emptyRegBikesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#0C6258',
    borderRadius: 7,
  },
  emptyRegBikesBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },

  // ─── SYNTHESIZED AI PROMPT SENTENCE STYLES (MOBILE) ───
  formedPromptCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    padding: 12,
    marginTop: 12,
    marginBottom: 12,
  },
  formedPromptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 6,
  },
  formedPromptTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  formedPromptTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  formedPromptBadge: {
    backgroundColor: '#D1ECE6',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
  },
  formedPromptBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#0C6258',
    letterSpacing: 0.3,
  },
  formedPromptActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  promptActionIconBtn: {
    padding: 4,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  formedPromptTextBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 6,
  },
  formedPromptSentence: {
    fontSize: 11.5,
    color: '#1E293B',
    lineHeight: 17,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  promptNoteText: {
    fontSize: 10.5,
    color: '#64748B',
  },

  // ─── MINIMALIST MOBILE STEPPER & WORKFLOW STYLES ───
  workflowStepperCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  stepperTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  stepItemActive: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#D1ECE6',
  },
  stepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBadgeActive: {
    backgroundColor: '#0C6258',
  },
  stepBadgeDone: {
    backgroundColor: '#10B981',
  },
  stepBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
  },
  stepBadgeTextActive: {
    color: '#FFFFFF',
  },
  stepLabelWrap: {
    flexDirection: 'column',
  },
  stepLabel: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#64748B',
  },
  stepLabelActive: {
    color: '#0F172A',
    fontWeight: '800',
  },
  stepSubLabel: {
    fontSize: 9.5,
    color: '#94A3B8',
  },
  stepConnector: {
    flex: 1,
    height: 1.5,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 4,
    minWidth: 8,
  },
  stepConnectorActive: {
    backgroundColor: '#0C6258',
  },

  // ─── PART DETAILS & PRICE MODAL (MOBILE) ───
  partModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'flex-end',
    zIndex: 2000,
  },
  partModalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  partModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  partModalImgBox: {
    width: '100%',
    height: 180,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#0F172A',
    marginBottom: 14,
    position: 'relative',
  },
  partModalImg: {
    width: '100%',
    height: '100%',
  },
  partModalBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(12, 98, 88, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  partModalBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  partModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  partModalBrand: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 10,
  },
  partModalPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    backgroundColor: '#F8FAFC',
    padding: 10,
    borderRadius: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  partModalPricePhp: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0C6258',
  },
  partModalPriceUsd: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
  },
  partModalSpecsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  partModalSpecChip: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  partModalSpecText: {
    fontSize: 10.5,
    color: '#334155',
    fontWeight: '600',
  },
  partModalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 8,
  },
  partModalAddBtn: {
    flex: 2,
    backgroundColor: '#0C6258',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  partModalAddBtnText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    fontWeight: '800',
  },
  partModalCancelBtn: {
    flex: 1,
    backgroundColor: '#F1F5F9',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  partModalCancelBtnText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
  },

  // ─── ADD MORE CUSTOMIZATIONS PROMPT BANNER (MOBILE) ───
  addMorePromptBanner: {
    backgroundColor: '#0F172A',
    borderRadius: 14,
    padding: 14,
    marginTop: 14,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    gap: 10,
  },
  addMorePromptLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addMoreIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMorePromptTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  addMorePromptSub: {
    fontSize: 11,
    color: '#94A3B8',
  },
  addMoreBtnGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  addMoreBtnYes: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  addMoreBtnYesText: {
    color: '#F8FAFC',
    fontSize: 11.5,
    fontWeight: '700',
  },
  addMoreBtnNo: {
    flex: 1.2,
    backgroundColor: '#0C6258',
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  addMoreBtnNoText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },

  // ─── STAGE 3: REVIEW CUSTOMIZATION & AI PREVIEW (MOBILE) ───
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  reviewHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  reviewBikeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reviewBikeThumb: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: '#0F172A',
  },
  reviewBikeTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  reviewBikeSub: {
    fontSize: 11,
    color: '#64748B',
  },
  reviewPartsList: {
    gap: 8,
    marginVertical: 10,
  },
  reviewPartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 10,
  },
  reviewPartLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  reviewPartThumb: {
    width: 38,
    height: 38,
    borderRadius: 6,
    backgroundColor: '#CBD5E1',
  },
  reviewPartName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
  },
  reviewPartMeta: {
    fontSize: 10.5,
    color: '#64748B',
  },
  reviewPartPrice: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  reviewPartRemoveBtn: {
    padding: 5,
    borderRadius: 6,
    backgroundColor: '#FEE2E2',
  },
  reviewActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  reviewActionSecondaryBtn: {
    flex: 1,
    minWidth: 130,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  reviewActionSecondaryText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#334155',
  },
  reviewActionPrimaryBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#0C6258',
    marginTop: 6,
  },
  reviewActionPrimaryText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // ─── STAGE 4: ESTIMATED TOTAL & DUAL ACTIONS (MOBILE) ───
  totalBreakdownCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
  },
  totalRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  totalRowLabel: {
    fontSize: 12.5,
    color: '#64748B',
  },
  totalRowValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  totalGrandBox: {
    backgroundColor: '#F0FDF4',
    padding: 12,
    borderRadius: 12,
    marginTop: 14,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalGrandLabel: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  totalGrandAmount: {
    fontSize: 19,
    fontWeight: '900',
    color: '#0C6258',
    textAlign: 'right',
  },
  dualActionContainer: {
    gap: 12,
  },
  buyPartsCheckoutBtn: {
    backgroundColor: '#0C6258',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  buyPartsCheckoutText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  bookInstallServiceBtn: {
    backgroundColor: '#0F172A',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#334155',
  },
  bookInstallServiceText: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '800',
  },
});

export default customizerStyles;


