export * from './shop.styles';
export * from './admin.styles';
export * from './auth.styles';
export * from './garagePage.styles';
export * from './loginPage.styles';
export * from './orderPage.styles';
export * from './signUpPage.styles';
export * from './wishlistPage.styles';
export * from './customizer.styles';
export * as webStyles from './web';
