import { StyleSheet, Platform } from 'react-native';
import { ANDROID_STATUS_BAR_HEIGHT, ANDROID_BOTTOM_INSET } from '../utils/safeArea';

export const productDetailsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  rootContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },

  // ─── TOP STICKY APP BAR ──────────────────────────────────────────────────
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'android' ? ANDROID_STATUS_BAR_HEIGHT + 6 : 10,
    paddingBottom: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    zIndex: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 3,
  },
  topBarIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  topSearchPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    paddingHorizontal: 12,
    height: 40,
    marginHorizontal: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  topSearchText: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
    marginLeft: 8,
    fontWeight: '600',
  },
  topBarRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: '#EF4444',
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },

  // ─── SCROLLABLE CONTENT ──────────────────────────────────────────────────
  scrollContent: {
    paddingBottom: 130, // Space for sticky bottom action bar
  },

  // ─── HERO GALLERY SHOWCASE ───────────────────────────────────────────────
  heroContainer: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  heroImage: {
    width: '100%',
    height: 320,
    backgroundColor: '#FFFFFF',
  },
  topTagPill: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  topTagText: {
    color: '#1D4533',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  pageIndicatorPill: {
    position: 'absolute',
    bottom: 12,
    right: 14,
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 12,
  },
  pageIndicatorText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  promoRibbon: {
    width: '100%',
    backgroundColor: '#1D4533',
    paddingVertical: 8,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  promoRibbonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  promoBadgeHighlight: {
    backgroundColor: '#F59E0B',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  promoBadgeHighlightText: {
    color: '#0F172A',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  promoRibbonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.1,
  },
  promoRibbonSubtext: {
    color: '#99F6E4',
    fontSize: 11,
    fontWeight: '700',
  },

  // ─── MAIN PRICING BLOCK ──────────────────────────────────────────────────
  priceCard: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    flexWrap: 'wrap',
  },
  currencySymbol: {
    color: '#1D4533',
    fontSize: 22,
    fontWeight: '900',
  },
  priceMainInteger: {
    color: '#1D4533',
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  priceMainDecimal: {
    color: '#1D4533',
    fontSize: 20,
    fontWeight: '900',
  },
  priceOriginalText: {
    color: '#94A3B8',
    fontSize: 14,
    textDecorationLine: 'line-through',
    fontWeight: '600',
    marginLeft: 4,
  },
  discountPercentBadge: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    marginLeft: 4,
  },
  discountPercentText: {
    color: '#059669',
    fontSize: 11,
    fontWeight: '800',
  },

  // PayLater / Payment Perks Row
  perkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  perkRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  perkText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '700',
  },
  perkLinkText: {
    color: '#1D4533',
    fontSize: 12,
    fontWeight: '800',
  },
  voucherTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingVertical: 4,
  },
  voucherTagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFFBEB',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  voucherTagText: {
    color: '#B45309',
    fontSize: 11,
    fontWeight: '800',
  },

  // ─── PRODUCT TITLE & SOCIAL ROW ──────────────────────────────────────────
  titleSection: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    marginTop: 8,
  },
  titleHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  titleTextContainer: {
    flex: 1,
  },
  titleBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 6,
  },
  trendBadge: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 4,
  },
  trendBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  categoryPill: {
    backgroundColor: '#E8F0EC',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#1D4533',
  },
  categoryPillText: {
    color: '#1D4533',
    fontSize: 10.5,
    fontWeight: '800',
  },
  productTitle: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 23,
    letterSpacing: -0.2,
  },
  wishlistBookmarkBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },

  // Rating & Meta Stats
  metaStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    flexWrap: 'wrap',
    gap: 8,
  },
  ratingStarsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingValueText: {
    color: '#D97706',
    fontSize: 13,
    fontWeight: '900',
  },
  unratedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  unratedText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
  },
  metaDot: {
    color: '#CBD5E1',
    fontSize: 12,
  },
  metaText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  stockPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  stockPillInStock: {
    backgroundColor: '#ECFDF5',
  },
  stockPillSoldOut: {
    backgroundColor: '#FEF2F2',
  },
  stockPillText: {
    fontSize: 11,
    fontWeight: '800',
  },

  // ─── SHIPPING & DELIVERY GUARANTEE CARD ───────────────────────────────────
  shippingCard: {
    marginHorizontal: 14,
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  shippingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  shippingIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#E8F0EC',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  shippingInfoColumn: {
    flex: 1,
  },
  guaranteedDeliveryDate: {
    color: '#0F172A',
    fontSize: 13.5,
    fontWeight: '800',
    marginBottom: 2,
  },
  guaranteeLateCouponNote: {
    color: '#64748B',
    fontSize: 11.5,
    lineHeight: 16,
  },
  shippingCostRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  shippingFeeLabel: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  shippingFeeOriginal: {
    color: '#94A3B8',
    fontSize: 12,
    textDecorationLine: 'line-through',
  },
  shippingFeeCurrent: {
    color: '#059669',
    fontSize: 13,
    fontWeight: '900',
  },
  shippingPromoHighlight: {
    color: '#1D4533',
    fontSize: 11.5,
    fontWeight: '700',
    marginTop: 4,
  },

  // Expiring discount countdown ticker
  expiringDiscountTicker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  tickerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  tickerText: {
    color: '#047857',
    fontSize: 11.5,
    fontWeight: '800',
  },
  tickerCountdown: {
    color: '#D97706',
    fontSize: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },

  // ─── VARIANT SELECTOR (COLOR & SIZE) ──────────────────────────────────────
  sectionBox: {
    marginHorizontal: 14,
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  sectionBoxTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionBoxTitle: {
    color: '#0F172A',
    fontSize: 13.5,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  sectionBoxSub: {
    color: '#64748B',
    fontSize: 11.5,
    fontWeight: '600',
  },
  variantChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  variantChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  variantChipSelected: {
    backgroundColor: '#E8F0EC',
    borderColor: '#1D4533',
  },
  variantChipSoldOut: {
    opacity: 0.45,
    backgroundColor: '#F1F5F9',
    borderColor: '#E2E8F0',
  },
  colorSwatchCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.15)',
  },
  variantChipText: {
    color: '#334155',
    fontSize: 12.5,
    fontWeight: '700',
  },
  variantChipTextSelected: {
    color: '#1D4533',
    fontWeight: '900',
  },
  variantChipPrice: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
  },

  // Quantity stepper
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  quantityLabel: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
  },
  quantityStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  stepperBtn: {
    width: 36,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperValueText: {
    minWidth: 32,
    textAlign: 'center',
    color: '#0F172A',
    fontSize: 13.5,
    fontWeight: '800',
  },

  // ─── SPECIFICATIONS & FEATURES ───────────────────────────────────────────
  specRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  specLabel: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  specValue: {
    color: '#0F172A',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 6,
  },
  featureText: {
    color: '#334155',
    fontSize: 12.5,
    lineHeight: 18,
    flex: 1,
  },
  descriptionText: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },

  // ─── REVIEWS ─────────────────────────────────────────────────────────────
  reviewItem: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  reviewAuthor: {
    color: '#0F172A',
    fontSize: 12.5,
    fontWeight: '800',
  },
  reviewDate: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '600',
  },
  reviewComment: {
    color: '#334155',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },

  // ─── STICKY BOTTOM ACTION BAR ────────────────────────────────────────────
  bottomBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'android' ? ANDROID_BOTTOM_INSET + 8 : 14,
    gap: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 16,
  },
  iconActionBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 44,
    paddingVertical: 4,
  },
  iconActionLabel: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  addToCartIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#E8F0EC',
    borderWidth: 1.5,
    borderColor: '#1D4533',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  buyNowBtn: {
    flex: 1,
    height: 48,
    backgroundColor: '#1D4533',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1D4533',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  buyNowBtnTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  buyNowBtnSub: {
    color: '#C8DDD3',
    fontSize: 10.5,
    fontWeight: '800',
  },
  soldOutBtn: {
    backgroundColor: '#E2E8F0',
    borderWidth: 0,
    opacity: 0.7,
  },
  soldOutBtnText: {
    color: '#94A3B8',
    fontSize: 13.5,
    fontWeight: '800',
  },
});
