import { StyleSheet } from 'react-native';

export const variantModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'flex-end',
  },
  backdropTouchable: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '88%',
    minHeight: 440,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 20,
  },
  dragHandleBar: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#CBD5E1',
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 4,
  },

  // ─── SHEET HEADER ───
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 12,
  },
  productThumbnailContainer: {
    width: 88,
    height: 88,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productThumbnail: {
    width: '100%',
    height: '100%',
  },
  headerInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    flexWrap: 'wrap',
  },
  discountBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#FECACA',
    marginRight: 4,
  },
  discountBadgeText: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: '900',
  },
  priceCurrency: {
    fontSize: 14,
    fontWeight: '900',
    color: '#1D4533',
  },
  priceInteger: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1D4533',
    letterSpacing: -0.5,
  },
  priceDecimal: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1D4533',
  },
  priceOriginal: {
    fontSize: 13,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
    fontWeight: '600',
    marginLeft: 6,
  },
  perksRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 5,
    flexWrap: 'wrap',
  },
  freeShippingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#E6F4F1',
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 5,
  },
  freeShippingBadgeText: {
    color: '#1D4533',
    fontSize: 10.5,
    fontWeight: '800',
  },
  bonusBadge: {
    backgroundColor: '#FFFBEB',
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  bonusBadgeText: {
    color: '#B45309',
    fontSize: 10.5,
    fontWeight: '700',
  },
  selectedVariantSummary: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 6,
    fontWeight: '600',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ─── SCROLLABLE CONTENT ───
  scrollBody: {
    flex: 1,
    paddingHorizontal: 16,
  },
  sectionContainer: {
    marginTop: 18,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  sectionSub: {
    fontSize: 12,
    color: '#1D4533',
    fontWeight: '700',
  },
  sizeGuideLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  sizeGuideText: {
    fontSize: 12,
    color: '#1D4533',
    fontWeight: '700',
  },

  // ─── COLOR GRID (TIKTOK STYLE) ───
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  colorCardCol: {
    width: '33.333%',
    padding: 4,
  },
  colorCard: {
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
    height: 128,
  },
  colorCardSelected: {
    borderColor: '#1D4533',
    backgroundColor: '#F0FDFA',
  },
  colorCardSoldOut: {
    borderColor: '#F1F5F9',
    opacity: 0.55,
  },
  colorCardImageContainer: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  colorCardImage: {
    width: '100%',
    height: '100%',
  },
  colorCardExpandBtn: {
    position: 'absolute',
    top: 5,
    left: 5,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  colorCardSelectedBadge: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#1D4533',
    justifyContent: 'center',
    alignItems: 'center',
  },
  colorCardFooter: {
    backgroundColor: '#0F172A',
    paddingVertical: 5,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  colorCardFooterSelected: {
    backgroundColor: '#1D4533',
  },
  colorCardLabel: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  colorCardSub: {
    color: '#CBD5E1',
    fontSize: 9.5,
    fontWeight: '700',
    marginTop: 1,
  },

  // ─── SIZE CHIPS ───
  sizeWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sizeChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    minWidth: 56,
    alignItems: 'center',
  },
  sizeChipSelected: {
    borderColor: '#1D4533',
    backgroundColor: '#1D4533',
  },
  sizeChipSoldOut: {
    borderColor: '#F1F5F9',
    backgroundColor: '#F8FAFC',
    opacity: 0.5,
  },
  sizeChipText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  sizeChipTextSelected: {
    color: '#FFFFFF',
  },
  sizeChipPrice: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#64748B',
    marginTop: 2,
  },
  sizeChipPriceSelected: {
    color: '#99F6E4',
  },

  // ─── QUANTITY ROW ───
  quantityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 8,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  quantityLeft: {
    gap: 2,
  },
  quantityLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  stockAvailableText: {
    fontSize: 11.5,
    color: '#64748B',
    fontWeight: '600',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  stepperBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  stepperBtnDisabled: {
    opacity: 0.35,
  },
  stepperValue: {
    width: 44,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },

  // ─── STICKY BOTTOM ACTION BAR ───
  stickyFooter: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  confirmBtn: {
    height: 50,
    borderRadius: 25,
    backgroundColor: '#1D4533',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    shadowColor: '#1D4533',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  confirmBtnDisabled: {
    backgroundColor: '#94A3B8',
    shadowOpacity: 0,
    elevation: 0,
  },
  confirmBtnTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  confirmBtnSub: {
    color: '#CCFBF1',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 1,
  },
});
