import { StyleSheet, Platform } from 'react-native';

export const shopStyles = StyleSheet.create({
  // ─── BASE CONTAINER ───
  container: {
    flex: 1,
    backgroundColor: '#F6F8FC',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#F6F8FC',
  },
  scrollContent: {
    paddingBottom: 100,
  },
  maxContainer: {
    width: '100%',
    maxWidth: 1320,
    alignSelf: 'center',
    paddingHorizontal: 20,
  },

  // ─── TOAST NOTIFICATION ───
  toastContainer: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 24 : 54,
    alignSelf: 'center',
    backgroundColor: '#0F172A',
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 9999,
    zIndex: 99999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    fontWeight: '700',
  },

  // ─── MOBILE TOP HEADER ───
  headerWrapper: {
    backgroundColor: '#F6F8FC',
    paddingTop: Platform.OS === 'web' ? 14 : 6,
    paddingBottom: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },
  userGreetingWrap: {
    justifyContent: 'center',
  },
  greetingSub: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  greetingNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 1,
  },
  userName: {
    fontSize: 15.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  verifiedBadge: {
    fontSize: 12,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    position: 'relative',
  },
  adminIconBtn: {
    backgroundColor: '#F3F7F6',
    borderColor: '#D1ECE6',
  },
  cartBadgeDot: {
    position: 'absolute',
    top: 3,
    right: 3,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cartBadgeDotText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '900',
  },

  // ─── 3. SEARCH & FILTER BAR (MOBILE) ───
  searchSection: {
    marginTop: 8,
    marginBottom: 14,
  },
  searchBarPill: {
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  searchIcon: {
    fontSize: 16,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#0F172A',
    fontWeight: '500',
    paddingVertical: 0,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },
  filterBtnInside: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },

  // ─── 4. TOP CATEGORY PILLS (HORIZONTAL SCROLL) ───
  categoryPillsWrap: {
    marginBottom: 16,
  },
  categoryPillScroll: {
    paddingVertical: 4,
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  categoryPillActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
    shadowColor: '#0C6258',
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  categoryPillIcon: {
    fontSize: 14,
  },
  categoryPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  categoryPillTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },

  // ─── 5. HERO PROMO BANNER (RESPONSIVE) ───
  heroBannerWrap: {
    marginBottom: 24,
  },
  heroBannerCard: {
    backgroundColor: '#0C6258',
    borderRadius: 24,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 160,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 8,
  },
  heroBannerCardDesktop: {
    minHeight: 200,
    padding: 36,
  },
  heroBannerBgShape: {
    position: 'absolute',
    right: -40,
    top: -40,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  heroBannerLeft: {
    flex: 1.3,
    zIndex: 2,
  },
  heroBannerHeading: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 28,
    letterSpacing: -0.3,
  },
  heroBannerHeadingDesktop: {
    fontSize: 28,
    lineHeight: 34,
  },
  heroBannerSub: {
    fontSize: 13,
    color: '#D1ECE6',
    marginTop: 6,
    marginBottom: 16,
    fontWeight: '500',
  },
  heroShopBtn: {
    backgroundColor: '#FACC15',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 9.5,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
  },
  heroShopBtnText: {
    color: '#0F172A',
    fontWeight: '800',
    fontSize: 13,
  },
  heroBannerRight: {
    flex: 0.9,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  heroProductImg: {
    width: 130,
    height: 130,
    borderRadius: 16,
    resizeMode: 'contain',
  },
  heroProductImgDesktop: {
    width: 180,
    height: 180,
  },
  paginationDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 12,
  },
  dotActive: {
    width: 18,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#0C6258',
  },
  dotInactive: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#CBD5E1',
  },

  // ─── 6. SUB-CATEGORY SQUIRCLE TILES (SCREEN 2) ───
  squircleSection: {
    marginBottom: 20,
  },
  squircleScroll: {
    paddingVertical: 4,
  },
  squircleItem: {
    alignItems: 'center',
    marginRight: 16,
    width: 68,
  },
  squircleBox: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
    marginBottom: 6,
  },
  squircleBoxActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
    shadowColor: '#0C6258',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  squircleIcon: {
    fontSize: 24,
  },
  squircleLabel: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
  },
  squircleLabelActive: {
    color: '#0C6258',
    fontWeight: '800',
  },

  // ─── 7. FILTER CHIPS ROW ───
  filterChipsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 18,
    flexWrap: 'wrap',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterChipActive: {
    backgroundColor: '#F3F7F6',
    borderColor: '#A7F3D0',
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  filterChipTextActive: {
    color: '#0C6258',
    fontWeight: '700',
  },

  // ─── 8. SECTION HEADER ───
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  sectionCount: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
  },

  // ─── 9. RESPONSIVE MULTI-COLUMN PRODUCT GRID ───
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 14,
  },
  productCard: {
    width: '47.5%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 12,
    marginBottom: 6,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    position: 'relative',
  },
  productCardTablet: {
    width: '31.2%',
    marginBottom: 10,
  },
  productCardDesktop: {
    width: '23.3%',
    marginBottom: 14,
    padding: 14,
  },
  productImageContainer: {
    width: '100%',
    height: 155,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#F8FAFC',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  wishlistToggleBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 5,
  },
  wishlistIconHeart: {
    fontSize: 14,
  },
  priceBadgePill: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: '#0C6258',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 5,
  },
  priceBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  productCardDetails: {
    marginTop: 12,
    paddingHorizontal: 2,
  },
  stockCountText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 3,
  },
  stockLowText: {
    color: '#DC2626',
    fontWeight: '700',
  },
  ratingReviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 5,
  },
  ratingStarText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#F59E0B',
  },
  ratingCountText: {
    fontSize: 11.5,
    color: '#94A3B8',
    fontWeight: '500',
  },
  productTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0F172A',
    lineHeight: 18,
    minHeight: 36,
  },

  // ─── 10. FLOATING BOTTOM CART BAR (MOBILE) ───
  floatingCartBarWrapper: {
    position: 'absolute',
    bottom: 74,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 900,
  },
  floatingCartBar: {
    backgroundColor: '#0C6258',
    borderRadius: 28,
    height: 52,
    width: '92%',
    maxWidth: 520,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  floatingCartLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  floatingCartText: {
    color: '#FFFFFF',
    fontSize: 14.5,
    fontWeight: '800',
  },
  floatingCartQtyPill: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  floatingCartQtyText: {
    color: '#0C6258',
    fontSize: 11.5,
    fontWeight: '900',
  },
  floatingCartTotalText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: -0.2,
  },

  // ─── 11. BOTTOM NAVIGATION BAR (MOBILE ONLY) ───
  bottomNavWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 10,
    zIndex: 1000,
  },
  bottomNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 64,
    height: '100%',
  },
  bottomNavActiveDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#0C6258',
    marginBottom: 3,
  },
  bottomNavActiveDotHidden: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: 'transparent',
    marginBottom: 3,
  },
  bottomNavIcon: {
    fontSize: 19,
  },
  bottomNavLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 2,
  },
  bottomNavLabelActive: {
    color: '#0C6258',
    fontWeight: '800',
  },

  // ─── 12. DESKTOP FOOTER ───
  desktopFooter: {
    marginTop: 60,
    paddingTop: 32,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
  },
  footerText: {
    color: '#64748B',
    fontSize: 13,
  },
  footerBadge: {
    backgroundColor: '#F3F7F6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1ECE6',
  },
  footerBadgeText: {
    color: '#0C6258',
    fontSize: 12,
    fontWeight: '700',
  },

  // ─── 13. MODALS ───
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'flex-end',
    ...(Platform.OS === 'web' ? { backdropFilter: 'blur(4px)' } : {}),
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '90%',
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 20,
    width: '100%',
    maxWidth: 640,
    alignSelf: 'center',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseBtnText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '800',
  },

  // ─── CART DRAWER & ITEMS ───
  cartItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  cartItemThumb: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 2,
  },
  cartItemBrand: {
    fontSize: 11.5,
    color: '#64748B',
    marginBottom: 4,
  },
  cartItemPrice: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  cartQtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  cartQtyBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartQtyBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  cartQtyNumber: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    minWidth: 16,
    textAlign: 'center',
  },
  cartFooter: {
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  cartSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cartSummaryLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },
  cartSummaryValue: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  cartTotalLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  cartTotalValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0C6258',
  },
  checkoutBtn: {
    backgroundColor: '#0C6258',
    borderRadius: 18,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 14,
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  checkoutBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },

  // ─── PRODUCT DETAIL / SPECS MODAL ───
  specImageBanner: {
    width: '100%',
    height: 220,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    marginBottom: 16,
  },
  specTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 4,
  },
  specBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  specBrandBadge: {
    backgroundColor: '#F3F7F6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  specBrandText: {
    color: '#0C6258',
    fontSize: 12,
    fontWeight: '700',
  },
  specPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginBottom: 14,
  },
  specPriceMain: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0C6258',
  },
  specPriceOld: {
    fontSize: 15,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  specDescription: {
    fontSize: 13.5,
    lineHeight: 20,
    color: '#475569',
    marginBottom: 16,
  },
  featureBullet: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  featureBulletText: {
    fontSize: 12.5,
    color: '#334155',
    fontWeight: '500',
  },

  // ─── FORM INPUTS ───
  formGroup: {
    marginBottom: 12,
  },
  formLabel: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 5,
  },
  formInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13.5,
    color: '#0F172A',
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
  },

  // ─── PAYMENT METHOD SELECTOR CARDS ───
  paymentOptionCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    padding: 14,
    marginBottom: 10,
  },
  paymentOptionCardActive: {
    backgroundColor: '#F3F7F6',
    borderColor: '#0C6258',
  },
  paymentOptionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentRadioDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  paymentRadioDotActive: {
    borderColor: '#0C6258',
    backgroundColor: '#0C6258',
  },
  paymentRadioInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  paymentOptionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  paymentOptionSub: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  paymentDetailsDrawer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#D1ECE6',
  },

  // ─── ORDER CONFIRMATION MODAL ───
  orderSuccessCard: {
    backgroundColor: '#F3F7F6',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#D1ECE6',
    marginBottom: 14,
  },
  trackOnMapBtn: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    paddingVertical: 13,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 10,
  },
  trackOnMapBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});
