import { StyleSheet, Platform } from 'react-native';

export const customizerWebStyles = StyleSheet.create({
  // ─── BASE CANVAS & SCROLL CONTAINER ───
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    minHeight: Platform.OS === 'web' ? '100vh' : '100%',
  },
  scrollContent: {
    paddingVertical: 24,
    paddingHorizontal: 24,
    paddingBottom: 80,
  },
  maxContainer: {
    width: '100%',
    maxWidth: 1360,
    alignSelf: 'center',
    marginHorizontal: 'auto',
  },

  // ─── 1. FULL-WIDTH DESKTOP STICKY NAVBAR (MATCHING APP PALETTE) ───
  headerWrapper: {
    backgroundColor: 'rgba(10, 15, 28, 0.85)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    paddingVertical: 12,
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.15)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
    paddingHorizontal: 20,
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
  },
  logoIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  logoText: {
    fontSize: 21,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  logoAccent: {
    color: '#0C6258',
  },
  logoSubText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1.2,
  },
  headerCenterNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  headerCenterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    cursor: 'pointer',
  },
  headerCenterBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  navActionIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    transition: 'all 0.3s ease',
  },
  navBadgeCircle: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderWidth: 2,
    borderColor: '#0A0F1C',
    zIndex: 10,
    boxShadow: '0 2px 6px rgba(239, 68, 68, 0.5)',
  },
  navBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  loggedInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  authButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signInHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#1E293B',
  },
  signInHeaderBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // ─── 2. HERO SHOWCASE SECTION (MATCHING APP BRAND HERO) ───
  heroSection: {
    backgroundColor: '#0C6258',
    borderRadius: 24,
    padding: 30,
    marginBottom: 24,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  heroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  heroPillText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  heroHeading: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 36,
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  heroSub: {
    fontSize: 14,
    color: '#D1ECE6',
    lineHeight: 22,
    maxWidth: 820,
  },

  // ─── 3. RESPONSIVE DUAL-COLUMN WORKBENCH ───
  studioLayout: {
    flexDirection: 'column',
    gap: 24,
  },
  studioLayoutDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 28,
  },
  canvasColumn: {
    flex: 1.25,
    minWidth: 340,
  },
  controlsColumn: {
    flex: 1,
    minWidth: 340,
  },

  // ─── 4. CANVAS CARD & 4K VIEWPORT ───
  canvasCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  canvasImageContainer: {
    width: '100%',
    height: 420,
    backgroundColor: '#0F172A',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  canvasImage: {
    width: '100%',
    height: '100%',
  },
  canvasOverlayHeader: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  bikeTagBadge: {
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backdropFilter: 'blur(8px)',
  },
  bikeTagText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  toggleViewBtn: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#56B9A1',
    cursor: 'pointer',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  toggleViewBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },

  // ─── SCANNING & PROGRESS OVERLAY ───
  scanOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.94)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    zIndex: 20,
  },
  scanSpinnerBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3.5,
    borderColor: '#0C6258',
    borderTopColor: '#56B9A1',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  scanTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  scanSub: {
    fontSize: 14,
    color: '#74C9B4',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '700',
  },
  progressBarBg: {
    width: '80%',
    maxWidth: 380,
    height: 9,
    backgroundColor: '#1E293B',
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0C6258',
    borderRadius: 5,
  },
  progressPercentText: {
    fontSize: 12.5,
    color: '#94A3B8',
    fontWeight: '800',
  },

  // ─── GEMINI DIAGNOSTICS & TELEMETRY ───
  geminiCard: {
    backgroundColor: '#F8FAFC',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  geminiCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  geminiTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  geminiTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
  },
  geminiBadge: {
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#D1ECE6',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  geminiBadgeText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  geminiSummary: {
    fontSize: 12.5,
    color: '#475569',
    lineHeight: 19,
    marginBottom: 10,
  },
  dynoAdviceBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dynoAdviceText: {
    fontSize: 12,
    color: '#334155',
    flex: 1,
    lineHeight: 18,
  },

  // ─── LIVE DYNO PERFORMANCE DIAGNOSTICS (LIGHT THEMED WITH EMERALD ACCENTS) ───
  diagnosticsCard: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  diagHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  diagTitle: {
    fontSize: 13.5,
    fontWeight: '900',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  diagGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  diagItem: {
    flex: 1,
    minWidth: 140,
    backgroundColor: '#F8FAFC',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  diagItemLabel: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '700',
    marginBottom: 4,
  },
  diagItemVal: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0C6258',
  },
  diagItemSub: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 3,
  },

  // ─── ACTION BUTTONS (GENERATE / BOOK / CART) ───
  actionButtonsGroup: {
    marginTop: 18,
    gap: 10,
  },
  generateCtaBtn: {
    backgroundColor: '#0C6258',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    cursor: 'pointer',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 5,
  },
  generateCtaText: {
    color: '#FFFFFF',
    fontSize: 15.5,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  bookServiceBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#0C6258',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    cursor: 'pointer',
  },
  bookServiceBtnText: {
    color: '#0C6258',
    fontSize: 14,
    fontWeight: '800',
  },
  addCartBtn: {
    backgroundColor: '#F1F5F9',
    paddingVertical: 13,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  addCartBtnText: {
    color: '#334155',
    fontSize: 13.5,
    fontWeight: '700',
  },

  // ─── 5. WORKBENCH CARDS (RIGHT PANE - LIGHT & CRISP) ───
  workbenchCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionHeading: {
    fontSize: 16.5,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  sectionHeadingSub: {
    fontSize: 12,
    color: '#0C6258',
    fontWeight: '700',
    cursor: 'pointer',
  },

  // Base Photo Upload Box
  uploadBox: {
    borderWidth: 2,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    borderRadius: 18,
    padding: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    marginBottom: 16,
    cursor: 'pointer',
  },
  uploadBoxActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  uploadIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  uploadTitle: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
    textAlign: 'center',
  },
  uploadSubtitle: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
  },

  // Presets Horizontal Row
  presetBikesScroll: {
    marginBottom: 6,
  },
  presetBikeCard: {
    width: 146,
    marginRight: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    cursor: 'pointer',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  presetBikeCardActive: {
    borderColor: '#0C6258',
    borderWidth: 2,
    backgroundColor: '#F3F7F6',
  },
  presetBikeImg: {
    width: '100%',
    height: 80,
    backgroundColor: '#E2E8F0',
  },
  presetBikeBody: {
    padding: 9,
  },
  presetBikeName: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
  },
  presetBikeBrand: {
    fontSize: 10.5,
    color: '#0C6258',
    fontWeight: '700',
    marginTop: 1,
  },

  // Custom Theme Selector
  themeGrid: {
    gap: 10,
  },
  themeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  themeCardActive: {
    borderColor: '#0C6258',
    borderWidth: 2,
    backgroundColor: '#F3F7F6',
  },
  themeTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  themeDesc: {
    fontSize: 11.5,
    color: '#64748B',
    marginTop: 3,
    lineHeight: 16,
  },
  themeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
  },
  themeBadgeText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0F172A',
  },

  // Parts Selector & Search
  partsCategoryScroll: {
    marginBottom: 14,
  },
  partsCategoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 11,
    backgroundColor: '#F1F5F9',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  partsCategoryChipActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  partsCategoryText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  partsCategoryTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  partsSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 12,
    height: 42,
  },
  partsSearchInput: {
    flex: 1,
    color: '#0F172A',
    fontSize: 12.5,
    marginLeft: 8,
    outlineStyle: 'none',
  },
  partsListContainer: {
    gap: 8,
    maxHeight: 320,
  },
  partItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
    cursor: 'pointer',
    marginBottom: 8,
  },
  partItemCardSelected: {
    borderColor: '#0C6258',
    borderWidth: 1.5,
    backgroundColor: '#F3F7F6',
  },
  partThumb: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
  },
  partInfo: {
    flex: 1,
  },
  partName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
  },
  partMeta: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  partPriceRow: {
    alignItems: 'flex-end',
  },
  partPricePhp: {
    fontSize: 13.5,
    fontWeight: '900',
    color: '#0C6258',
  },
  partPriceUsd: {
    fontSize: 10.5,
    color: '#94A3B8',
  },
  checkboxCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxCircleSelected: {
    borderColor: '#0C6258',
    backgroundColor: '#0C6258',
  },

  // Selected Parts Tray
  selectedTray: {
    backgroundColor: '#F3F7F6',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#D1ECE6',
    marginTop: 12,
  },
  selectedTrayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  selectedTrayTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#18181B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  selectedTrayTotal: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0C6258',
  },

  // ─── 6. MODALS (WHITE & EMERALD) ───
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    zIndex: 9999,
  },
  modalSheet: {
    width: '100%',
    maxWidth: 560,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 28,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: '900',
    color: '#0F172A',
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  formInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13.5,
    color: '#0F172A',
    marginBottom: 14,
    outlineStyle: 'none',
  },
  branchBtn: {
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 8,
    cursor: 'pointer',
  },
  branchBtnActive: {
    borderColor: '#0C6258',
    borderWidth: 2,
    backgroundColor: '#F3F7F6',
  },
  branchText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
  },
  branchSub: {
    fontSize: 11.5,
    color: '#64748B',
    marginTop: 2,
  },
  slotChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginRight: 8,
    marginBottom: 8,
    cursor: 'pointer',
  },
  slotChipActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  slotText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  slotTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },

  // ─── DUAL-MODE CUSTOMIZATION STYLES (WEB) ───
  modeSelectorWrapper: {
    marginBottom: 24,
  },
  modeTabsRow: {
    flexDirection: 'row',
    gap: 16,
  },
  modeTab: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  modeTabActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
    shadowColor: '#0C6258',
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  modeTabHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modeIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeIconWrapActive: {
    backgroundColor: '#0C6258',
  },
  modeTabBadge: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  modeTabBadgeActive: {
    backgroundColor: '#0C6258',
  },
  modeTabBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#475569',
  },
  modeTabBadgeTextActive: {
    color: '#FFFFFF',
  },
  modeTabTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  modeTabTitleActive: {
    color: '#0C6258',
  },
  modeTabDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 16,
  },

  // Inspo Input / Notes
  inspoNotesInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    padding: 14,
    fontSize: 13,
    color: '#0F172A',
    minHeight: 70,
    marginTop: 12,
    marginBottom: 16,
    outlineStyle: 'none',
  },

  // Inspo Preview & Results
  inspoPreviewImage: {
    width: '100%',
    height: 340,
    borderRadius: 16,
    backgroundColor: '#0F172A',
  },
  inspoResultCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  inspoStyleBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  inspoStylePill: {
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#56B9A1',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  inspoStylePillText: {
    color: '#0C6258',
    fontSize: 11,
    fontWeight: '800',
  },
  inspoTaglineText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    lineHeight: 26,
    marginBottom: 8,
  },
  inspoSummaryText: {
    fontSize: 13.5,
    color: '#475569',
    lineHeight: 20,
    marginBottom: 16,
  },
  inspoModsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  inspoModChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  inspoModChipText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#334155',
  },

  // Matched Parts Section
  matchedPartsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
  },
  matchedPartsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  matchedPartsTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  matchedPartsCountBadge: {
    backgroundColor: '#0C6258',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  matchedPartsCountText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  matchedPartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
    gap: 12,
    cursor: 'pointer',
  },
  matchedPartItemActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  matchedPartImg: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
  },
  matchedPartName: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  matchedPartBrand: {
    fontSize: 11.5,
    color: '#64748B',
    marginTop: 2,
  },
  matchedPartPrice: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0C6258',
    marginTop: 2,
  },
  customPromptInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    color: '#0F172A',
    minHeight: 56,
    marginTop: 8,
    marginBottom: 14,
    outlineStyle: 'none',
  },

  // ─── REGISTERED MOTORCYCLE SELECTOR STYLES ───
  bikeSourceTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  bikeSourceTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  bikeSourceTabActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  bikeSourceTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  bikeSourceTabTextActive: {
    color: '#FFFFFF',
  },
  registeredBikesScroll: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  regBikeCard: {
    width: 260,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    padding: 12,
    marginRight: 12,
    cursor: 'pointer',
    position: 'relative',
  },
  regBikeCardActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
    boxShadow: '0 4px 14px rgba(12, 98, 88, 0.12)',
  },
  regBikeThumb: {
    width: '100%',
    height: 120,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
    marginBottom: 10,
  },
  regBikeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  regBikeTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    flex: 1,
  },
  regBikeNickname: {
    fontSize: 11.5,
    color: '#64748B',
    marginBottom: 6,
  },
  regBikeMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  regBikePlateBadge: {
    backgroundColor: '#0F172A',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
  },
  regBikePlateText: {
    color: '#F8FAFC',
    fontSize: 10.5,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  regBikeColorBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  regBikeColorText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#475569',
  },
  regBikePrimaryTag: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
  },
  regBikePrimaryTagText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#92400E',
  },
  emptyRegBikesBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 14,
  },
  emptyRegBikesText: {
    fontSize: 12.5,
    color: '#64748B',
    textAlign: 'center',
  },
  emptyRegBikesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: '#0C6258',
    borderRadius: 8,
  },
  emptyRegBikesBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },

  // ─── SYNTHESIZED AI PROMPT SENTENCE STYLES ───
  formedPromptCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    padding: 16,
    marginTop: 14,
    marginBottom: 14,
    boxShadow: '0 4px 16px rgba(12, 98, 88, 0.08)',
  },
  formedPromptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 8,
  },
  formedPromptTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  formedPromptTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  formedPromptBadge: {
    backgroundColor: '#D1ECE6',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  formedPromptBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0C6258',
    letterSpacing: 0.3,
  },
  formedPromptActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  promptActionIconBtn: {
    padding: 5,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  formedPromptTextBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 8,
  },
  formedPromptSentence: {
    fontSize: 12.5,
    color: '#1E293B',
    lineHeight: 19,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  promptNoteText: {
    fontSize: 11,
    color: '#64748B',
  },

  // ─── MINIMALIST STEPPER & WORKFLOW STYLES ───
  workflowStepperCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
    boxShadow: '0 2px 10px rgba(0,0,0,0.04)',
  },
  stepperTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    cursor: 'pointer',
  },
  stepItemActive: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#D1ECE6',
  },
  stepBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBadgeActive: {
    backgroundColor: '#0C6258',
  },
  stepBadgeDone: {
    backgroundColor: '#10B981',
  },
  stepBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#64748B',
  },
  stepBadgeTextActive: {
    color: '#FFFFFF',
  },
  stepLabelWrap: {
    flexDirection: 'column',
  },
  stepLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
  },
  stepLabelActive: {
    color: '#0F172A',
    fontWeight: '800',
  },
  stepSubLabel: {
    fontSize: 10.5,
    color: '#94A3B8',
  },
  stepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 8,
    minWidth: 16,
  },
  stepConnectorActive: {
    backgroundColor: '#0C6258',
  },

  // ─── PART DETAILS & PRICE MODAL ───
  partModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    backdropFilter: 'blur(6px)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    zIndex: 2000,
  },
  partModalSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '100%',
    maxWidth: 520,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    boxShadow: '0 20px 50px rgba(0,0,0,0.2)',
  },
  partModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  partModalImgBox: {
    width: '100%',
    height: 220,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#0F172A',
    marginBottom: 16,
    position: 'relative',
  },
  partModalImg: {
    width: '100%',
    height: '100%',
  },
  partModalBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(12, 98, 88, 0.9)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  partModalBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  partModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  partModalBrand: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 12,
  },
  partModalPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  partModalPricePhp: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0C6258',
  },
  partModalPriceUsd: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  partModalSpecsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  partModalSpecChip: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  partModalSpecText: {
    fontSize: 11.5,
    color: '#334155',
    fontWeight: '600',
  },
  partModalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  partModalAddBtn: {
    flex: 2,
    backgroundColor: '#0C6258',
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    cursor: 'pointer',
  },
  partModalAddBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  partModalCancelBtn: {
    flex: 1,
    backgroundColor: '#F1F5F9',
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    cursor: 'pointer',
  },
  partModalCancelBtnText: {
    color: '#475569',
    fontSize: 13.5,
    fontWeight: '700',
  },

  // ─── ADD MORE CUSTOMIZATIONS PROMPT BANNER ───
  addMorePromptBanner: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
    boxShadow: '0 8px 24px rgba(12, 98, 88, 0.2)',
  },
  addMorePromptLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 260,
  },
  addMoreIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMorePromptTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  addMorePromptSub: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  addMoreBtnGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addMoreBtnYes: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
  },
  addMoreBtnYesText: {
    color: '#F8FAFC',
    fontSize: 12.5,
    fontWeight: '700',
  },
  addMoreBtnNo: {
    backgroundColor: '#0C6258',
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
  },
  addMoreBtnNoText: {
    color: '#FFFFFF',
    fontSize: 12.5,
    fontWeight: '800',
  },

  // ─── STAGE 3: REVIEW CUSTOMIZATION & AI PREVIEW ───
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
  },
  reviewHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  reviewBikeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  reviewBikeThumb: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#0F172A',
  },
  reviewBikeTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  reviewBikeSub: {
    fontSize: 12,
    color: '#64748B',
  },
  reviewPartsList: {
    gap: 10,
    marginVertical: 12,
  },
  reviewPartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
  },
  reviewPartLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  reviewPartThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#CBD5E1',
  },
  reviewPartName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  reviewPartMeta: {
    fontSize: 11,
    color: '#64748B',
  },
  reviewPartPrice: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  reviewPartRemoveBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#FEE2E2',
    cursor: 'pointer',
  },
  reviewActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  reviewActionSecondaryBtn: {
    flex: 1,
    minWidth: 160,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    cursor: 'pointer',
  },
  reviewActionSecondaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
  },
  reviewActionPrimaryBtn: {
    flex: 1.5,
    minWidth: 200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: '#0C6258',
    cursor: 'pointer',
  },
  reviewActionPrimaryText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // ─── STAGE 4: ESTIMATED TOTAL & DUAL ACTIONS ───
  totalBreakdownCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 24,
    boxShadow: '0 4px 20px rgba(0,0,0,0.05)',
  },
  totalRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  totalRowLabel: {
    fontSize: 13.5,
    color: '#64748B',
  },
  totalRowValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  totalGrandBox: {
    backgroundColor: '#F0FDF4',
    padding: 16,
    borderRadius: 14,
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalGrandLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0C6258',
  },
  totalGrandAmount: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0C6258',
    textAlign: 'right',
  },
  dualActionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
  },
  buyPartsCheckoutBtn: {
    flex: 1,
    minWidth: 240,
    backgroundColor: '#0C6258',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    boxShadow: '0 6px 20px rgba(12, 98, 88, 0.3)',
    cursor: 'pointer',
  },
  buyPartsCheckoutText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  bookInstallServiceBtn: {
    flex: 1,
    minWidth: 240,
    backgroundColor: '#0F172A',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderColor: '#334155',
    cursor: 'pointer',
  },
  bookInstallServiceText: {
    color: '#F8FAFC',
    fontSize: 15,
    fontWeight: '800',
  },
});

export const customizerStyles = customizerWebStyles;
export default customizerWebStyles;


