import { StyleSheet } from 'react-native';

export const garageWebStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  headerWrapper: {
    backgroundColor: '#1D4533',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.15)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.10)',
  },
  headerInner: {
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
    paddingHorizontal: 24,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#1D4533',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  logoSubText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1.2,
  },
  headerCenterNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  headerCenterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    cursor: 'pointer',
  },
  headerCenterBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  navActionIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    transition: 'all 0.3s ease',
  },
  navBadgeCircle: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderWidth: 2,
    borderColor: '#0A0F1C',
    zIndex: 10,
    boxShadow: '0 2px 6px rgba(239, 68, 68, 0.5)',
  },
  navBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  loggedInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  authButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signInHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  signInHeaderBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scrollContent: {
    paddingVertical: 24,
    paddingHorizontal: 24,
  },
  maxContainer: {
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
  },
  // ─── 4 KPI STATS GRID (MATCHING PROFILE / ADMIN STAT CARDS) ───
  garageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    flexWrap: 'wrap',
    gap: 14,
  },
  garageHeaderLeft: {
    flex: 1,
    minWidth: 260,
  },
  garageHeaderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  garageHeaderTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  garageHeaderSub: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  garageHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 32,
  },
  statCard: {
    flex: 1,
    minWidth: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.04)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
    elevation: 3,
    position: 'relative',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  statCardTealAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#1D4533',
  },
  statCardWarningAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  statCardDangerAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#EF4444',
  },
  statCardSuccessAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#10B981',
  },
  statCardBlueAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
  },
  statCardPurpleAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#8B5CF6',
  },
  statIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 36,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
    letterSpacing: -1,
  },
  statSub: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500',
  },
  heroCard: {
    backgroundColor: '#0F172A',
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: 'row',
    marginBottom: 28,
    borderWidth: 1,
    borderColor: '#1E293B',
  },
  heroLeft: {
    flex: 1.3,
    padding: 36,
    justifyContent: 'center',
  },
  heroTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(37, 99, 235, 0.2)',
    borderWidth: 1,
    borderColor: '#1D4533',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  heroTagText: {
    color: '#A7F3D0',
    fontSize: 12,
    fontWeight: '800',
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 34,
    marginBottom: 12,
  },
  heroSub: {
    fontSize: 13.5,
    color: '#94A3B8',
    lineHeight: 20,
  },
  heroRight: {
    flex: 1,
    minHeight: 220,
  },
  heroImg: {
    width: '100%',
    height: '100%',
  },
  tabBarRow: {
    marginBottom: 20,
  },
  tabButtons: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  tabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
  },
  tabBtnActive: {
    backgroundColor: '#1D4533',
    borderColor: '#1D4533',
  },
  tabBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  tabBtnTextActive: {
    color: '#FFFFFF',
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  serviceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  serviceImgWrap: {
    width: '100%',
    height: 180,
    backgroundColor: '#F1F5F9',
    position: 'relative',
  },
  serviceImg: {
    width: '100%',
    height: '100%',
  },
  serviceCatBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  serviceCatBadgeText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  servicePriceTag: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#1D4533',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  servicePriceText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  serviceBody: {
    padding: 16,
  },
  serviceTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  serviceDesc: {
    fontSize: 12.5,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 12,
  },
  inclusionsList: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    gap: 6,
    marginBottom: 14,
  },
  incItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  incItemText: {
    fontSize: 12,
    color: '#334155',
    fontWeight: '600',
  },
  bookServiceBtn: {
    backgroundColor: '#1D4533',
    borderRadius: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  bookServiceBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  bookingsContainer: {
    paddingVertical: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 16,
  },
  emptyBox: {
    padding: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 12,
  },
  emptySub: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 4,
  },
  bookingsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  bookingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 20,
    width: '48%',
  },
  bookingCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  bookingId: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#1D4533',
  },
  bookingServiceTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 2,
  },
  statusPillConfirmed: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusPillText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#15803D',
  },
  bookingDetailsGrid: {
    gap: 8,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 14,
  },
  bookingDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bookingDetailVal: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  cancelBookingBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
  },
  cancelBookingBtnText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#DC2626',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalBox: {
    width: '100%',
    maxWidth: 560,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.4)',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 16,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  modalSub: {
    fontSize: 12.5,
    color: '#1D4533',
    fontWeight: '700',
    marginTop: 2,
  },
  modalForm: {
    paddingVertical: 4,
  },
  fieldLabel: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#334155',
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#94A3B8',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: '600',
    color: '#0F172A',
    outlineStyle: 'none',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.04)',
  },
  branchPickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  branchPickBtnActive: {
    borderColor: '#1D4533',
    backgroundColor: '#F3F7F6',
  },
  branchPickText: {
    fontSize: 12.5,
    color: '#475569',
    fontWeight: '600',
  },
  branchPickTextActive: {
    color: '#1D4533',
    fontWeight: '800',
  },
  timeSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  timeSlotPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  timeSlotPillActive: {
    borderColor: '#1D4533',
    backgroundColor: '#1D4533',
  },
  timeSlotText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  timeSlotTextActive: {
    color: '#FFFFFF',
  },
  modalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  modalCancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  modalCancelText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  modalSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#1D4533',
  },
  modalSubmitText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  statusPillRepair: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  statusPillPMS: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  // ─── WEB SERVICE TYPE SEGMENT SWITCHER ───
  serviceTypeSegmentWrap: {
    marginBottom: 16,
  },
  serviceTypeSegment: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 14,
    padding: 4,
    gap: 6,
  },
  serviceTypeTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    cursor: 'pointer',
  },
  serviceTypeTabActiveRepair: {
    backgroundColor: '#DC2626',
    boxShadow: '0 2px 8px rgba(220, 38, 38, 0.25)',
  },
  serviceTypeTabActivePMS: {
    backgroundColor: '#1D4533',
    boxShadow: '0 2px 8px rgba(29, 69, 51, 0.25)',
  },
  serviceTypeTabActiveCust: {
    backgroundColor: '#7C3AED',
    boxShadow: '0 2px 8px rgba(124, 58, 237, 0.25)',
  },
  serviceTypeTabText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#475569',
  },
  serviceTypeTabTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  // ─── REPAIR COMMON FAULT CHIPS ───
  repairFaultChipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  repairFaultChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  repairFaultChipActive: {
    backgroundColor: '#FEF2F2',
    borderColor: '#DC2626',
  },
  repairFaultChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  repairFaultChipTextActive: {
    color: '#DC2626',
    fontWeight: '800',
  },
  // ─── HERO QUICK ACTIONS ───
  heroActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
  },
  heroBookRepairBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#DC2626',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    cursor: 'pointer',
  },
  heroBookPMSBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#1D4533',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    cursor: 'pointer',
  },
  heroBookBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  heroBookTomorrowBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#1D4533',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(29, 69, 51, 0.35)',
  },
  heroBookTomorrowBtnText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    fontWeight: '800',
  },
  heroRosterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    cursor: 'pointer',
  },
  heroRosterBtnText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '700',
  },
  // ─── HERO LIVE METRICS CARDS ───
  heroStatsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
    flexWrap: 'wrap',
  },
  heroStatCard: {
    flex: 1,
    minWidth: 170,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
    padding: 14,
  },
  heroStatCardAlert: {
    backgroundColor: 'rgba(220, 38, 38, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  heroStatCardSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderColor: 'rgba(16, 185, 129, 0.25)',
  },
  heroStatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  heroStatNumber: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  heroStatTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
    marginBottom: 4,
  },
  heroStatDetail: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  heroFullyBookedNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(220, 38, 38, 0.15)',
    borderWidth: 1,
    borderColor: '#EF4444',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 16,
  },
  heroFullyBookedNoticeText: {
    color: '#FCA5A5',
    fontSize: 12.5,
    fontWeight: '700',
    flex: 1,
  },
  // ─── DEMO SIMULATION TOGGLE ───
  demoToggleRow: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 10,
  },
  demoTogglePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    cursor: 'pointer',
  },
  demoTogglePillActive: {
    backgroundColor: 'rgba(220, 38, 38, 0.3)',
    borderColor: '#EF4444',
  },
  demoTogglePillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
  },
  // ─── ROSTER MODAL STYLES ───
  rosterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  rosterModalContainer: {
    backgroundColor: '#0F172A',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#334155',
    width: '100%',
    maxWidth: 680,
    maxHeight: '90%',
    padding: 24,
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.5)',
  },
  rosterModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  rosterModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rosterModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  rosterModalSub: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  rosterModalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  rosterItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#1E293B',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#334155',
  },
  rosterItemAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#475569',
  },
  rosterItemBody: {
    flex: 1,
  },
  rosterItemName: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  rosterItemSpec: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#38BDF8',
    marginBottom: 2,
  },
  rosterItemBay: {
    fontSize: 11,
    color: '#94A3B8',
  },
  rosterStatusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  rosterStatusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  // ─── EMBEDDED BOOKING CARD ───
  bookingCardWrap: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 32,
    marginBottom: 28,
    boxShadow: '0 4px 20px -2px rgba(15, 23, 42, 0.05)',
  },
  bookingCardHeader: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  bookingFormTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0F172A',
  },
  bookingFormSub: {
    fontSize: 13.5,
    color: '#64748B',
    marginTop: 4,
    lineHeight: 20,
  },
  submitBookingBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1D4533',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 14,
    marginTop: 18,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(29, 69, 51, 0.3)',
  },
  submitBookingBtnRepair: {
    backgroundColor: '#DC2626',
    boxShadow: '0 4px 14px rgba(220, 38, 38, 0.3)',
  },
  submitBookingBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  // ─── STEP WIZARD STYLES ───
  wizardStepsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflowX: 'auto',
  },
  wizardStepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  wizardStepItemActive: {
    backgroundColor: '#FFFFFF',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.08)',
  },
  wizardStepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardStepBadgeActive: {
    backgroundColor: '#1D4533',
  },
  wizardStepBadgeActiveRepair: {
    backgroundColor: '#DC2626',
  },
  wizardStepBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
  },
  wizardStepBadgeTextActive: {
    color: '#FFFFFF',
  },
  wizardStepLabel: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#64748B',
  },
  wizardStepLabelActive: {
    color: '#0F172A',
    fontWeight: '800',
  },
  // ─── SINGLE FLAGSHIP HUB BANNER ───
  singleHubCard: {
    backgroundColor: '#F3F7F6',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#1D4533',
    padding: 16,
    marginBottom: 16,
  },
  singleHubBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#1D4533',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  singleHubBadgeText: {
    color: '#FFFFFF',
    fontSize: 10.5,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  singleHubTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#18181B',
    marginBottom: 4,
  },
  singleHubAddress: {
    fontSize: 12.5,
    color: '#334155',
    lineHeight: 18,
    marginBottom: 6,
  },
  singleHubFeatures: {
    fontSize: 11.5,
    color: '#1D4533',
    fontWeight: '700',
  },
  // ─── PHOTO UPLOAD ───
  photoUploadBox: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    marginBottom: 14,
    cursor: 'pointer',
  },
  photoThumbnailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  photoThumbWrap: {
    width: 90,
    height: 90,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  photoThumbImg: {
    width: '100%',
    height: '100%',
  },
  photoRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(220, 38, 38, 0.9)',
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ─── REVIEW SUMMARY CARD ───
  reviewSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 20,
    marginBottom: 20,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  reviewLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  reviewValue: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: '800',
    textAlign: 'right',
    maxWidth: '60%',
  },
  wizardNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 12,
  },
  wizardBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    cursor: 'pointer',
  },
  wizardBackBtnText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#475569',
  },
  wizardNextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#1D4533',
    cursor: 'pointer',
  },
  wizardNextBtnRepair: {
    backgroundColor: '#DC2626',
  },
  wizardNextBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  // ─── ONE FILL UP PAGE POPUP MODAL STYLES ───
  popupModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
    backdropFilter: 'blur(8px)',
  },
  popupModalBackdropTouchable: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  popupModalCard: {
    width: '100%',
    maxWidth: 680,
    maxHeight: '90vh',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    overflow: 'hidden',
    boxShadow: '0 25px 60px -12px rgba(15, 23, 42, 0.35)',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    zIndex: 10,
  },
  popupModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  popupModalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
  },
  popupModalSub: {
    fontSize: 12.5,
    color: '#64748B',
    marginTop: 2,
  },
  popupModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  popupModalBody: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    flex: 1,
    maxHeight: 'calc(90vh - 145px)',
    overflowY: 'auto',
  },
  formSectionBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 16,
    marginBottom: 16,
  },
  formSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  formSectionHeading: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  popupModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    paddingHorizontal: 22,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  popupCancelBtn: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  popupCancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  popupSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#1D4533',
    shadowColor: '#1D4533',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  popupSubmitBtnText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // ─── MULTI-STEP BOOKING MODAL STYLES ───
  stepperHeader: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 16,
  },
  stepperTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  stepperIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#E6F8F5',
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperModalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  stepperModalSubtitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1D4533',
    marginTop: 2,
  },
  stepperCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingBottom: 4,
  },
  stepNodeWrap: {
    alignItems: 'center',
    gap: 8,
    flex: 1,
    cursor: 'pointer',
  },
  stepCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F0F6FA',
    borderWidth: 1.5,
    borderColor: '#D0DFEB',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  stepCircleActive: {
    backgroundColor: '#1D4533',
    borderColor: '#1D4533',
    boxShadow: '0 0 0 4px #DCE9E2, 0 2px 6px rgba(29, 69, 51, 0.25)',
  },
  stepCircleCompleted: {
    backgroundColor: '#1D4533',
    borderColor: '#1D4533',
    boxShadow: '0 0 0 3px #DCE9E2',
  },
  stepNumberText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#3B7097',
  },
  stepNumberTextActive: {
    color: '#FFFFFF',
  },
  stepLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#5A738E',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#1D4533',
    fontWeight: '900',
  },
  stepLabelCompleted: {
    color: '#1D4533',
    fontWeight: '800',
  },
  stepConnectingLine: {
    height: 2,
    backgroundColor: '#D0DFEB',
    flex: 0.8,
    marginHorizontal: -6,
    marginTop: 16,
  },
  stepConnectingLineCompleted: {
    backgroundColor: '#1D4533',
  },
  stepSectionHeader: {
    marginBottom: 16,
  },
  stepSectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  stepSectionSubtitle: {
    fontSize: 12.5,
    color: '#64748B',
    marginTop: 3,
    lineHeight: 18,
  },
  serviceCardGrid: {
    flexDirection: 'row',
    gap: 16,
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  serviceCard: {
    flex: 1,
    minWidth: 260,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    padding: 20,
    cursor: 'pointer',
    position: 'relative',
    transition: 'all 0.2s ease',
  },
  serviceCardActivePMS: {
    borderColor: '#1D4533',
    backgroundColor: '#F0FDFA',
    boxShadow: '0 8px 24px rgba(29, 69, 51, 0.12)',
  },
  serviceCardActiveRepair: {
    borderColor: '#DC2626',
    backgroundColor: '#FFF5F5',
    boxShadow: '0 8px 24px rgba(220, 38, 38, 0.12)',
  },
  packageCardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(290px, 1fr))',
    gap: 16,
    marginBottom: 20,
  },
  packageCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    cursor: 'pointer',
    position: 'relative',
    transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)',
  },
  packageCardActive: {
    borderColor: '#1D4533',
    backgroundColor: '#F0FDFA',
    boxShadow: '0 12px 28px -6px rgba(29, 69, 51, 0.16)',
    transform: 'translateY(-2px)',
  },
  packageCardActiveRepair: {
    borderColor: '#DC2626',
    backgroundColor: '#FFF5F5',
    boxShadow: '0 12px 28px -6px rgba(220, 38, 38, 0.16)',
    transform: 'translateY(-2px)',
  },
  packageCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  packageCardIconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  packageCardRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  packageCardRadioActive: {
    borderColor: '#1D4533',
    backgroundColor: '#1D4533',
  },
  packageCardRadioActiveRepair: {
    borderColor: '#DC2626',
    backgroundColor: '#DC2626',
  },
  packageCardTitle: {
    fontSize: 16.5,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 4,
  },
  packageCardSubtitle: {
    fontSize: 12.5,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 12,
  },
  packageCardPricingRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 12,
  },
  packageCardPrice: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0F172A',
  },
  packageCardDurationPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
  },
  packageCardInclusionsList: {
    gap: 7,
    marginBottom: 16,
    flex: 1,
  },
  packageCardInclusionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 7,
  },
  packageCardInclusionText: {
    fontSize: 12,
    color: '#334155',
    fontWeight: '600',
    lineHeight: 16,
    flex: 1,
  },
  packageCardSelectBtn: {
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    marginTop: 'auto',
  },
  packageCardSelectBtnActive: {
    backgroundColor: '#1D4533',
    borderColor: '#1D4533',
  },
  packageCardSelectBtnActiveRepair: {
    backgroundColor: '#DC2626',
    borderColor: '#DC2626',
  },
  faultAreaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 10,
  },
  faultAreaCard: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  faultAreaCardActive: {
    backgroundColor: '#FEE2E2',
    borderColor: '#DC2626',
    boxShadow: '0 4px 12px rgba(220, 38, 38, 0.1)',
  },
  // Studio Inspiration Package Card UI (Matching Reference)
  studioHeroWrap: {
    alignItems: 'center',
    textAlign: 'center',
    marginBottom: 20,
    paddingTop: 4,
  },
  studioEyebrowPill: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 999,
    marginBottom: 10,
    alignSelf: 'center',
  },
  studioEyebrowText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#92400E',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  studioTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: '"Playfair Display", Georgia, "Times New Roman", serif',
    letterSpacing: -0.5,
    marginBottom: 6,
    textAlign: 'center',
  },
  studioSubtitle: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
    textAlign: 'center',
  },
  studioCardsDeck: {
    display: 'flex',
    flexDirection: 'row',
    gap: 16,
    overflowX: 'auto',
    paddingVertical: 16,
    paddingHorizontal: 10,
    alignItems: 'stretch',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  studioCard: {
    width: 250,
    minHeight: 400,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    cursor: 'pointer',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    boxShadow: '0 12px 30px rgba(0, 0, 0, 0.22)',
    transition: 'all 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    backgroundColor: '#0F172A',
  },
  studioCardActive: {
    borderColor: '#F59E0B',
    boxShadow: '0 24px 50px -10px rgba(0, 0, 0, 0.65), 0 0 25px rgba(245, 158, 11, 0.35)',
    transform: 'translateY(-8px) scale(1.02)',
    zIndex: 10,
  },
  studioCardBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  studioCardGradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundImage: 'linear-gradient(180deg, rgba(15, 23, 42, 0.25) 0%, rgba(15, 23, 42, 0.65) 45%, rgba(10, 15, 29, 0.96) 80%, #080D1A 100%)',
  },
  studioCardHeaderPills: {
    position: 'relative',
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
  },
  studioGlassIconPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    backdropFilter: 'blur(8px)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  studioGlassCountPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    backdropFilter: 'blur(8px)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  studioGlassCountText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  studioCardBody: {
    position: 'relative',
    zIndex: 2,
    paddingHorizontal: 16,
    paddingTop: 40,
    paddingBottom: 14,
    flex: 1,
    justifyContent: 'flex-end',
  },
  studioCardTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: '"Playfair Display", Georgia, "Times New Roman", serif',
    lineHeight: 25,
    marginBottom: 8,
    textShadow: '0 2px 6px rgba(0,0,0,0.6)',
  },
  studioCardDesc: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 17,
    marginBottom: 12,
  },
  studioCardInclusionChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  studioCardInclusionChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  studioCardInclusionText: {
    fontSize: 10.5,
    color: '#F1F5F9',
    fontWeight: '600',
  },
  studioCardFooter: {
    position: 'relative',
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(10, 15, 29, 0.75)',
    backdropFilter: 'blur(8px)',
  },
  studioPriceLabel: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  studioPriceValue: {
    fontSize: 21,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: '"Playfair Display", Georgia, serif',
  },
  studioProceedBtn: {
    backgroundColor: '#F59E0B',
    backgroundImage: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    boxShadow: '0 4px 12px rgba(245, 158, 11, 0.35)',
    cursor: 'pointer',
  },
  studioProceedBtnSelected: {
    backgroundColor: '#10B981',
    backgroundImage: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    boxShadow: '0 4px 12px rgba(16, 185, 129, 0.35)',
  },
  studioProceedText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#1C1917',
    letterSpacing: 0.6,
  },
  studioArrowCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  motorcycleCardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
    gap: 16,
    marginBottom: 16,
  },
  motorcycleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    cursor: 'pointer',
    transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
    boxShadow: '0 4px 16px rgba(15, 23, 42, 0.05)',
  },
  motorcycleCardActive: {
    borderColor: '#1D4533',
    backgroundColor: '#FFFFFF',
    boxShadow: '0 10px 28px -4px rgba(29, 69, 51, 0.25), 0 0 0 2px #1D4533',
    transform: 'translateY(-2px)',
  },
  brandChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  brandChipActive: {
    backgroundColor: '#1D4533',
    borderColor: '#1D4533',
  },
  brandChipText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#334155',
  },
  brandChipTextActive: {
    color: '#FFFFFF',
  },
  stepperFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
    gap: 12,
  },
  stepBackBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  stepNextBtn: {
    paddingHorizontal: 22,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: '#1D4533',
    cursor: 'pointer',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    boxShadow: '0 4px 14px rgba(29, 69, 51, 0.25)',
  },
  stepNextBtnText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

export const gStyles = garageWebStyles;
export default garageWebStyles;

