import { StyleSheet } from 'react-native';

export const garageWebStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  headerWrapper: {
    backgroundColor: 'rgba(10, 15, 28, 0.85)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.15)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  headerInner: {
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
    paddingHorizontal: 24,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  logoSubText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1.2,
  },
  headerCenterNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  headerCenterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    cursor: 'pointer',
  },
  headerCenterBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  navActionIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    transition: 'all 0.3s ease',
  },
  navBadgeCircle: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderWidth: 2,
    borderColor: '#0A0F1C',
    zIndex: 10,
    boxShadow: '0 2px 6px rgba(239, 68, 68, 0.5)',
  },
  navBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  loggedInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  authButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signInHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#1E293B',
  },
  signInHeaderBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scrollContent: {
    paddingVertical: 24,
    paddingHorizontal: 24,
  },
  maxContainer: {
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
  },
  // ─── 4 KPI STATS GRID (MATCHING PROFILE / ADMIN STAT CARDS) ───
  garageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    flexWrap: 'wrap',
    gap: 14,
  },
  garageHeaderLeft: {
    flex: 1,
    minWidth: 260,
  },
  garageHeaderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  garageHeaderTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  garageHeaderSub: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  garageHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 32,
  },
  statCard: {
    flex: 1,
    minWidth: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.04)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
    elevation: 3,
    position: 'relative',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  statCardTealAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#0C6258',
  },
  statCardWarningAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  statCardDangerAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#EF4444',
  },
  statCardSuccessAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#10B981',
  },
  statCardBlueAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
  },
  statCardPurpleAccent: {
    borderLeftWidth: 4,
    borderLeftColor: '#8B5CF6',
  },
  statIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 36,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
    letterSpacing: -1,
  },
  statSub: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500',
  },
  heroCard: {
    backgroundColor: '#0F172A',
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: 'row',
    marginBottom: 28,
    borderWidth: 1,
    borderColor: '#1E293B',
  },
  heroLeft: {
    flex: 1.3,
    padding: 36,
    justifyContent: 'center',
  },
  heroTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(37, 99, 235, 0.2)',
    borderWidth: 1,
    borderColor: '#0C6258',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  heroTagText: {
    color: '#A7F3D0',
    fontSize: 12,
    fontWeight: '800',
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 34,
    marginBottom: 12,
  },
  heroSub: {
    fontSize: 13.5,
    color: '#94A3B8',
    lineHeight: 20,
  },
  heroRight: {
    flex: 1,
    minHeight: 220,
  },
  heroImg: {
    width: '100%',
    height: '100%',
  },
  tabBarRow: {
    marginBottom: 20,
  },
  tabButtons: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  tabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
  },
  tabBtnActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  tabBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  tabBtnTextActive: {
    color: '#FFFFFF',
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  serviceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  serviceImgWrap: {
    width: '100%',
    height: 180,
    backgroundColor: '#F1F5F9',
    position: 'relative',
  },
  serviceImg: {
    width: '100%',
    height: '100%',
  },
  serviceCatBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  serviceCatBadgeText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  servicePriceTag: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#0C6258',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  servicePriceText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  serviceBody: {
    padding: 16,
  },
  serviceTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  serviceDesc: {
    fontSize: 12.5,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 12,
  },
  inclusionsList: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    gap: 6,
    marginBottom: 14,
  },
  incItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  incItemText: {
    fontSize: 12,
    color: '#334155',
    fontWeight: '600',
  },
  bookServiceBtn: {
    backgroundColor: '#0C6258',
    borderRadius: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  bookServiceBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  bookingsContainer: {
    paddingVertical: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 16,
  },
  emptyBox: {
    padding: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 12,
  },
  emptySub: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 4,
  },
  bookingsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  bookingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 20,
    width: '48%',
  },
  bookingCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  bookingId: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  bookingServiceTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 2,
  },
  statusPillConfirmed: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusPillText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#15803D',
  },
  bookingDetailsGrid: {
    gap: 8,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 14,
  },
  bookingDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bookingDetailVal: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  cancelBookingBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
  },
  cancelBookingBtnText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#DC2626',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalBox: {
    width: '100%',
    maxWidth: 560,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.4)',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 16,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  modalSub: {
    fontSize: 12.5,
    color: '#0C6258',
    fontWeight: '700',
    marginTop: 2,
  },
  modalForm: {
    paddingVertical: 4,
  },
  fieldLabel: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#334155',
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
    fontSize: 13,
    color: '#0F172A',
    outlineStyle: 'none',
  },
  branchPickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  branchPickBtnActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  branchPickText: {
    fontSize: 12.5,
    color: '#475569',
    fontWeight: '600',
  },
  branchPickTextActive: {
    color: '#0C6258',
    fontWeight: '800',
  },
  timeSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  timeSlotPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  timeSlotPillActive: {
    borderColor: '#0C6258',
    backgroundColor: '#0C6258',
  },
  timeSlotText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  timeSlotTextActive: {
    color: '#FFFFFF',
  },
  modalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  modalCancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  modalCancelText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  modalSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#0C6258',
  },
  modalSubmitText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  statusPillRepair: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  statusPillPMS: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  // ─── WEB SERVICE TYPE SEGMENT SWITCHER ───
  serviceTypeSegmentWrap: {
    marginBottom: 16,
  },
  serviceTypeSegment: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 14,
    padding: 4,
    gap: 6,
  },
  serviceTypeTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    cursor: 'pointer',
  },
  serviceTypeTabActiveRepair: {
    backgroundColor: '#DC2626',
    boxShadow: '0 2px 8px rgba(220, 38, 38, 0.25)',
  },
  serviceTypeTabActivePMS: {
    backgroundColor: '#0C6258',
    boxShadow: '0 2px 8px rgba(12, 98, 88, 0.25)',
  },
  serviceTypeTabActiveCust: {
    backgroundColor: '#7C3AED',
    boxShadow: '0 2px 8px rgba(124, 58, 237, 0.25)',
  },
  serviceTypeTabText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#475569',
  },
  serviceTypeTabTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  // ─── REPAIR COMMON FAULT CHIPS ───
  repairFaultChipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  repairFaultChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    cursor: 'pointer',
  },
  repairFaultChipActive: {
    backgroundColor: '#FEF2F2',
    borderColor: '#DC2626',
  },
  repairFaultChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  repairFaultChipTextActive: {
    color: '#DC2626',
    fontWeight: '800',
  },
  // ─── HERO QUICK ACTIONS ───
  heroActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
  },
  heroBookRepairBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#DC2626',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    cursor: 'pointer',
  },
  heroBookPMSBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#0C6258',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    cursor: 'pointer',
  },
  heroBookBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  heroBookTomorrowBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#0C6258',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 98, 88, 0.35)',
  },
  heroBookTomorrowBtnText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    fontWeight: '800',
  },
  heroRosterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    cursor: 'pointer',
  },
  heroRosterBtnText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '700',
  },
  // ─── HERO LIVE METRICS CARDS ───
  heroStatsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
    flexWrap: 'wrap',
  },
  heroStatCard: {
    flex: 1,
    minWidth: 170,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
    padding: 14,
  },
  heroStatCardAlert: {
    backgroundColor: 'rgba(220, 38, 38, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  heroStatCardSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderColor: 'rgba(16, 185, 129, 0.25)',
  },
  heroStatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  heroStatNumber: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  heroStatTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
    marginBottom: 4,
  },
  heroStatDetail: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  heroFullyBookedNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(220, 38, 38, 0.15)',
    borderWidth: 1,
    borderColor: '#EF4444',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 16,
  },
  heroFullyBookedNoticeText: {
    color: '#FCA5A5',
    fontSize: 12.5,
    fontWeight: '700',
    flex: 1,
  },
  // ─── DEMO SIMULATION TOGGLE ───
  demoToggleRow: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 10,
  },
  demoTogglePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    cursor: 'pointer',
  },
  demoTogglePillActive: {
    backgroundColor: 'rgba(220, 38, 38, 0.3)',
    borderColor: '#EF4444',
  },
  demoTogglePillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
  },
  // ─── ROSTER MODAL STYLES ───
  rosterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  rosterModalContainer: {
    backgroundColor: '#0F172A',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#334155',
    width: '100%',
    maxWidth: 680,
    maxHeight: '90%',
    padding: 24,
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.5)',
  },
  rosterModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  rosterModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rosterModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  rosterModalSub: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  rosterModalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  rosterItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#1E293B',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#334155',
  },
  rosterItemAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#475569',
  },
  rosterItemBody: {
    flex: 1,
  },
  rosterItemName: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  rosterItemSpec: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#38BDF8',
    marginBottom: 2,
  },
  rosterItemBay: {
    fontSize: 11,
    color: '#94A3B8',
  },
  rosterStatusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  rosterStatusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  // ─── EMBEDDED BOOKING CARD ───
  bookingCardWrap: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 32,
    marginBottom: 28,
    boxShadow: '0 4px 20px -2px rgba(15, 23, 42, 0.05)',
  },
  bookingCardHeader: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  bookingFormTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0F172A',
  },
  bookingFormSub: {
    fontSize: 13.5,
    color: '#64748B',
    marginTop: 4,
    lineHeight: 20,
  },
  submitBookingBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0C6258',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 14,
    marginTop: 18,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 98, 88, 0.3)',
  },
  submitBookingBtnRepair: {
    backgroundColor: '#DC2626',
    boxShadow: '0 4px 14px rgba(220, 38, 38, 0.3)',
  },
  submitBookingBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  // ─── STEP WIZARD STYLES ───
  wizardStepsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflowX: 'auto',
  },
  wizardStepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  wizardStepItemActive: {
    backgroundColor: '#FFFFFF',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.08)',
  },
  wizardStepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardStepBadgeActive: {
    backgroundColor: '#0C6258',
  },
  wizardStepBadgeActiveRepair: {
    backgroundColor: '#DC2626',
  },
  wizardStepBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
  },
  wizardStepBadgeTextActive: {
    color: '#FFFFFF',
  },
  wizardStepLabel: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#64748B',
  },
  wizardStepLabelActive: {
    color: '#0F172A',
    fontWeight: '800',
  },
  // ─── SINGLE FLAGSHIP HUB BANNER ───
  singleHubCard: {
    backgroundColor: '#F3F7F6',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#0C6258',
    padding: 16,
    marginBottom: 16,
  },
  singleHubBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#0C6258',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  singleHubBadgeText: {
    color: '#FFFFFF',
    fontSize: 10.5,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  singleHubTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#18181B',
    marginBottom: 4,
  },
  singleHubAddress: {
    fontSize: 12.5,
    color: '#334155',
    lineHeight: 18,
    marginBottom: 6,
  },
  singleHubFeatures: {
    fontSize: 11.5,
    color: '#0C6258',
    fontWeight: '700',
  },
  // ─── PHOTO UPLOAD ───
  photoUploadBox: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    marginBottom: 14,
    cursor: 'pointer',
  },
  photoThumbnailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  photoThumbWrap: {
    width: 90,
    height: 90,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  photoThumbImg: {
    width: '100%',
    height: '100%',
  },
  photoRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(220, 38, 38, 0.9)',
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ─── REVIEW SUMMARY CARD ───
  reviewSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 20,
    marginBottom: 20,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  reviewLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  reviewValue: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: '800',
    textAlign: 'right',
    maxWidth: '60%',
  },
  wizardNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 12,
  },
  wizardBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    cursor: 'pointer',
  },
  wizardBackBtnText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#475569',
  },
  wizardNextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#0C6258',
    cursor: 'pointer',
  },
  wizardNextBtnRepair: {
    backgroundColor: '#DC2626',
  },
  wizardNextBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  // ─── ONE FILL UP PAGE POPUP MODAL STYLES ───
  popupModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
    backdropFilter: 'blur(8px)',
  },
  popupModalBackdropTouchable: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  popupModalCard: {
    width: '100%',
    maxWidth: 680,
    maxHeight: '90vh',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    overflow: 'hidden',
    boxShadow: '0 25px 60px -12px rgba(15, 23, 42, 0.35)',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    zIndex: 10,
  },
  popupModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  popupModalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
  },
  popupModalSub: {
    fontSize: 12.5,
    color: '#64748B',
    marginTop: 2,
  },
  popupModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  popupModalBody: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    flex: 1,
    maxHeight: 'calc(90vh - 145px)',
    overflowY: 'auto',
  },
  formSectionBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 16,
    marginBottom: 16,
  },
  formSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  formSectionHeading: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  popupModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    paddingHorizontal: 22,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  popupCancelBtn: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  popupCancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  popupSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#0C6258',
    shadowColor: '#0C6258',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  popupSubmitBtnText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

export const gStyles = garageWebStyles;
export default garageWebStyles;

