import { StyleSheet } from 'react-native';

export const botanicalStyles = StyleSheet.create({
  organicBlob: {
    position: 'absolute',
    top: -30,
    left: -30,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#56B9A1',
    opacity: 0.7,
  },
  decorWrap: {
    position: 'absolute',
    right: 20,
    top: 20,
    alignItems: 'center',
    opacity: 0.9,
  },
  leafGroup: {
    alignItems: 'center',
    marginBottom: -4,
  },
  leftLeaf: {
    position: 'absolute',
    bottom: 16,
    left: -10,
    width: 10,
    height: 38,
    backgroundColor: '#56B9A1',
    borderRadius: 8,
    transform: [{ rotate: '-18deg' }],
  },
  centerLeaf: {
    width: 12,
    height: 52,
    backgroundColor: '#74C9B4',
    borderRadius: 8,
    zIndex: 2,
  },
  rightLeaf: {
    position: 'absolute',
    bottom: 14,
    right: -10,
    width: 10,
    height: 34,
    backgroundColor: '#48A48D',
    borderRadius: 8,
    transform: [{ rotate: '20deg' }],
  },
  potBody: {
    width: 32,
    height: 28,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
});

export const authWebStyles = StyleSheet.create({
  pageWrapper: {
    flex: 1,
    backgroundColor: '#18181B',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    minHeight: '100vh',
  },
  topNav: {
    width: '100%',
    maxWidth: 820,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  topBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBrandText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  backStoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  backStoreBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#88A9A3',
  },
  cardContainer: {
    width: 820,
    minHeight: 570,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 25px 60px rgba(0, 0, 0, 0.5)',
  },
  formHalf: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 410,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
  },
  leftFormHalf: {
    left: 0,
  },
  rightFormHalf: {
    right: 0,
  },
  formScrollInner: {
    paddingHorizontal: 32,
    paddingVertical: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formHeading: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0C6258',
    marginBottom: 4,
    textAlign: 'center',
  },
  mutedSubtext: {
    fontSize: 11.5,
    color: '#88A9A3',
    marginBottom: 14,
    textAlign: 'center',
  },
  inputWrap: {
    width: '100%',
    backgroundColor: '#F3F7F6',
    borderRadius: 20,
    height: 42,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  textInput: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
    fontWeight: '600',
    outlineStyle: 'none',
  },
  forgotPasswordBtn: {
    alignSelf: 'flex-end',
    marginBottom: 10,
    marginTop: -4,
  },
  forgotPasswordText: {
    fontSize: 11.5,
    color: '#88A9A3',
    fontWeight: '600',
  },
  primaryTealBtn: {
    backgroundColor: '#0C6258',
    borderRadius: 22,
    paddingVertical: 11,
    paddingHorizontal: 36,
    marginTop: 6,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 14px rgba(12, 98, 88, 0.35)',
  },
  primaryTealBtnDisabled: {
    backgroundColor: '#94A3B8',
    boxShadow: 'none',
  },
  primaryTealBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
  },

  // Password Strength Meter
  strengthMeterBox: {
    width: '100%',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  strengthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  strengthLabel: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '600',
  },
  strengthBadge: {
    fontSize: 10.5,
    fontWeight: '800',
  },
  meterTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
    marginBottom: 6,
  },
  meterFill: {
    height: '100%',
    borderRadius: 2,
  },
  criteriaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  criteriaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  criteriaChipText: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontWeight: '500',
  },
  criteriaChipTextActive: {
    color: '#059669',
    fontWeight: '700',
  },

  // OTP Container & Inputs
  otpContainer: {
    width: '100%',
    alignItems: 'center',
  },
  otpBackBtn: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  },
  otpBackBtnText: {
    fontSize: 11.5,
    color: '#0C6258',
    fontWeight: '700',
  },
  otpHeader: {
    alignItems: 'center',
    marginBottom: 12,
  },
  otpBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E7F5F3',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  otpSubtitle: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
    maxWidth: 280,
  },
  otpEmailHighlight: {
    fontWeight: '800',
    color: '#0C6258',
  },
  instantOtpBadge: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
    width: '100%',
  },
  instantOtpText: {
    fontSize: 11,
    color: '#1D4ED8',
    fontWeight: '600',
    flex: 1,
  },
  instantOtpCode: {
    fontWeight: '900',
    letterSpacing: 2,
    color: '#1E40AF',
  },
  otpBoxesRow: {
    flexDirection: 'row',
    gap: 8,
    marginVertical: 14,
  },
  otpBox: {
    width: 42,
    height: 48,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
    color: '#0C6258',
    outlineStyle: 'none',
  },
  otpBoxFilled: {
    borderColor: '#0C6258',
    backgroundColor: '#FFFFFF',
  },
  resendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  resendText: {
    fontSize: 11.5,
    color: '#64748B',
  },
  resendLink: {
    fontSize: 11.5,
    color: '#0C6258',
    fontWeight: '800',
  },
  resendCountdown: {
    fontSize: 11.5,
    color: '#94A3B8',
    fontWeight: '700',
  },

  // Fast Login Section
  fastLoginSection: {
    marginTop: 14,
    width: '100%',
    alignItems: 'center',
  },
  fastLoginTitle: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '700',
    marginBottom: 6,
  },
  fastLoginRow: {
    flexDirection: 'row',
    gap: 8,
  },
  fastPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#E2ECE9',
  },
  fastPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0C6258',
  },

  // Badges
  errorBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    marginBottom: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  errorBadgeText: {
    color: '#DC2626',
    fontSize: 11.5,
    fontWeight: '700',
    flex: 1,
  },
  infoBadge: {
    backgroundColor: '#E7F5F3',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    marginBottom: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  infoBadgeText: {
    color: '#0C6258',
    fontSize: 11.5,
    fontWeight: '700',
    flex: 1,
  },
  successBadge: {
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    marginBottom: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  successBadgeText: {
    color: '#065F46',
    fontSize: 11.5,
    fontWeight: '700',
    flex: 1,
  },

  // Sliding Overlay Panel
  slidingOverlayPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 410,
    height: '100%',
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 36,
    zIndex: 10,
    overflow: 'hidden',
  },
  overlayContentBox: {
    alignItems: 'center',
    textAlign: 'center',
    width: '100%',
    zIndex: 5,
  },
  overlayHeadingLine1: {
    fontSize: 26,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 30,
  },
  overlayHeadingLine2: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 30,
    marginBottom: 10,
  },
  overlaySubtext: {
    fontSize: 12.5,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 24,
    maxWidth: 260,
  },
  overlayGhostBtn: {
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 32,
    paddingVertical: 9,
  },
  overlayGhostBtnText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
});

export const authStyles = authWebStyles;
export default authWebStyles;
