import { StyleSheet, Platform } from 'react-native';

export function getProfileWebTokens(isDark = false) {
  if (isDark) {
    return {
      isDark: true,
      bgMain: '#0E1311',
      bgCard: '#141A18',
      bgSub: '#1C2422',
      bgSubtle: '#18201E',
      border: 'rgba(255, 255, 255, 0.09)',
      borderLight: 'rgba(255, 255, 255, 0.05)',
      borderInput: 'rgba(255, 255, 255, 0.14)',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#94A3B8',
      textSubtle: '#64748B',
      brandPrimary: '#22C55E',
      brandPrimaryDark: '#16A34A',
      brandLight: 'rgba(34, 197, 94, 0.14)',
      brandBorder: 'rgba(34, 197, 94, 0.35)',
      statusSuccessBg: 'rgba(16, 185, 129, 0.16)',
      statusSuccessText: '#34D399',
      statusSuccessBorder: 'rgba(16, 185, 129, 0.3)',
      statusWarningBg: 'rgba(245, 158, 11, 0.16)',
      statusWarningText: '#FBBF24',
      statusWarningBorder: 'rgba(245, 158, 11, 0.3)',
      statusDangerBg: 'rgba(239, 68, 68, 0.16)',
      statusDangerText: '#F87171',
      statusDangerBorder: 'rgba(239, 68, 68, 0.3)',
      statusInfoBg: 'rgba(56, 189, 248, 0.16)',
      statusInfoText: '#38BDF8',
      statusInfoBorder: 'rgba(56, 189, 248, 0.3)',
      statusNeutralBg: '#1C2422',
      statusNeutralText: '#CBD5E1',
      statusNeutralBorder: 'rgba(255, 255, 255, 0.08)',
      cardShadow: '#000000',
    };
  }

  return {
    isDark: false,
    bgMain: '#F8FAFC',
    bgCard: '#FFFFFF',
    bgSub: '#F8FAFC',
    bgSubtle: '#F1F5F9',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    borderInput: '#CBD5E1',
    textPrimary: '#0F172A',
    textSecondary: '#334155',
    textMuted: '#64748B',
    textSubtle: '#94A3B8',
    brandPrimary: '#1D4533',
    brandPrimaryDark: '#143325',
    brandLight: '#E8F0EC',
    brandBorder: '#C8DDD3',
    statusSuccessBg: '#DCFCE7',
    statusSuccessText: '#166534',
    statusSuccessBorder: '#86EFAC',
    statusWarningBg: '#FEF3C7',
    statusWarningText: '#92400E',
    statusWarningBorder: '#FDE68A',
    statusDangerBg: '#FEF2F2',
    statusDangerText: '#991B1B',
    statusDangerBorder: '#FECACA',
    statusInfoBg: '#EFF6FF',
    statusInfoText: '#1D4ED8',
    statusInfoBorder: '#BFDBFE',
    statusNeutralBg: '#F1F5F9',
    statusNeutralText: '#475569',
    statusNeutralBorder: '#E2E8F0',
    cardShadow: 'rgba(15, 23, 42, 0.04)',
  };
}

export function createProfileWebStyles(isDark = false) {
  const t = getProfileWebTokens(isDark);

  return StyleSheet.create({
    // ─── BASE LAYOUT ───
    container: {
      flex: 1,
      backgroundColor: t.bgMain,
    },
    adminLayout: {
      flex: 1,
      flexDirection: 'column',
      minHeight: Platform.OS === 'web' ? '100vh' : '100%',
      backgroundColor: t.bgMain,
    },

    // ─── SHOP-STYLE TOP NAVBAR (STICKY FOREST GREEN) ───
    headerWrapper: {
      backgroundColor: '#1D4533',
      backdropFilter: 'blur(16px)',
      WebkitBackdropFilter: 'blur(16px)',
      position: Platform.OS === 'web' ? 'sticky' : 'relative',
      top: 0,
      zIndex: 1000,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.10)',
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.15)',
      minHeight: 67,
    },
    headerInner: {
      maxWidth: 1360,
      marginHorizontal: 'auto',
      width: '100%',
      paddingHorizontal: 24,
      paddingVertical: 12,
      minHeight: 66,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 20,
    },
    logoWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      cursor: 'pointer',
    },
    headerLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 10,
    },
    mobileNavToggleBtn: {
      width: 42,
      height: 42,
      borderRadius: 10,
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
    },
    headerCenterNav: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    mainNavList: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    mainNavItem: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      cursor: 'pointer',
      backgroundColor: 'transparent',
    },
    mainNavItemActive: {
      backgroundColor: 'transparent',
    },
    mainNavItemText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#FFFFFF',
      opacity: 0.85,
      whiteSpace: 'nowrap',
    },
    mainNavItemTextActive: {
      color: '#FFFFFF',
      fontWeight: '900',
      opacity: 1,
      textShadow: '0 0 10px rgba(255, 255, 255, 0.6)',
    },
    headerActions: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 8,
    },
    navSearchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderRadius: 24,
      height: 38,
      width: 190,
      paddingHorizontal: 12,
      gap: 8,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.10)',
    },
    navSearchInput: {
      flex: 1,
      height: '100%',
      fontSize: 13,
      color: '#E2E8F0',
      outlineStyle: 'none',
    },
    navActionIconBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.10)',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      cursor: 'pointer',
    },
    navActionIconBtnActive: {
      backgroundColor: 'rgba(52, 211, 153, 0.22)',
      borderColor: '#34D399',
      boxShadow: '0 0 10px rgba(52, 211, 153, 0.45)',
    },
    navBadgeCircle: {
      position: 'absolute',
      top: -4,
      right: -4,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: '#EF4444',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: '#1D4533',
      zIndex: 10,
      boxShadow: '0 2px 6px rgba(239, 68, 68, 0.5)',
    },
    navBadgeText: {
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '900',
    },
    mobileNavDrawer: {
      backgroundColor: '#163829',
      borderTopWidth: 1,
      borderTopColor: 'rgba(255, 255, 255, 0.10)',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(0, 0, 0, 0.25)',
      paddingVertical: 10,
      paddingHorizontal: 16,
      gap: 4,
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.25)',
    },
    mobileNavItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      cursor: 'pointer',
    },
    mobileNavItemActive: {
      backgroundColor: 'transparent',
    },
    mobileNavItemText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#FFFFFF',
      opacity: 0.85,
    },
    mobileNavItemTextActive: {
      color: '#FFFFFF',
      fontWeight: '900',
      opacity: 1,
    },

    // ─── 3. MAIN CONTENT AREA & HEADER ───
    mainContentArea: {
      flex: 1,
      backgroundColor: t.bgMain,
      minWidth: 0,
    },
    mainScroll: {
      width: '100%',
      maxWidth: 1360,
      alignSelf: 'center',
      paddingHorizontal: 24,
      paddingVertical: 24,
      paddingBottom: 120,
    },

    // ─── 4. CARDS & GENERAL CONTAINERS ───
    sectionCard: {
      backgroundColor: t.bgCard,
      borderRadius: 14,
      padding: 20,
      borderWidth: 1,
      borderColor: t.border,
      marginBottom: 20,
      boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)',
    },
    sectionCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      flexWrap: 'wrap',
      gap: 10,
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    sectionTitleIconBox: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: t.brandLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: t.brandBorder,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: t.textPrimary,
      letterSpacing: -0.2,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    sectionSubtitle: {
      fontSize: 12,
      color: t.textMuted,
      marginTop: 2,
    },

    // ─── 5. OVERVIEW KPI STAT CARDS ───
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 14,
      marginBottom: 20,
    },
    statCard: {
      flex: 1,
      minWidth: 200,
      backgroundColor: t.bgCard,
      borderRadius: 14,
      padding: 18,
      borderWidth: 1,
      borderColor: t.border,
      boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)',
      justifyContent: 'space-between',
      minHeight: 128,
      cursor: 'pointer',
      transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    },
    statIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: t.brandLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    statLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: t.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 4,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    statValue: {
      fontSize: 25,
      fontWeight: '800',
      color: t.textPrimary,
      letterSpacing: -0.5,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    statSub: {
      fontSize: 11.5,
      color: t.textMuted,
      fontWeight: '500',
      marginTop: 3,
    },

    // ─── 6. CUSTOMER PROFILE SUMMARY (OVERVIEW) ───
    profileSummaryTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 14,
      marginBottom: 16,
    },
    profileSummaryUserRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    profileSummaryAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#1D4533',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      borderWidth: 2,
      borderColor: t.brandBorder,
    },
    profileSummaryName: {
      fontSize: 16,
      fontWeight: '800',
      color: t.textPrimary,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    verifiedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: t.statusSuccessBg,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: t.statusSuccessBorder,
    },
    verifiedBadgeText: {
      fontSize: 10.5,
      fontWeight: '800',
      color: t.statusSuccessText,
    },
    profileSummaryContact: {
      fontSize: 12,
      color: t.textMuted,
      marginTop: 3,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    summaryInfoBoxesRow: {
      flexDirection: 'row',
      gap: 14,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: t.border,
    },
    summaryInfoBox: {
      flex: 1,
      backgroundColor: t.bgSub,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: t.border,
    },
    summaryInfoLabel: {
      fontSize: 10.5,
      fontWeight: '700',
      color: t.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    summaryInfoValue: {
      fontSize: 13,
      fontWeight: '600',
      color: t.textPrimary,
      marginTop: 4,
      lineHeight: 18,
    },

    // ─── 7. RECENT ORDERS LIST ───
    orderListItem: {
      backgroundColor: t.bgSub,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 12,
      padding: 14,
      gap: 8,
    },
    orderListTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    orderItemTitle: {
      fontSize: 13.5,
      fontWeight: '700',
      color: t.textPrimary,
      flex: 1,
    },
    orderMetaText: {
      fontSize: 12,
      color: t.textMuted,
    },

    // ─── 8. GARAGE PIT BAY APPOINTMENT CARDS ───
    bookingSlotCard: {
      backgroundColor: t.bgSub,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 12,
      padding: 16,
      gap: 10,
    },
    bookingSlotHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    bookingSlotTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: t.textPrimary,
    },
    bookingMetaGrid: {
      gap: 4,
    },
    bookingMetaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    bookingMetaItemText: {
      fontSize: 12,
      color: t.textSecondary,
      fontWeight: '500',
    },

    // ─── 9. ACCOUNT PROFILE HEADER (REPLACING HUGE GREEN BANNER) ───
    profileHeaderCard: {
      backgroundColor: t.bgCard,
      borderColor: t.border,
      borderWidth: 1,
      borderRadius: 16,
      paddingVertical: 24,
      paddingHorizontal: 20,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'hidden',
      marginBottom: 20,
      boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)',
    },
    profileAvatarWrapper: {
      position: 'relative',
      width: 88,
      height: 88,
      marginBottom: 12,
    },
    profileAvatarCircle: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: '#1D4533',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: '#FFFFFF',
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    },
    profileCameraBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: '#1D4533',
      boxShadow: '0 2px 5px rgba(0, 0, 0, 0.15)',
      cursor: 'pointer',
    },
    profileFullName: {
      fontSize: 21,
      fontWeight: '800',
      color: t.textPrimary,
      textAlign: 'center',
      marginBottom: 3,
      letterSpacing: -0.2,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    profileHeadlineText: {
      fontSize: 13.5,
      fontWeight: '500',
      color: t.textSecondary,
      textAlign: 'center',
      marginBottom: 3,
    },
    profileLocationText: {
      fontSize: 12.5,
      fontWeight: '500',
      color: t.textMuted,
      textAlign: 'center',
    },
    profileHeaderActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: 14,
    },

    // ─── 10. 2-COLUMN PERSONAL INFORMATION GRID ───
    profileInfoGrid: {
      gap: 16,
    },
    profileInfoRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
    },
    profileInfoCol: {
      flex: 1,
      minWidth: 200,
    },
    profileFieldLabel: {
      fontSize: 10.5,
      fontWeight: '700',
      color: t.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: 4,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    profileFieldValue: {
      fontSize: 14,
      fontWeight: '700',
      color: t.textPrimary,
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },

    // ─── 11. BUTTON SYSTEM ───
    btnPrimary: {
      backgroundColor: '#1D4533',
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      cursor: 'pointer',
    },
    btnPrimaryText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    btnSecondary: {
      backgroundColor: t.bgCard,
      borderWidth: 1,
      borderColor: t.border,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      cursor: 'pointer',
    },
    btnSecondaryText: {
      color: t.textPrimary,
      fontSize: 12.5,
      fontWeight: '700',
      fontFamily: Platform.select({ web: "'Plus Jakarta Sans', sans-serif" }),
    },
    btnDangerSubtle: {
      backgroundColor: t.statusDangerBg,
      borderWidth: 1,
      borderColor: t.statusDangerBorder,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      cursor: 'pointer',
    },
    btnDangerSubtleText: {
      color: '#DC2626',
      fontSize: 12,
      fontWeight: '700',
    },
    btnGhost: {
      backgroundColor: 'transparent',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      cursor: 'pointer',
    },
    btnGhostText: {
      fontSize: 12,
      fontWeight: '600',
      color: t.textMuted,
    },

    // ─── 12. FORM INPUTS & BADGES ───
    inputBox: {
      backgroundColor: t.bgSub,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 9,
      color: t.textPrimary,
      fontSize: 13.5,
      outlineStyle: 'none',
    },
    statusBadgePill: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      alignSelf: 'flex-start',
    },
    statusBadgePillText: {
      fontSize: 11,
      fontWeight: '800',
    },

    // Backward compatibility with admin style keys
    addBtnPrimary: {
      backgroundColor: '#1D4533',
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      cursor: 'pointer',
    },
    addBtnPrimaryText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
    },
    quickStoreBtn: {
      backgroundColor: t.bgSub,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: t.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      cursor: 'pointer',
    },
    quickStoreBtnText: {
      color: t.brandPrimary,
      fontSize: 12,
      fontWeight: '700',
    },

    // Compatibility aliases for existing component keys
    adminProfileBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 10,
      borderRadius: 12,
      backgroundColor: t.bgSub,
      borderWidth: 1,
      borderColor: t.border,
      marginBottom: 12,
    },
    adminAvatarCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#1D4533',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    onlineIndicator: {
      position: 'absolute',
      bottom: -1,
      right: -1,
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: '#10B981',
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
    },
    profileNameText: {
      color: t.textPrimary,
      fontSize: 13,
      fontWeight: '700',
    },
    profileRoleText: {
      color: t.textMuted,
      fontSize: 11,
      fontWeight: '500',
    },
    navHeading: {
      fontSize: 10.5,
      fontWeight: '700',
      color: t.textSubtle,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
      marginTop: 14,
      marginBottom: 6,
      paddingHorizontal: 8,
    },
    sidebarCountBadge: {
      paddingHorizontal: 7,
      paddingVertical: 1.5,
      borderRadius: 10,
      backgroundColor: t.bgSubtle,
      borderWidth: 1,
      borderColor: t.border,
    },
    sidebarCountBadgeActive: {
      backgroundColor: t.brandPrimary,
      borderColor: t.brandPrimary,
    },
    sidebarCountText: {
      fontSize: 10.5,
      fontWeight: '700',
      color: t.textSecondary,
    },
    sidebarCountTextActive: {
      color: '#FFFFFF',
      fontWeight: '800',
    },
    statusDotGreen: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: '#10B981',
    },
    sidebarStatusText: {
      fontSize: 11,
      fontWeight: '600',
      color: t.textMuted,
    },
    logoutSidebarBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: t.statusDangerBg,
      borderWidth: 1,
      borderColor: t.statusDangerBorder,
      cursor: 'pointer',
    },
    logoutSidebarText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#DC2626',
    },
    statCardTealAccent: {
      borderColor: isDark ? 'rgba(16, 185, 129, 0.35)' : '#A7F3D0',
      borderWidth: 1.5,
    },
    statCardWarningAccent: {
      borderColor: isDark ? 'rgba(245, 158, 11, 0.35)' : '#FDE68A',
      borderWidth: 1.5,
    },
    statCardDangerAccent: {
      borderColor: isDark ? 'rgba(244, 63, 94, 0.35)' : '#FECDD3',
      borderWidth: 1.5,
    },
    statCardSuccessAccent: {
      borderColor: isDark ? 'rgba(59, 130, 246, 0.35)' : '#BFDBFE',
      borderWidth: 1.5,
    },
    statCardPurpleAccent: {
      borderColor: isDark ? 'rgba(139, 92, 246, 0.35)' : '#DDD6FE',
      borderWidth: 1.5,
    },
    statCardBlueAccent: {
      borderColor: isDark ? 'rgba(59, 130, 246, 0.35)' : '#BFDBFE',
      borderWidth: 1.5,
    },
    tableScrollContainer: {
      width: '100%',
      ...(Platform.OS === 'web' ? { overflowX: 'auto' } : {}),
    },
    tableCard: {
      backgroundColor: t.bgCard,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: t.border,
      overflow: 'hidden',
      width: '100%',
    },
    tableHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: t.bgSub,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    tableHeaderCell: {
      fontSize: 12,
      fontWeight: '700',
      color: t.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    tableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: t.borderLight,
      backgroundColor: t.bgCard,
    },
    productThumb: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: t.bgSub,
      borderWidth: 1,
      borderColor: t.border,
      marginRight: 10,
    },
    tableTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: t.textPrimary,
    },
    tableSub: {
      fontSize: 11.5,
      color: t.textMuted,
      marginTop: 2,
    },
  });
}

export const profileWebStyles = createProfileWebStyles(false);
export default profileWebStyles;
