import { StyleSheet } from 'react-native';

export const profileWebStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#020617',
    minHeight: '100vh',
  },
  scrollContent: {
    paddingBottom: 80,
  },
  maxContainer: {
    width: '100%',
    maxWidth: 1320,
    alignSelf: 'center',
    paddingHorizontal: 20,
  },

  // ─── TOP STICKY NAVBAR ───
  headerWrapper: {
    backgroundColor: 'rgba(10, 15, 28, 0.85)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.25)',
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
  },
  logoIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  headerNavLinks: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  navLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    cursor: 'pointer',
  },
  navLinkBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#E2E8F0',
  },
  userPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 4,
    paddingRight: 12,
    paddingVertical: 4,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    cursor: 'pointer',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  userAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  userNameText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // ─── HERO GREETING BANNER ───
  heroBanner: {
    backgroundColor: '#020617',
    backgroundImage: 'radial-gradient(circle at top right, #1E293B 0%, #020617 70%)',
    borderRadius: 24,
    padding: 24,
    marginTop: 20,
    marginBottom: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  heroLeft: {
    flex: 1,
    minWidth: 280,
  },
  heroTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(12, 98, 88, 0.25)',
    borderWidth: 1,
    borderColor: '#0C6258',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  heroTagText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#56B9A1',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  heroSub: {
    fontSize: 13.5,
    color: '#94A3B8',
    marginTop: 4,
  },
  heroStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  heroStatCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  heroStatNumber: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  heroStatLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
    marginTop: 2,
  },

  // ─── TWO-COLUMN SIDEBAR & CONTENT LAYOUT ───
  layoutRow: {
    flexDirection: 'row',
    gap: 24,
    alignItems: 'flex-start',
  },

  // ─── LEFT SIDEBAR ───
  sidebar: {
    width: 300,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.3)',
    position: 'sticky',
    top: 86,
  },
  sidebarUserCard: {
    alignItems: 'center',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    marginBottom: 12,
  },
  sidebarAvatarWrap: {
    position: 'relative',
    marginBottom: 10,
  },
  sidebarAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: '#10B981',
    backgroundColor: '#1E293B',
    boxShadow: '0 0 15px rgba(16, 185, 129, 0.4)',
  },
  sidebarAvatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  sidebarName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  sidebarEmail: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
    textAlign: 'center',
  },
  sidebarRoleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    marginTop: 8,
  },
  sidebarRoleText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#10B981',
    textShadowColor: 'rgba(16, 185, 129, 0.5)',
    textShadowRadius: 8,
  },

  // Sidebar Menu Tabs
  sidebarNav: {
    gap: 4,
  },
  sidebarTabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    cursor: 'pointer',
  },
  sidebarTabBtnActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    boxShadow: 'inset 0 0 10px rgba(16, 185, 129, 0.1)',
  },
  sidebarTabIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
  },
  sidebarTabIconBoxActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  sidebarTabText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#94A3B8',
    flex: 1,
  },
  sidebarTabTextActive: {
    color: '#10B981',
    fontWeight: '900',
    textShadowColor: 'rgba(16, 185, 129, 0.5)',
    textShadowRadius: 8,
  },
  sidebarBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
  },
  sidebarBadgeActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  sidebarBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#475569',
  },
  sidebarBadgeTextActive: {
    color: '#FFFFFF',
  },

  sidebarDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginVertical: 12,
  },
  sidebarLogoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    cursor: 'pointer',
  },
  sidebarLogoutText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#DC2626',
  },

  // ─── RIGHT MAIN CONTENT AREA ───
  mainContent: {
    flex: 1,
    minWidth: 0,
  },
  sectionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 24,
    marginBottom: 20,
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.25)',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    marginBottom: 20,
    flexWrap: 'wrap',
    gap: 12,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionTitleIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  sectionSubtitle: {
    fontSize: 12.5,
    color: '#94A3B8',
    marginTop: 2,
  },

  // Form Fields
  formGrid: {
    gap: 16,
  },
  formRow: {
    flexDirection: 'row',
    gap: 14,
    flexWrap: 'wrap',
  },
  formCol: {
    flex: 1,
    minWidth: 220,
  },
  formLabel: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#334155',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13.5,
    color: '#0F172A',
    outlineStyle: 'none',
  },
  textarea: {
    minHeight: 70,
    paddingTop: 10,
  },

  // Preset Chips
  presetsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  presetChip: {
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    cursor: 'pointer',
  },
  presetChipText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#475569',
  },

  // Brand Chips
  brandChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  brandChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    cursor: 'pointer',
  },
  brandChipActive: {
    backgroundColor: '#0C6258',
  },
  brandChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  brandChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },

  // Primary Action Button
  primaryBtn: {
    backgroundColor: '#0C6258',
    paddingVertical: 13,
    paddingHorizontal: 22,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    cursor: 'pointer',
    alignSelf: 'flex-start',
    marginTop: 18,
  },
  primaryBtnText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // ─── BOOKINGS CARDS STYLES ───
  bookingsFilterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  bookingFilterPill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    cursor: 'pointer',
  },
  bookingFilterPillActive: {
    backgroundColor: '#0F172A',
  },
  bookingFilterText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  bookingFilterTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  bookingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 18,
    marginBottom: 14,
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.03)',
  },
  bookingCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 12,
  },
  ticketBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  ticketBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#475569',
  },
  bookingTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  bookingStatusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  bookingStatusText: {
    fontSize: 11.5,
    fontWeight: '800',
  },
  bookingMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
    marginTop: 6,
  },
  bookingMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bookingMetaVal: {
    fontSize: 12.5,
    color: '#475569',
    fontWeight: '600',
  },
  bookingFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F8FAFC',
    flexWrap: 'wrap',
    gap: 10,
  },
  cancelBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    cursor: 'pointer',
  },
  cancelBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#DC2626',
  },

  // ─── ORDERS CARD STYLES ───
  orderCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 18,
    marginBottom: 14,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 12,
    flexWrap: 'wrap',
    gap: 8,
  },
  orderIdText: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0F172A',
  },
  orderDateText: {
    fontSize: 11.5,
    color: '#94A3B8',
    marginTop: 2,
  },
  orderItemsList: {
    gap: 6,
    marginBottom: 12,
  },
  orderItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderItemName: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  orderItemPrice: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
  },
  trackOrderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    cursor: 'pointer',
  },
  trackOrderBtnText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#2563EB',
  },

  // ─── NOTIFICATIONS LIST STYLES ───
  notifItem: {
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
    alignItems: 'flex-start',
    cursor: 'pointer',
  },
  notifItemUnread: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderLeftWidth: 4,
    borderLeftColor: '#0C6258',
  },
  notifIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifContent: {
    flex: 1,
  },
  notifTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  notifMessage: {
    fontSize: 12.5,
    color: '#475569',
    marginTop: 3,
    lineHeight: 18,
  },
  notifTime: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 4,
  },
  emptyBox: {
    alignItems: 'center',
    paddingVertical: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 12,
  },
  emptySub: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 4,
  },

  // ─── BOOKING LIFECYCLE & WORKFLOW STYLES ───
  lifecyclePipeline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflowX: 'auto',
  },
  lifecycleStepPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
  },
  lifecycleStepPillActive: {
    backgroundColor: '#0C6258',
  },
  lifecycleStepPillDone: {
    backgroundColor: '#DCFCE7',
  },
  lifecycleStepText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
  },
  lifecycleStepTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  lifecycleStepTextDone: {
    color: '#16A34A',
    fontWeight: '800',
  },
  lifecycleArrow: {
    fontSize: 11,
    color: '#CBD5E1',
    fontWeight: '900',
  },

  // Estimate Approval Card
  estimateCard: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
    borderColor: '#F87171',
    borderRadius: 14,
    padding: 14,
    marginTop: 12,
  },
  estimateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  estimateTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#991B1B',
  },
  estimateAmount: {
    fontSize: 15,
    fontWeight: '900',
    color: '#DC2626',
  },
  estimateDesc: {
    fontSize: 12.5,
    color: '#7F1D1D',
    lineHeight: 18,
    marginBottom: 10,
  },
  estimateActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  estimateApproveBtn: {
    flex: 1,
    backgroundColor: '#16A34A',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  estimateApproveText: {
    color: '#FFFFFF',
    fontSize: 12.5,
    fontWeight: '800',
  },
  estimateDeclineBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  estimateDeclineText: {
    color: '#64748B',
    fontSize: 12.5,
    fontWeight: '700',
  },

  // Bill Settlement Card
  billCard: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1.5,
    borderColor: '#86EFAC',
    borderRadius: 14,
    padding: 14,
    marginTop: 12,
  },
  billHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  billTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#166534',
  },
  billTotalAmount: {
    fontSize: 18,
    fontWeight: '900',
    color: '#15803D',
  },
  payBillBtn: {
    backgroundColor: '#0C6258',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    cursor: 'pointer',
  },
  payBillBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },

  // Service Report & Next PMS Reminder Card
  reportCard: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 14,
    padding: 14,
    marginTop: 12,
  },
  nextPmsCard: {
    backgroundColor: '#F3F7F6',
    borderWidth: 1.5,
    borderColor: '#0C6258',
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  nextPmsBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextPmsTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#042F2E',
  },
  nextPmsDetail: {
    fontSize: 11.5,
    color: '#0C6258',
    fontWeight: '700',
    marginTop: 2,
  },
});

