import { StyleSheet } from 'react-native';

export const shopWebStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  headerWrapper: {
    backgroundColor: 'rgba(10, 15, 28, 0.85)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.15)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  headerInner: {
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
    paddingHorizontal: 24,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    textDecorationLine: 'none',
  },
  logoIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundImage: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(16, 185, 129, 0.4)',
  },
  logoText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  logoAccent: {
    color: '#0C6258',
  },
  logoSubText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 1,
  },
  searchContainer: {
    flex: 1,
    maxWidth: 480,
    height: 42,
    backgroundColor: '#F1F5F9',
    borderRadius: 21,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchInput: {
    flex: 1,
    fontSize: 13.5,
    color: '#0F172A',
    outlineStyle: 'none',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  navLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  navLinkBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  headerIconBtnDark: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0F172A',
    borderWidth: 1.5,
    borderColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.15)',
  },
  navSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 24,
    height: 42,
    width: 280,
    paddingHorizontal: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  navSearchInput: {
    flex: 1,
    height: '100%',
    fontSize: 13.5,
    color: '#E2E8F0',
    outlineStyle: 'none',
    paddingVertical: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  navActionIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    transition: 'all 0.3s ease',
  },
  navBadgeCircle: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderWidth: 2,
    borderColor: '#0A0F1C',
    zIndex: 10,
    boxShadow: '0 2px 6px rgba(239, 68, 68, 0.5)',
  },
  navBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  headerCenterNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  headerAiVisionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  headerAiVisionBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  headerRepairBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  headerRepairBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  headerFavoritesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 14,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    boxShadow: '0 2px 6px rgba(15, 23, 42, 0.04)',
  },
  headerFavoritesBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1E293B',
    letterSpacing: 0.1,
  },
  headerFavoritesBadge: {
    backgroundColor: '#EF4444',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    marginLeft: 2,
  },
  headerFavoritesBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  headerIconBtnPrimary: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0C6258',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    boxShadow: '0 4px 12px rgba(12, 98, 88, 0.25)',
  },
  headerBadgeCircle: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    zIndex: 10,
  },
  headerBadgeText: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontWeight: '900',
    lineHeight: 12,
  },
  adminPillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#D1ECE6',
  },
  adminPillBtnText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#0C6258',
  },
  cartSummaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#0C6258',
    boxShadow: '0 4px 14px rgba(37, 99, 235, 0.3)',
  },
  cartSummaryBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  loggedInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  userProfileHeaderBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  userAvatarImg: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  userProfileName: {
    display: 'none',
  },
  authButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signInHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#1E293B',
  },
  signInHeaderBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  signUpHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#0C6258',
  },
  signUpHeaderBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scrollContent: {
    paddingVertical: 24,
    paddingHorizontal: 24,
  },
  maxContainer: {
    maxWidth: 1360,
    marginHorizontal: 'auto',
    width: '100%',
  },
  heroBanner: {
    backgroundColor: '#020617',
    backgroundImage: 'radial-gradient(circle at top right, #1E293B 0%, #020617 70%)',
    borderRadius: 32,
    overflow: 'hidden',
    flexDirection: 'row',
    marginBottom: 32,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  heroBannerLeft: {
    flex: 1.2,
    padding: 40,
    justifyContent: 'center',
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 24,
    alignSelf: 'flex-start',
    marginBottom: 20,
    boxShadow: '0 0 15px rgba(16, 185, 129, 0.15)',
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
    boxShadow: '0 0 8px #10B981',
  },
  heroBadgeText: {
    color: '#A7F3D0',
    fontSize: 12.5,
    fontWeight: '800',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(167, 243, 208, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  heroHeading: {
    fontSize: 36,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 44,
    letterSpacing: -1,
    marginBottom: 16,
  },
  heroSubtext: {
    fontSize: 14,
    color: '#94A3B8',
    lineHeight: 22,
    maxWidth: 520,
    marginBottom: 24,
  },
  heroCtaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  heroCtaPrimary: {
    backgroundImage: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    boxShadow: '0 8px 20px -6px rgba(16, 185, 129, 0.6)',
  },
  heroCtaPrimaryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  heroCtaSecondary: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  heroCtaSecondaryText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    fontWeight: '800',
  },
  heroBannerRight: {
    flex: 1,
    minHeight: 280,
  },
  heroProductImg: {
    width: '100%',
    height: '100%',
  },
  toolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 20,
    gap: 14,
    zIndex: 100,
  },
  toolbarLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 300,
  },
  categoryDropdownContainer: {
    position: 'relative',
    zIndex: 110,
  },
  categoryDropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    boxShadow: '0 2px 8px -2px rgba(15, 23, 42, 0.06)',
  },
  categoryDropdownBtnActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  categoryDropdownBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
  },
  categoryDropdownBtnTextActive: {
    color: '#0C6258',
  },
  categoryDropdownMenu: {
    position: 'absolute',
    top: 48,
    left: 0,
    minWidth: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    boxShadow: '0 16px 36px -6px rgba(15, 23, 42, 0.16)',
    paddingVertical: 6,
    zIndex: 120,
    overflow: 'hidden',
  },
  categoryDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 9,
    gap: 10,
  },
  categoryDropdownItemActive: {
    backgroundColor: '#F0FDF4',
  },
  categoryDropdownItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  categoryDropdownItemText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  categoryDropdownItemTextActive: {
    color: '#0C6258',
    fontWeight: '700',
  },
  categoryDropdownBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
  },
  categoryDropdownBadgeActive: {
    color: '#0C6258',
    backgroundColor: '#DCFCE7',
  },
  dropdownBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 105,
    cursor: 'default',
  },
  toolbarSearchContainer: {
    flex: 1,
    maxWidth: 380,
    minWidth: 220,
    height: 42,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
    boxShadow: '0 2px 8px -2px rgba(15, 23, 42, 0.06)',
  },
  toolbarSearchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
    outlineStyle: 'none',
  },
  categoryPillsScroll: {
    flex: 1,
  },
  categoryPillsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  catPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  catPillActive: {
    backgroundColor: '#0C6258',
    borderColor: '#0C6258',
  },
  catPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  catPillTextActive: {
    color: '#FFFFFF',
  },
  sortingGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sortBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  sortBtnActive: {
    borderColor: '#0C6258',
    backgroundColor: '#F3F7F6',
  },
  sortBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#64748B',
  },
  sortBtnTextActive: {
    color: '#0C6258',
  },
  catalogHeaderRow: {
    marginBottom: 16,
  },
  catalogTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0F172A',
  },
  catalogSub: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 40,
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.8)',
    overflow: 'hidden',
    boxShadow: '0 12px 35px -10px rgba(15, 23, 42, 0.06)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  productImgContainer: {
    width: '100%',
    height: 180,
    backgroundColor: '#F1F5F9',
    position: 'relative',
  },
  productImg: {
    width: '100%',
    height: '100%',
  },
  stockBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  stockBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
  },
  wishlistBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 2px 6px rgba(0,0,0,0.1)',
  },
  pricePill: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  pricePillText: {
    fontSize: 13.5,
    fontWeight: '900',
    color: '#F8FAFC',
    letterSpacing: 0.5,
  },
  productDetails: {
    padding: 14,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  ratingVal: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
  },
  reviewCount: {
    fontSize: 11,
    color: '#94A3B8',
  },
  brandTag: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
  },
  productName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    lineHeight: 18,
    marginBottom: 4,
    minHeight: 36,
  },
  compatibilityText: {
    fontSize: 11.5,
    color: '#64748B',
    marginBottom: 12,
  },
  cardActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quickAddBtn: {
    flex: 1,
    backgroundColor: '#F3F7F6',
    borderWidth: 1,
    borderColor: '#D1ECE6',
    borderRadius: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  quickAddBtnText: {
    color: '#0C6258',
    fontSize: 12.5,
    fontWeight: '800',
  },
  specsInspectBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  desktopFooter: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    borderRadius: 24,
    padding: 36,
    marginTop: 20,
  },
  footerTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 40,
    flexWrap: 'wrap',
    paddingBottom: 28,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  footerBrandBlock: {
    flex: 1,
    minWidth: 280,
  },
  footerTrustGrid: {
    flex: 2,
    flexDirection: 'row',
    gap: 24,
    flexWrap: 'wrap',
  },
  trustItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  trustTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  trustSub: {
    fontSize: 11.5,
    color: '#64748B',
    marginTop: 2,
  },
  footerBottomBar: {
    paddingTop: 20,
    alignItems: 'center',
  },
});

export const webStyles = shopWebStyles;
export default shopWebStyles;
